// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/whileLoop.ts#WhileLoop. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double count_down(double start) {
  double count = start;
  double steps = 0.0;
  while ((count > 0.0)) {
    count = (count - 1.0);
    steps = (steps + 1.0);
  }
  return steps;
}

inline double sum_until(flight::Array<double> values, double limit) {
  double total = 0.0;
  double index = 0.0;
  while ((index < static_cast<double>(values.size()))) {
    if (((total + values.element(index)) > limit)) {
      break;
    }
    total = (total + values.element(index));
    index = (index + 1.0);
  }
  return total;
}

} // namespace flighthq_golden
