// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/whileLoop.ts#WhileLoop. Do not edit.
#pragma once
#include <vector>

namespace flighthq_golden {

double count_down(double start) {
  double count = start;
  double steps = 0.0;
  while ((count > 0.0)) {
    count = (count - 1.0);
    steps = (steps + 1.0);
  }
  return steps;
}

double sum_until(std::vector<double> values, double limit) {
  double total = 0.0;
  double index = 0.0;
  while ((index < static_cast<double>(values.size()))) {
    if (((total + values[static_cast<size_t>(index)]) > limit)) {
      break;
    }
    total = (total + values[static_cast<size_t>(index)]);
    index = (index + 1.0);
  }
  return total;
}

} // namespace flighthq_golden
