// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/catchAwait.ts#CatchAwait. Do not edit.
#![forbid(unsafe_code)]

use flight_runtime::FlightTask;

pub async fn attempt(task: FlightTask<f64>, backup: FlightTask<f64>) -> f64 {
  let mut result: f64 = 0.0;
  match task.settle() {
    Ok(__value) => {
      result = __value;
    }
    Err(_) => {
      result = backup.await;
    }
  }
  return result;
}
