// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/exponentiation.ts#Exponentiation. Do not edit.
package flighthq.golden;

function square(x:Float):Float {
  return Math.pow(x, 2);
}

function cube(x:Float):Float {
  return Math.pow(x, 3);
}

function nthPower(base:Float, exp:Float):Float {
  return Math.pow(base, exp);
}

function squareRoot(x:Float):Float {
  return Math.pow(x, 0.5);
}

function accumPower(base:Float, exp:Float):Float {
  var result:Float = base;
  result = Math.pow(result, exp);
  return result;
}
