// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringConcat.ts#StringConcat. Do not edit.
#![forbid(unsafe_code)]

pub fn greet_user(name: String) -> String {
  return format!("Hello, {}!", name);
}

pub fn format_pair(key: String, value: f64) -> String {
  return format!("{}={}", key, value.to_string());
}

pub fn repeat(text: String, count: f64) -> String {
  let mut result: String = "".to_owned();
  {
    let mut i: f64 = 0.0;
    while i < count {
      {
        result.push_str(&text);
      }
      i += 1.0;
    }
  }
  return result;
}
