// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/logicalShortCircuit.ts#LogicalShortCircuit. Do not edit.
#![forbid(unsafe_code)]

pub fn both_positive(a: f64, b: f64) -> f64 {
  return if ((a > 0.0) && (b > 0.0)) { (a + b) } else { 0.0 };
}

pub fn either_large(a: f64, b: f64) -> bool {
  return (a > 100.0) || (b > 100.0);
}

pub fn guarded_divide(a: f64, b: f64) -> f64 {
  return if ((b != 0.0) && ((a / b) > 1.0)) { (a / b) } else { 0.0 };
}

pub fn range_check(value: f64, low: f64, high: f64) -> bool {
  return (value >= low) && (value <= high);
}
