// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/scopeShadow.ts#ScopeShadow. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double outer_inner(double value) {
  const double x_2 = value;
  if ((value > 0.0)) {
    const double x = (value * 2.0);
    return x;
  }
  return x_2;
}

inline double loop_shadow(double limit) {
  double sum = 0.0;
  {
    double i = 0.0;
    while ((i < limit)) {
      {
        const double sum_2 = (i * i);
        if ((sum_2 > 100.0)) {
          break;
        }
      }
      i += 1.0;
    }
  }
  return sum;
}

inline double parameter_shadow(double n) {
  double result = n;
  {
    double n_2 = 0.0;
    while ((n_2 < 3.0)) {
      {
        result += n_2;
      }
      n_2 += 1.0;
    }
  }
  return result;
}

} // namespace flighthq_golden
