// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/firstReplacement.ts#FirstReplacement. Do not edit.
#![forbid(unsafe_code)]

pub fn swapped(text: String) -> String {
  return text.replacen("a", "b", 1);
}
