// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericBoundary.ts#NumericBoundary. Do not edit.
#![forbid(unsafe_code)]

pub fn safe_div(a: f64, b: f64) -> f64 {
  if b == 0.0 {
    return 0.0;
  }
  return a / b;
}

pub fn clamp_int(value: f64, min: f64, max: f64) -> f64 {
  if value < min {
    return min;
  }
  if value > max {
    return max;
  }
  return f64::floor(value);
}

pub fn is_even(n: f64) -> bool {
  return (f64::floor(n) == n) && ((n - (2.0 * f64::floor((n / 2.0)))) == 0.0);
}

pub fn lerp(a: f64, b: f64, t: f64) -> f64 {
  return a + ((b - a) * t);
}
