// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/clamp.ts#Clamp. Do not edit.
package flighthq.golden;

class Clamp {
  public static final EPSILON:Float = 0.000001;

  public static function clamp(value:Float, min:Float, max:Float):Float {
    if (value < min) {
      return min;
    }
    if (value > max) {
      return max;
    }
    return value;
  }
}
