// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringAccumulate.ts#StringAccumulate. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::String join(flight::Array<flight::String> parts, flight::String separator) {
  if ((static_cast<double>(parts.size()) == 0.0)) {
    return flight::String("");
  }
  std::optional<flight::String> result = parts.get(0.0);
  {
    double i = 1.0;
    while ((i < static_cast<double>(parts.size()))) {
      {
        result = result + separator + parts.element(i);
      }
      i += 1.0;
    }
  }
  return result;
}

inline flight::String repeat(flight::String text, double count) {
  flight::String result = flight::String("");
  {
    double i = 0.0;
    while ((i < count)) {
      {
        result = result + text;
      }
      i += 1.0;
    }
  }
  return result;
}

inline flight::String wrap(flight::String text, flight::String before, flight::String after) {
  return before + text + after;
}

inline flight::String pad_left(flight::String text, double width, flight::String fill) {
  flight::String result = text;
  while ((static_cast<double>(result.length()) < width)) {
    result = fill + result;
  }
  return result;
}

} // namespace flighthq_golden
