// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/interfaceReturn.ts#InterfaceReturn. Do not edit.
#pragma once

namespace flighthq_golden {

struct point {
  double x;
  double y;
};

point origin() {
  return {.x = 0.0, .y = 0.0};
}

point from_values(double x, double y) {
  return {.x = x, .y = y};
}

point translate(point p, double dx, double dy) {
  return {.x = (p.x + dx), .y = (p.y + dy)};
}

double distance(point a, point b) {
  const double dx = (a.x - b.x);
  const double dy = (a.y - b.y);
  return std::sqrt(((dx * dx) + (dy * dy)));
}

} // namespace flighthq_golden
