// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedProperty.ts#NestedProperty. Do not edit.
#pragma once

namespace flighthq_golden {

struct point {
  double x;
  double y;
};

struct rect {
  point origin;
  point size;
};

double area(rect rect) {
  return (rect.size.x * rect.size.y);
}

rect translate(rect rect, double dx, double dy) {
  return {.origin = {.x = (rect.origin.x + dx), .y = (rect.origin.y + dy)}, .size = rect.size};
}

double diagonal(rect rect) {
  const double w = rect.size.x;
  const double h = rect.size.y;
  return std::sqrt(((w * w) + (h * h)));
}

} // namespace flighthq_golden
