// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/indexSignatureRecordCarrier.ts#IndexSignatureRecordCarrier. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Scalar = Dynamic;

typedef Fields = {  };

function read(fields:Fields, key:String):Null<Scalar> {
  return HaxeReflect.field(fields, key);
}

function write(fields:Fields, key:String, value:Scalar):Void {
  (function() { final assignmentReceiver:Dynamic = fields; final assignmentKey:Dynamic = key; final assignmentValue:Dynamic = value; flighthq._internal._Js.setProperty(assignmentReceiver, assignmentKey, assignmentValue); return assignmentValue; })();
}

function present(fields:Fields, key:String):Bool {
  return js.Syntax.strictNeq(HaxeReflect.field(fields, key), js.Syntax.code("undefined"));
}
