// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/runtimeExternalTypes.ts#RuntimeExternalTypes. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

struct values_task_bytes {
  flight::Map<flight::String, double> values;
  flight::Task<double> task;
  flight::Uint8Array bytes;
};

using RuntimeTypes = values_task_bytes;

} // namespace flighthq_golden
