// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/recordConstruction.ts#RecordConstruction. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Entry = { key:String, value:Float };

function appended(entries:Array<Entry>, key:String, value:Float):Array<Entry> {
  final next:Array<Entry> = entries.copy();
  next.push((cast { key: key, value: value } : Entry));
  return next;
}

function tailSize(entries:Array<Entry>, index:Float):Float {
  return entries.slice(Std.int(index)).length;
}
