// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/multipleInterface.ts#MultipleInterface. Do not edit.
package flighthq.golden;

typedef Named = { name:String };

typedef Valued = { value:Float };

function getName(item:Named):String {
  return item.name;
}

function getValue(item:Valued):Float {
  return item.value;
}

function formatNamed(item:Named):String {
  return "item: " + item.name;
}

function isPositive(item:Valued):Bool {
  return item.value > 0;
}
