import path from 'node:path';

import { createBackendEmissionFailure, indentSourceLines } from '../../compiler-emission/src/index.js';
import type { CompilerBackend, EmittedFile, RustCompilerBackendOptions } from '../../compiler-types/src/index.js';
import type {
  IrClassDeclaration,
  IrDeclaration,
  IrEnumDeclaration,
  IrExpression,
  IrFunctionDeclaration,
  IrImport,
  IrInterfaceDeclaration,
  IrModule,
  IrObjectTypeMember,
  IrParameter,
  IrStatement,
  IrType,
  IrTypeDeclaration,
  IrTypeParameter,
  IrVariable,
  IrVariableDeclaration,
} from '../../compiler-types/src/index.js';

interface EmitContext {
  constants: ReadonlyMap<string, string>;
  localNames: ReadonlySet<string>;
  module: Readonly<IrModule>;
  options: Readonly<RustCompilerBackendOptions>;
}

export function convertPackageNameToRustCrateName(packageName: string): string {
  const bareName = packageName.replace(/^@[^/]+\//u, '');
  if (bareName.length === 0) throw new Error(`Cannot map empty npm package name: ${packageName}`);
  return `flighthq-${bareName.replaceAll('_', '-').toLowerCase()}`;
}

export function convertSourcePathToRustModuleName(sourcePath: string): string | undefined {
  const filename = path.basename(sourcePath).replace(/\.tsx?$/u, '');
  if (
    filename.toLowerCase() === 'index' ||
    filename.toLowerCase() === 'internal' ||
    /test(?:helper|util)/iu.test(filename)
  ) {
    return undefined;
  }
  return snakeCase(filename);
}

export function createRustCompilerBackend(): CompilerBackend<RustCompilerBackendOptions> {
  return {
    emitModule(module, { options }) {
      return [emitIrModuleRust(module, options)];
    },
    name: 'rust',
  };
}

export function emitIrModuleRust(
  module: Readonly<IrModule>,
  options: Readonly<RustCompilerBackendOptions> = {},
): EmittedFile {
  const constants = new Map(
    module.declarations.flatMap((declaration) =>
      declaration.kind === 'variable' && !declaration.mutable
        ? [[declaration.name, screamingSnakeCase(declaration.name)]]
        : [],
    ),
  );
  const context: EmitContext = { constants, localNames: new Set(), module, options };
  if (module.exports.length > 0) {
    emissionError(context, 're-exports and export assignments require Rust module-facade lowering');
  }
  const lines = [
    options.generatedHeader ?? '// Generated by @flighthq/tool-compiler. Do not edit.',
    '#![forbid(unsafe_code)]',
  ];
  const imports = emitImports(module.imports, context);
  if (imports.length > 0) lines.push('', ...imports);
  module.declarations.forEach((declaration) => {
    lines.push('', ...emitDeclaration(declaration, context));
  });
  return {
    contents: lines.join('\n'),
    path: `${convertSourcePathToRustModuleName(module.source) ?? `_internal_${snakeCase(module.name)}`}.rs`,
  };
}

function emitClass(declaration: Readonly<IrClassDeclaration>, context: EmitContext): string[] {
  if (declaration.extends || declaration.implements.length > 0) {
    emissionError(context, `class ${declaration.name} inheritance requires Rust ownership lowering`);
  }
  if (declaration.constructorParameters.length > 0 || declaration.constructorBody.length > 0) {
    emissionError(context, `class ${declaration.name} constructor requires Rust initialization lowering`);
  }
  if (declaration.abstract) emissionError(context, `abstract class ${declaration.name} requires Rust trait lowering`);
  if (declaration.fields.some((field) => field.static)) {
    emissionError(context, `class ${declaration.name} static fields require associated-item lowering`);
  }
  if (declaration.fields.some((field) => field.initializer)) {
    emissionError(context, `class ${declaration.name} field initializers require constructor lowering`);
  }
  const lines = [
    '#[derive(Clone, Debug)]',
    `${declaration.exported ? 'pub ' : ''}struct ${safeRustTypeName(declaration.name)}${emitTypeParameters(declaration.typeParameters, context)} {`,
  ];
  for (const field of declaration.fields) {
    lines.push(
      `    ${field.visibility === 'public' ? 'pub ' : ''}${safeRustValueName(field.name)}: ${emitType(field.type, context)},`,
    );
  }
  lines.push('}');
  if (declaration.methods.length > 0) {
    lines.push(
      '',
      `impl${emitTypeParameters(declaration.typeParameters, context)} ${safeRustTypeName(declaration.name)}${emitTypeArguments(declaration.typeParameters)} {`,
    );
    declaration.methods.forEach((method, index) => {
      if (index > 0) lines.push('');
      if (method.async) emissionError(context, `async method ${method.name} requires Flight task lowering`);
      const parameters = [
        ...(method.static ? [] : ['&mut self']),
        ...method.parameters.map((parameter) => emitParameter(parameter, context)),
      ].join(', ');
      const methodContext = withLocalNames(
        context,
        method.parameters.map((parameter) => parameter.name),
        method.static ? [] : ['this'],
      );
      lines.push(
        `  ${method.visibility === 'public' ? 'pub ' : ''}fn ${safeRustValueName(method.name)}${emitTypeParameters(method.typeParameters, context)}(${parameters}) -> ${emitType(method.returns, context)} {`,
        ...indentSourceLines(emitStatements(method.body, methodContext), 2),
        '  }',
      );
    });
    lines.push('}');
  }
  return lines;
}

function emitDeclaration(declaration: Readonly<IrDeclaration>, context: EmitContext): string[] {
  switch (declaration.kind) {
    case 'class':
      return emitClass(declaration, context);
    case 'enum':
      return emitEnum(declaration, context);
    case 'function':
      return emitFunction(declaration, context);
    case 'interface':
      return emitInterface(declaration, context);
    case 'type':
      return emitTypeAlias(declaration, context);
    case 'variable':
      return emitVariableDeclaration(declaration, context);
  }
}

function emitEnum(declaration: Readonly<IrEnumDeclaration>, context: EmitContext): string[] {
  if (declaration.members.some((member) => typeof member.value !== 'number' || !Number.isInteger(member.value))) {
    emissionError(context, `enum ${declaration.name} requires integer discriminants for Rust`);
  }
  if (
    declaration.members.some((member) => Number(member.value) < -2_147_483_648 || Number(member.value) > 2_147_483_647)
  ) {
    emissionError(context, `enum ${declaration.name} has a discriminant outside the Rust i32 range`);
  }
  const lines = [
    '#[derive(Clone, Copy, Debug, PartialEq, Eq)]',
    '#[repr(i32)]',
    `${declaration.exported ? 'pub ' : ''}enum ${safeRustTypeName(declaration.name)} {`,
  ];
  declaration.members.forEach((member) => {
    lines.push(`  ${safeRustTypeName(member.name)} = ${String(member.value)},`);
  });
  lines.push('}');
  return lines;
}

function emitExpression(expression: Readonly<IrExpression>, context: EmitContext): string {
  switch (expression.kind) {
    case 'array':
      return `vec![${expression.elements.map((element) => (element ? emitExpression(element, context) : 'Default::default()')).join(', ')}]`;
    case 'assignment':
      return `${emitExpression(expression.left, context)} ${mapOperator(expression.operator, true, context)} ${emitExpression(expression.right, context)}`;
    case 'await':
      emissionError(context, 'await requires Flight task lowering');
    case 'binary':
      return `(${emitExpression(expression.left, context)} ${mapOperator(expression.operator, false, context)} ${emitExpression(expression.right, context)})`;
    case 'call':
      if (expression.optional) emissionError(context, 'optional calls require Option-aware lowering');
      return `${emitExpression(expression.callee, context)}(${expression.arguments.map((argument) => emitExpression(argument, context)).join(', ')})`;
    case 'cast':
      return `(${emitExpression(expression.expression, context)} as ${emitType(expression.type, context)})`;
    case 'conditional':
      return `if ${emitExpression(expression.condition, context)} { ${emitExpression(expression.whenTrue, context)} } else { ${emitExpression(expression.whenFalse, context)} }`;
    case 'element':
      if (expression.optional) emissionError(context, 'optional element access requires Option-aware lowering');
      return `${emitExpression(expression.object, context)}[${emitExpression(expression.index, context)} as usize]`;
    case 'function':
      if (expression.async) emissionError(context, 'async closures require Flight task lowering');
      if (expression.typeParameters.length > 0) emissionError(context, 'generic closures require monomorphization');
      {
        const functionContext = withLocalNames(
          context,
          expression.parameters.map((parameter) => parameter.name),
        );
        return expression.expression
          ? `|${expression.parameters.map((parameter) => safeRustValueName(parameter.name)).join(', ')}| ${emitExpression(expression.expression, functionContext)}`
          : `|${expression.parameters.map((parameter) => safeRustValueName(parameter.name)).join(', ')}| {\n${indentSourceLines(emitStatements(expression.body, functionContext)).join('\n')}\n}`;
      }
    case 'identifier':
      return context.localNames.has(expression.name)
        ? safeRustValueName(expression.name)
        : (context.constants.get(expression.name) ?? safeRustValueName(expression.name));
    case 'literal':
      return emitLiteral(expression.value);
    case 'new':
      if (expression.callee.kind !== 'identifier') {
        emissionError(context, 'qualified constructors require Rust type-path lowering');
      }
      return `${safeRustTypeName(expression.callee.name)}::new(${expression.arguments.map((argument) => emitExpression(argument, context)).join(', ')})`;
    case 'object':
      emissionError(context, 'anonymous object construction requires Rust structural-type lowering');
    case 'property':
      if (expression.optional) emissionError(context, 'optional property access requires Option-aware lowering');
      return `${emitExpression(expression.object, context)}.${safeRustValueName(expression.name)}`;
    case 'regexp':
      emissionError(context, 'regular expressions require a downstream standard-library mapping');
    case 'spread':
      emissionError(context, 'spread expressions require collection or structural lowering');
    case 'template': {
      const format = expression.parts
        .map((part) => (typeof part === 'string' ? part.replaceAll('{', '{{').replaceAll('}', '}}') : '{}'))
        .join('');
      const values = expression.parts.flatMap((part) =>
        typeof part === 'string' ? [] : [emitExpression(part, context)],
      );
      return `format!(${JSON.stringify(format)}${values.length > 0 ? `, ${values.join(', ')}` : ''})`;
    }
    case 'unary': {
      const operand = emitExpression(expression.operand, context);
      if (expression.operator === 'typeof' || expression.operator === 'delete' || expression.operator === 'void') {
        emissionError(context, `${expression.operator} requires Rust semantic lowering`);
      }
      if (expression.operator === '++' || expression.operator === '--') {
        emissionError(
          context,
          `${expression.postfix ? 'postfix' : 'prefix'} ${expression.operator} requires value-preserving Rust lowering`,
        );
      }
      if (expression.postfix || (expression.operator !== '!' && expression.operator !== '-')) {
        emissionError(context, `operator ${expression.operator} requires Rust semantic lowering`);
      }
      return `${expression.operator}${operand}`;
    }
  }
}

function emitFunction(declaration: Readonly<IrFunctionDeclaration>, context: EmitContext): string[] {
  if (declaration.async) emissionError(context, `async function ${declaration.name} requires Flight task lowering`);
  const functionContext = withLocalNames(
    context,
    declaration.parameters.map((parameter) => parameter.name),
  );
  return [
    `${declaration.exported ? 'pub ' : ''}fn ${safeRustValueName(declaration.name)}${emitTypeParameters(declaration.typeParameters, context)}(${declaration.parameters.map((parameter) => emitParameter(parameter, context)).join(', ')}) -> ${emitType(declaration.returns, context)} {`,
    ...indentSourceLines(emitStatements(declaration.body, functionContext)),
    '}',
  ];
}

function emitImports(imports: readonly IrImport[], context: EmitContext): string[] {
  const lines = new Set<string>();
  for (const imported of imports) {
    if (imported.bindings.length === 0) continue;
    const module = rustImportModule(imported.specifier, context);
    const names = imported.bindings.map((binding) => {
      if (binding.imported === '*' || binding.imported === 'default') {
        emissionError(context, `${binding.imported} imports require explicit Rust mapping for ${imported.specifier}`);
      }
      const importedName = /^[A-Z]/u.test(binding.imported)
        ? safeRustTypeName(binding.imported)
        : safeRustValueName(binding.imported);
      const localName = /^[A-Z]/u.test(binding.local)
        ? safeRustTypeName(binding.local)
        : safeRustValueName(binding.local);
      return importedName === localName ? importedName : `${importedName} as ${localName}`;
    });
    lines.add(`use ${module}::{${names.sort().join(', ')}};`);
  }
  return [...lines].sort();
}

function emitInterface(declaration: Readonly<IrInterfaceDeclaration>, context: EmitContext): string[] {
  if (declaration.extends.length > 0)
    emissionError(context, `interface ${declaration.name} inheritance requires record flattening`);
  return emitRecord(declaration.name, declaration.members, declaration.typeParameters, declaration.exported, context);
}

function emitLiteral(value: boolean | null | number | string): string {
  if (typeof value === 'string') return `${JSON.stringify(value)}.to_owned()`;
  if (value === null) return 'None';
  if (typeof value === 'number' && Number.isInteger(value)) return `${String(value)}.0`;
  return String(value);
}

function emitParameter(parameter: Readonly<IrParameter>, context: EmitContext): string {
  if (parameter.initializer) emissionError(context, `default parameter ${parameter.name} requires call-site lowering`);
  if (parameter.optional) {
    return `${safeRustValueName(parameter.name)}: Option<${emitType(parameter.type, context)}>`;
  }
  if (parameter.rest) return `${safeRustValueName(parameter.name)}: Vec<${emitType(parameter.type, context)}>`;
  return `${safeRustValueName(parameter.name)}: ${emitType(parameter.type, context)}`;
}

function emitRecord(
  name: string,
  members: readonly IrObjectTypeMember[],
  typeParameters: readonly IrTypeParameter[],
  exported: boolean,
  context: EmitContext,
): string[] {
  const lines = [
    '#[derive(Clone, Debug)]',
    `${exported ? 'pub ' : ''}struct ${safeRustTypeName(name)}${emitTypeParameters(typeParameters, context)} {`,
  ];
  for (const member of members) {
    const type = emitType(member.type, context);
    lines.push(`  pub ${safeRustValueName(member.name)}: ${member.optional ? `Option<${type}>` : type},`);
  }
  lines.push('}');
  return lines;
}

function emitStatement(statement: Readonly<IrStatement>, context: EmitContext): string[] {
  switch (statement.kind) {
    case 'block':
      return ['{', ...indentSourceLines(emitStatements(statement.statements, context)), '}'];
    case 'break':
      return ['break;'];
    case 'continue':
      return ['continue;'];
    case 'do':
      return [
        'loop {',
        ...indentSourceLines(emitStatementBody(statement.body, context)),
        `  if !(${emitExpression(statement.condition, context)}) { break; }`,
        '}',
      ];
    case 'expression':
      return [`${emitExpression(statement.expression, context)};`];
    case 'for':
      emissionError(context, 'C-style for loops require control-flow lowering before Rust emission');
    case 'forIn':
      emissionError(context, 'object key iteration requires record or host-object lowering');
    case 'forOf':
      if (statement.await) emissionError(context, 'async iteration requires Flight task lowering');
      {
        const loopContext = withLocalNames(context, [statement.variable.name]);
        return [
          `for ${statement.variable.mutable ? 'mut ' : ''}${safeRustValueName(statement.variable.name)} in ${emitExpression(statement.iterable, context)} {`,
          ...indentSourceLines(emitStatementBody(statement.body, loopContext)),
          '}',
        ];
      }
    case 'if': {
      const lines = [
        `if ${emitExpression(statement.condition, context)} {`,
        ...indentSourceLines(emitStatementBody(statement.consequent, context)),
        '}',
      ];
      if (statement.otherwise)
        lines.push('else {', ...indentSourceLines(emitStatementBody(statement.otherwise, context)), '}');
      return lines;
    }
    case 'return':
      return [`return${statement.expression ? ` ${emitExpression(statement.expression, context)}` : ''};`];
    case 'switch': {
      emissionError(context, 'switch statements require exhaustive, fallthrough-aware Rust lowering');
    }
    case 'throw':
      return [`panic!("{:?}", ${emitExpression(statement.expression, context)});`];
    case 'try':
      emissionError(context, 'try/catch/finally requires Flight rejection lowering');
    case 'variable':
      return statement.declarations.map((variable) => emitVariable(variable, context));
    case 'while':
      return [
        `while ${emitExpression(statement.condition, context)} {`,
        ...indentSourceLines(emitStatementBody(statement.body, context)),
        '}',
      ];
  }
}

function emitStatementBody(statement: Readonly<IrStatement>, context: EmitContext): string[] {
  return statement.kind === 'block'
    ? emitStatements(statement.statements, context)
    : emitStatements([statement], context);
}

function emitStatements(statements: readonly IrStatement[], context: EmitContext): string[] {
  const blockContext = withLocalNames(
    context,
    statements.flatMap((statement) =>
      statement.kind === 'variable' ? statement.declarations.map((variable) => variable.name) : [],
    ),
  );
  return statements.flatMap((statement) => emitStatement(statement, blockContext));
}

function emitType(type: Readonly<IrType>, context: EmitContext): string {
  switch (type.kind) {
    case 'array':
      return `Vec<${emitType(type.element, context)}>`;
    case 'function': {
      const parameters = type.parameters.map((parameter) => emitType(parameter.type, context));
      return `FlightCallback<(${parameters.join(', ')}${parameters.length === 1 ? ',' : ''}), ${emitType(type.returns, context)}>`;
    }
    case 'indexedAccess':
    case 'keyof':
    case 'typeOf':
      return opaqueHostType(context);
    case 'intersection':
      emissionError(context, 'intersection types require Rust record or trait lowering');
    case 'literal':
      return typeof type.value === 'boolean' ? 'bool' : typeof type.value === 'number' ? 'f64' : 'String';
    case 'named': {
      if ((type.name === 'Readonly' || type.name === 'Required') && type.typeArguments[0]) {
        return emitType(type.typeArguments[0], context);
      }
      if (type.name === 'Partial' && type.typeArguments[0])
        emissionError(context, 'Partial<T> requires structural field lowering');
      const mapped = rustStandardType(type.name);
      const arguments_ = type.typeArguments.map((argument) => emitType(argument, context));
      return `${mapped}${arguments_.length > 0 ? `<${arguments_.join(', ')}>` : ''}`;
    }
    case 'never':
      return '!';
    case 'null':
    case 'undefined':
      return '()';
    case 'object':
      emissionError(context, 'anonymous object types require Rust record interning');
    case 'primitive':
      return { bigint: 'i64', boolean: 'bool', number: 'f64', string: 'String', symbol: 'FlightSymbol', void: '()' }[
        type.name
      ];
    case 'tuple': {
      const elements = type.elements.map((element) => emitType(element.type, context));
      return `(${elements.join(', ')}${elements.length === 1 ? ',' : ''})`;
    }
    case 'union': {
      const concrete = type.types.filter((item) => item.kind !== 'null' && item.kind !== 'undefined');
      if (concrete.length === 1 && concrete.length !== type.types.length)
        return `Option<${emitType(concrete[0]!, context)}>`;
      emissionError(context, 'non-nullable unions require Rust tagged-union lowering');
    }
    case 'unknown':
      return opaqueHostType(context);
  }
}

function emitTypeAlias(declaration: Readonly<IrTypeDeclaration>, context: EmitContext): string[] {
  if (declaration.type.kind === 'object') {
    return emitRecord(
      declaration.name,
      declaration.type.members,
      declaration.typeParameters,
      declaration.exported,
      context,
    );
  }
  return [
    `${declaration.exported ? 'pub ' : ''}type ${safeRustTypeName(declaration.name)}${emitTypeParameters(declaration.typeParameters, context)} = ${emitType(declaration.type, context)};`,
  ];
}

function emitTypeArguments(parameters: readonly IrTypeParameter[]): string {
  return parameters.length === 0
    ? ''
    : `<${parameters.map((parameter) => safeRustTypeName(parameter.name)).join(', ')}>`;
}

function emitTypeParameters(parameters: readonly IrTypeParameter[], context: EmitContext): string {
  if (parameters.length === 0) return '';
  return `<${parameters
    .map((parameter) => {
      const name = safeRustTypeName(parameter.name);
      return `${name}${parameter.constraint ? `: ${emitType(parameter.constraint, context)}` : ''}`;
    })
    .join(', ')}>`;
}

function emitVariable(variable: Readonly<IrVariable>, context: EmitContext): string {
  const type = variable.type ? `: ${emitType(variable.type, context)}` : '';
  const initializer = variable.initializer ? ` = ${emitExpression(variable.initializer, context)}` : '';
  return `let ${variable.mutable ? 'mut ' : ''}${safeRustValueName(variable.name)}${type}${initializer};`;
}

function emitVariableDeclaration(declaration: Readonly<IrVariableDeclaration>, context: EmitContext): string[] {
  if (!declaration.initializer || !declaration.type) {
    emissionError(context, `module variable ${declaration.name} requires an initializer and type`);
  }
  if (declaration.mutable)
    emissionError(context, `mutable module variable ${declaration.name} requires synchronization lowering`);
  return [
    `${declaration.exported ? 'pub ' : ''}const ${context.constants.get(declaration.name)!}: ${emitType(declaration.type, context)} = ${emitExpression(declaration.initializer, context)};`,
  ];
}

function emissionError(context: EmitContext, message: string): never {
  throw createBackendEmissionFailure('rust', context.module.source, message);
}

function mapOperator(operator: string, assignment: boolean, context: EmitContext): string {
  const allowed = assignment ? rustAssignmentOperators : rustBinaryOperators;
  if (!allowed.has(operator)) emissionError(context, `operator ${operator} requires Rust semantic lowering`);
  if (operator === '===' || operator === '==') return '==';
  if (operator === '!==' || operator === '!=') return '!=';
  return operator;
}

function withLocalNames(
  context: EmitContext,
  names: readonly string[],
  additional: readonly string[] = [],
): EmitContext {
  return {
    ...context,
    localNames: new Set([...context.localNames, ...additional, ...names]),
  };
}

function opaqueHostType(context: EmitContext): string {
  return context.options.opaqueHostType ?? 'OpaqueHostValue';
}

function rustImportModule(specifier: string, context: EmitContext): string {
  if (specifier.startsWith('.')) {
    const target = path.posix.normalize(
      path.posix.join(path.posix.dirname(context.module.source), specifier.replace(/\.[cm]?js$/u, '')),
    );
    return `crate::${convertSourcePathToRustModuleName(target) ?? `_internal_${snakeCase(path.posix.basename(target))}`}`;
  }
  if (specifier.startsWith('@')) {
    const packageName = /^(@[^/]+\/[^/]+)/u.exec(specifier)?.[1];
    if (!packageName) emissionError(context, `cannot identify package import ${specifier}`);
    return convertPackageNameToRustCrateName(packageName).replaceAll('-', '_');
  }
  emissionError(context, `external import ${specifier} requires a runtime or standard-library mapping`);
}

function rustStandardType(name: string): string {
  return (
    (
      {
        Array: 'Vec',
        Boolean: 'bool',
        Float32Array: 'Vec<f32>',
        Float64Array: 'Vec<f64>',
        Int16Array: 'Vec<i16>',
        Int32Array: 'Vec<i32>',
        Int8Array: 'Vec<i8>',
        Map: 'std::collections::HashMap',
        Promise: 'FlightTask',
        Set: 'std::collections::HashSet',
        Uint16Array: 'Vec<u16>',
        Uint32Array: 'Vec<u32>',
        Uint8Array: 'Vec<u8>',
        Uint8ClampedArray: 'Vec<u8>',
      } as Readonly<Record<string, string>>
    )[name] ?? safeRustTypeName(name)
  );
}

function safeRustTypeName(name: string): string {
  const value = name
    .split('.')
    .map((segment) => pascalCase(segment))
    .join('::');
  return rustKeywords.has(value) ? `${value}_` : value;
}

function safeRustValueName(name: string): string {
  if (name === 'this') return 'self';
  const value = snakeCase(name);
  return rustKeywords.has(value) ? `${value}_` : value;
}

function pascalCase(value: string): string {
  return value
    .split(/[-_]/u)
    .filter(Boolean)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join('');
}

function screamingSnakeCase(value: string): string {
  return snakeCase(value).toUpperCase();
}

function snakeCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/gu, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/gu, '$1_$2')
    .replace(/[-\s]+/gu, '_')
    .toLowerCase();
}

const rustKeywords = new Set([
  'abstract',
  'as',
  'async',
  'await',
  'break',
  'become',
  'box',
  'const',
  'continue',
  'crate',
  'dyn',
  'do',
  'else',
  'enum',
  'extern',
  'false',
  'fn',
  'final',
  'gen',
  'for',
  'if',
  'impl',
  'in',
  'let',
  'loop',
  'macro',
  'macro_rules',
  'match',
  'mod',
  'move',
  'mut',
  'override',
  'priv',
  'pub',
  'ref',
  'return',
  'self',
  'Self',
  'static',
  'struct',
  'super',
  'trait',
  'try',
  'true',
  'type',
  'typeof',
  'union',
  'unsafe',
  'unsized',
  'use',
  'where',
  'while',
  'virtual',
  'yield',
]);

const rustAssignmentOperators = new Set(['=', '+=', '-=', '*=', '/=', '%=', '&=', '|=', '^=', '<<=', '>>=']);

const rustBinaryOperators = new Set([
  '!==',
  '!=',
  '%',
  '&',
  '&&',
  '*',
  '+',
  '-',
  '/',
  '<',
  '<<',
  '<=',
  '===',
  '==',
  '>',
  '>=',
  '>>',
  '^',
  '|',
  '||',
]);
