import ts from 'typescript';

import { isBackendEmissionFailure } from '../../compiler-emission/src/index.js';
import { lowerTypeScriptSource } from '../../compiler-semantic/src/index.js';
import { createRustCompilerBackend, emitIrModuleRust } from './rustCompilerBackend.js';

function lower(file: string, source: string) {
  const sourceFile = ts.createSourceFile(`/flight/packages/math/src/${file}`, source, ts.ScriptTarget.Latest, true);
  return lowerTypeScriptSource(sourceFile, {
    packageName: '@flighthq/math',
    upstreamDirectory: '/flight',
  });
}

describe('createRustCompilerBackend', () => {
  it('creates independent stateless backend records with Rust identity', () => {
    const first = createRustCompilerBackend();
    const second = createRustCompilerBackend();
    const module = lower('value.ts', 'export const value = 1;').module;

    expect(first).not.toBe(second);
    expect(first.name).toBe('rust');
    expect(first.emitModule(module, { modules: [], options: {} })).toEqual([emitIrModuleRust(module)]);
  });
});

describe('emitIrModuleRust', () => {
  it('emits shared traceable provenance with an optional upstream commit', () => {
    const module = lower('value.ts', 'export const value = 1;').module;
    const commit = '0123456789abcdef0123456789abcdef01234567';

    expect(emitIrModuleRust(module).contents.split('\n')[0]).toBe(
      '// Generated by @flighthq/tool-compiler from @flighthq/math/packages/math/src/value.ts#Value. Do not edit.',
    );
    expect(emitIrModuleRust(module, { upstreamCommit: commit }).contents.split('\n')[0]).toBe(
      `// Generated by @flighthq/tool-compiler from @flighthq/math/packages/math/src/value.ts#Value at ${commit}. Do not edit.`,
    );
  });

  it('emits explicit type and value runtime bindings and rejects incomplete symbol spaces first', () => {
    const supported = lower(
      'external-types.ts',
      'export function preserve(values: Map<string, number>, bytes: Uint8Array, task: Promise<number>): Promise<number> { values; bytes; return task; }',
    );
    const missing = lower('external-missing.ts', 'export type fooBar = Date; export type foo_bar = Date;');
    const missingValue = lower(
      'external-value-missing.ts',
      'export function maximum(left: number, right: number): number { return Math.max(left, right); }',
    );
    const values = lower(
      'external-values.ts',
      'export function create(): Promise<number> { const values = new Map<string, number>(); values; return Promise.resolve(1); }',
    );
    const output = emitIrModuleRust(supported.module).contents;
    const valueOutput = emitIrModuleRust(values.module).contents;

    expect(output).toContain('values: std::collections::HashMap<String, f64>');
    expect(output).toContain('bytes: Vec<u8>');
    expect(output).toContain('task: FlightTask<f64>');
    expect(valueOutput).toContain('std::collections::HashMap::new()');
    expect(valueOutput).toContain('FlightTask::resolve(1.0)');
    expect(() => emitIrModuleRust(missing.module)).toThrow(
      'runtime external symbol binding plan is incomplete (missing: Date[type])',
    );
    expect(() => emitIrModuleRust(missingValue.module)).toThrow(
      'runtime external symbol binding plan is incomplete (missing: Math[value])',
    );
  });

  it('elects C-style for lowering while preserving Rust default-parameter refusal', () => {
    const loop = lower(
      'loop.ts',
      'export function total(limit: number): number { let total = 0; for (let index = 0; index < limit; index++) { total += index; } return total; }',
    );
    const defaults = lower(
      'defaults.ts',
      'export function scale(value: number, factor: number = 2): number { return value * factor; }',
    );
    const output = emitIrModuleRust(loop.module).contents;

    expect(output).toContain('let mut index: f64 = 0.0;');
    expect(output).toContain('while (index < limit)');
    expect(output).toContain('index += 1.0;');
    expect(() => emitIrModuleRust(defaults.module)).toThrow('default parameter factor requires call-site lowering');
  });

  it('elects fixed array binding lowering and reports residual destructuring semantics', () => {
    const fixed = lower(
      'array-binding.ts',
      'export function select(values: [number, number, number]): number { const [first, , third]: [number, number, number] = values; third; return first; }',
    );
    const rest = lower(
      'array-rest.ts',
      'export function select(values: [number, ...number[]]): number[] { const [first, ...rest]: [number, ...number[]] = values; first; return rest; }',
    );
    const defaulted = lower(
      'array-default.ts',
      'export function select(values: [number?]): number { const [first = 0]: [number?] = values; return first; }',
    );
    const requiredDefault = lower(
      'array-required-default.ts',
      'export function select(values: [number | undefined]): number { const [first = 0]: [number | undefined] = values; return first; }',
    );
    const dynamicIndex = lower(
      'tuple-index.ts',
      'export function select(values: [number], index: number): number { return values[index]; }',
    );
    const nestedDefault = lower(
      'array-nested-default.ts',
      'export function select(values: [[number]?]): number { const [[first] = [1]]: [[number]?] = values; return first; }',
    );
    const fixedRest = lower(
      'array-fixed-rest.ts',
      'export function select(values: [number, string, boolean]): [string, boolean] { const [first, ...rest]: [number, string, boolean] = values; first; return rest; }',
    );
    const emptyRest = lower(
      'array-empty-rest.ts',
      'export function select(values: [number]): [] { const [first, ...rest]: [number] = values; first; return rest; }',
    );
    const optionalRest = lower(
      'array-optional-rest.ts',
      'export function select(values: [number, string?]): [string?] { const [first, ...rest]: [number, string?] = values; first; return rest; }',
    );
    const mixedRest = lower(
      'array-mixed-rest.ts',
      'export function select(values: [number, string, ...boolean[]]): [string, ...boolean[]] { const [first, ...rest]: [number, string, ...boolean[]] = values; first; return rest; }',
    );
    const iteration = lower(
      'array-iteration.ts',
      'export function visit(rows: Array<[number, number]>): number { for (const [first, second] of rows) { second; return first; } return 0; }',
    );
    const output = emitIrModuleRust(fixed.module).contents;

    expect(output).toContain('let array_pattern_value: (f64, f64, f64) = values;');
    expect(output).toContain('let first: f64 = array_pattern_value.0;');
    expect(output).toContain('let third: f64 = array_pattern_value.2;');
    expect(emitIrModuleRust(defaulted.module).contents).toContain(
      'let first: f64 = array_pattern_value.0.unwrap_or_else(|| 0.0);',
    );
    expect(emitIrModuleRust(requiredDefault.module).contents).toContain(
      'let first: f64 = array_pattern_value.0.unwrap_or_else(|| 0.0);',
    );
    expect(emitIrModuleRust(rest.module).contents).toContain('let rest: Vec<f64> = array_pattern_value.1;');
    expect(emitIrModuleRust(nestedDefault.module).contents).toContain('unwrap_or_else(|| (1.0,))');
    expect(emitIrModuleRust(fixedRest.module).contents).toContain(
      'let rest: (String, bool) = (array_pattern_value.1, array_pattern_value.2);',
    );
    expect(emitIrModuleRust(emptyRest.module).contents).toContain('let rest: () = ();');
    expect(emitIrModuleRust(optionalRest.module).contents).toContain(
      'let rest: (Option<String>,) = (array_pattern_value.1,);',
    );
    expect(emitIrModuleRust(mixedRest.module).contents).toContain(
      'let rest: (String, Vec<bool>) = (array_pattern_value.1, array_pattern_value.2);',
    );
    expect(emitIrModuleRust(iteration.module).contents).toContain(
      'for array_pattern_value in rows {\n    let first: f64 = array_pattern_value.0;\n    let second: f64 = array_pattern_value.1;',
    );
    expect(() => emitIrModuleRust(dynamicIndex.module)).toThrow(
      'tuple projection requires one statically known nonnegative integer index',
    );
  });

  it('elects function-scoped variable hoisting after destructuring normalization', () => {
    const named = lower(
      'variable-hoisting.ts',
      'export function select(): number { { var value: number = 1; } return value; }',
    );
    const pattern = lower(
      'variable-pattern-hoisting.ts',
      'export function select(values: [number, string]): string { var [first, second]: [number, string] = values; first; return second; }',
    );
    const iteration = lower(
      'variable-iteration-hoisting.ts',
      'export function visit(values: number[]): void { for (var value of values) value += 1; }',
    );
    const namedOutput = emitIrModuleRust(named.module).contents;
    const patternOutput = emitIrModuleRust(pattern.module).contents;
    const iterationOutput = emitIrModuleRust(iteration.module).contents;

    expect(namedOutput).toContain('let mut value: f64;\n  {\n    value = 1.0;\n  }\n  return value;');
    expect(patternOutput).toContain(
      'let mut first: f64;\n  let mut second: String;\n  let array_pattern_value: (f64, String) = values;\n  first = array_pattern_value.0;\n  second = array_pattern_value.1;',
    );
    expect(iterationOutput).toContain(
      'let mut value: f64;\n  for variable_hoisting_iteration_value in values {\n    value = variable_hoisting_iteration_value;\n    value += 1.0;',
    );
  });

  it('emits contextual fixed tuple expressions with explicit optional positions', () => {
    const result = lower(
      'tuple-expression.ts',
      "export function create(): [number, string?] { const present: [number, string?] = [1, 'flight']; const value: [number, string?] = [2]; present; return value; }",
    );

    expect(result.diagnostics).toEqual([]);
    expect(emitIrModuleRust(result.module).contents).toContain(
      'let present: (f64, Option<String>) = (1.0, Some("flight".to_owned()));',
    );
    expect(emitIrModuleRust(result.module).contents).toContain('let value: (f64, Option<String>) = (2.0, None);');
  });

  it('clones fixed tuple spread fields through collision-free sequential evaluation carriers', () => {
    const result = lower(
      'tuple-spread.ts',
      `
        function marker(value: number): number { return value; }
        function optional(): [boolean?] { return []; }
        export function combine(tupleSpreadElement: number, tupleSpreadValue: [number, string]): [number, number, string, boolean?] {
          const output: [number, number, string, boolean?] = [marker(tupleSpreadElement), ...tupleSpreadValue, ...optional()];
          marker(tupleSpreadValue[0]);
          return output;
        }
      `,
    );
    const output = emitIrModuleRust(result.module).contents;

    expect(result.diagnostics).toEqual([]);
    expect(output).toContain(
      '({ let tuple_spread_element_2 = marker(tuple_spread_element); let tuple_spread_value_2 = &(tuple_spread_value); let tuple_spread_value_3 = &(optional()); (tuple_spread_element_2, tuple_spread_value_2.0.clone(), tuple_spread_value_2.1.clone(), tuple_spread_value_3.0.clone()) })',
    );
    expect(output).toContain('marker(tuple_spread_value.0);');
  });

  it('refuses tuple spread fields without clone-safe Rust ownership evidence', () => {
    const result = lower(
      'tuple-spread-object.ts',
      'type Item = { value: number }; export function copy(values: [Item]): [Item] { const copied: [Item] = [...values]; return copied; }',
    );

    expect(() => emitIrModuleRust(result.module)).toThrow(
      'fixed tuple spread source index 0 lacks clone-safe Rust ownership evidence',
    );
  });

  it('reports pass-named failures from the elected lowering plan', () => {
    const result = lower(
      'unsafe-loop.ts',
      'export function loop(): void { for (let index = 0; index < 1; index++) { try { continue; } finally { index; } } }',
    );

    expect(() => emitIrModuleRust(result.module)).toThrow(
      'Compiler lowering pass c-style-for failed for @flighthq/math/packages/math/src/unsafe-loop.ts: continue across a finally block requires completion-record lowering',
    );
  });

  it('emits numeric enums and rejects string enum representation', () => {
    const numeric = lower('mode.ts', 'export enum Mode { A = 1, B, C = Mode.A << 3, D }');
    const strings = lower('kind.ts', "export enum Kind { A = 'a', B = 'b' }");

    expect(emitIrModuleRust(numeric.module).contents).toContain('D = 9,');
    expect(() => emitIrModuleRust(strings.module)).toThrow('requires integer discriminants for Rust');
  });

  it('emits type-only imports and their references from one type-space identity', () => {
    const result = lower(
      'type-import.ts',
      "import type { sourceType as localType } from './types.js'; export type Alias = localType;",
    );
    const output = emitIrModuleRust(result.module).contents;

    expect(output).toContain('use crate::types::{SourceType as LocalType};');
    expect(output).toContain('pub type Alias = LocalType;');
  });

  it('keeps local bindings distinct from same-named module constants', () => {
    const result = lower(
      'guard.ts',
      'export const limit: number = 4; export function check(value: number): number { const limit: number = 9; if (value > limit) throw new Error("too big"); return limit; }',
    );
    const output = emitIrModuleRust(result.module).contents;

    expect(output).toContain('const LIMIT: f64 = 4.0;');
    expect(output).toContain('let limit: f64 = 9.0;');
    expect(output).toContain('(value > limit)');
    expect(output).toContain('Error::new("too big".to_owned())');
    expect(output).toContain('panic!("{:?}",');
    expect(output).not.toContain('panic!("{{:?}}"');
  });

  it('restores module bindings after nested local shadowing', () => {
    const result = lower(
      'scope.ts',
      'export const limit: number = 4; export function read(flag: boolean): number { if (flag) { const limit: number = 9; return limit; } return limit; }',
    );
    const output = emitIrModuleRust(result.module).contents;

    expect(output).toContain('return limit;');
    expect(output).toContain('return LIMIT;');
  });

  it('keeps parameters and nested closure parameters local when they shadow module constants', () => {
    const result = lower(
      'parameters.ts',
      'export const limit: number = 4; export function read(limit: number): number { return limit; } export function makeReader(): (limit: number) => number { return (limit: number): number => limit; }',
    );
    const output = emitIrModuleRust(result.module).contents;

    expect(output).toContain('pub fn read(limit: f64) -> f64 {\n  return limit;');
    expect(output).toContain('return |limit| limit;');
    expect(output.match(/return LIMIT;/gu)).toBeNull();
  });

  it('emits supported assignment, binary, and prefix operators from closed target mappings', () => {
    const result = lower(
      'operators.ts',
      'export function operators(left: number, right: number, disabled: boolean): boolean { let value: number = left; value += right; return value === right && !disabled; }',
    );
    const output = emitIrModuleRust(result.module).contents;

    expect(output).toContain('value += right;');
    expect(output).toContain('return ((value == right) && !disabled);');
  });

  it('refuses operators whose static domains require Rust type-directed lowering', () => {
    const strings = lower(
      'string-operators.ts',
      'export function join(left: string, right: string): string { return left + right; }',
    );
    const unknown = lower(
      'unknown-operators.ts',
      'export function both(left: any, right: boolean): boolean { return left && right; }',
    );
    const loose = lower(
      'loose-equality.ts',
      'export function equal(left: number, right: number): boolean { return left == right; }',
    );

    expect(() => emitIrModuleRust(strings.module)).toThrow(
      'operator + on string and string requires Rust type-directed lowering',
    );
    expect(() => emitIrModuleRust(unknown.module)).toThrow(
      'operator && on unknown and boolean requires Rust type-directed lowering',
    );
    expect(() => emitIrModuleRust(loose.module)).toThrow(
      'operator == on number and number requires Rust type-directed lowering',
    );
  });

  it('rejects module facades and emits normalized switch fallthrough', () => {
    const barrel = lower('barrel.ts', "export * from './other.js';");
    const fallthrough = lower(
      'switch.ts',
      'export function choose(a: number): number { switch (a) { case 1: case 2: return 2; default: return 0; } }',
    );
    const output = emitIrModuleRust(fallthrough.module).contents;

    expect(() => emitIrModuleRust(barrel.module)).toThrow('module-facade lowering');
    expect(output).toContain('let switch_value = a;');
    expect(output).toContain('if switch_value == 1.0 {\n      return 2.0;\n    }\n    else if switch_value == 2.0');
  });

  it.each([
    [
      'assignment',
      'export function power(a: number, b: number): number { a **= b; return a; }',
      'operator **= requires Rust semantic lowering',
    ],
    [
      'binary',
      'export function power(a: number, b: number): number { return a ** b; }',
      'operator ** requires Rust semantic lowering',
    ],
    [
      'keyword unary',
      'export function type(a: number): string { return typeof a; }',
      'typeof requires Rust semantic lowering',
    ],
    [
      'postfix unary',
      'export function increment(a: number): number { return a++; }',
      'postfix ++ requires value-preserving Rust lowering',
    ],
    [
      'prefix update unary',
      'export function increment(a: number): number { return ++a; }',
      'prefix ++ requires value-preserving Rust lowering',
    ],
    [
      'prefix unary',
      'export function positive(a: number): number { return +a; }',
      'operator + requires Rust semantic lowering',
    ],
  ])('refuses unsupported %s operators explicitly', (family, source, message) => {
    const result = lower(`${family.replaceAll(' ', '-')}-operator.ts`, source);

    expect(() => emitIrModuleRust(result.module)).toThrow(message);
  });

  it('rejects nullable parameters and undefined expressions without Option-aware lowering', () => {
    const nullable = lower(
      'nullable.ts',
      'export function nullable(value: number | null): number | null { return value; }',
    );
    const optional = lower('optional.ts', 'export function optional(value?: number): number { return 0; }');
    const undefinedNullable = lower(
      'undefined-nullable.ts',
      'export function undefinedNullable(value: number | undefined): number { return 0; }',
    );
    const nullableReturn = lower(
      'nullable-return.ts',
      'export function nullableReturn(): number | null { return null; }',
    );
    const undefinedValue = lower('missing.ts', 'export function missing(): undefined { return undefined; }');

    expect(() => emitIrModuleRust(nullable.module)).toThrow(
      'nullable parameter value requires Option-aware Rust control-flow lowering',
    );
    expect(() => emitIrModuleRust(optional.module)).toThrow(
      'nullable parameter value requires Option-aware Rust control-flow lowering',
    );
    expect(() => emitIrModuleRust(undefinedNullable.module)).toThrow(
      'nullable parameter value requires Option-aware Rust control-flow lowering',
    );
    expect(emitIrModuleRust(nullableReturn.module).contents).toContain(
      'pub fn nullable_return() -> Option<f64> {\n  return None;',
    );
    expect(() => emitIrModuleRust(undefinedValue.module)).toThrow(
      'undefined expressions require Rust Option-aware lowering',
    );
  });

  it('emits a local binding named undefined without confusing it with the ambient value', () => {
    const result = lower(
      'local-undefined.ts',
      'export function read(value: number): number { const undefined: number = value; return undefined; }',
    );
    const output = emitIrModuleRust(result.module).contents;

    expect(output).toContain('let undefined: f64 = value;');
    expect(output).toContain('return undefined;');
  });

  it('uses binding identity to keep renamed declarations and references aligned', () => {
    const result = lower('rename.ts', 'export function read(): number { return read(); }');
    const declaration = result.module.declarations[0];
    if (declaration?.kind !== 'function') throw new Error('Expected function declaration');
    const renamed = {
      ...result.module,
      declarations: [{ ...declaration, binding: { ...declaration.binding, name: 'renamed' } }],
    };
    const output = emitIrModuleRust(renamed).contents;

    expect(output).toContain('pub fn renamed() -> f64');
    expect(output).toContain('return renamed();');
  });

  it('allocates collision-free Rust names for shadowed and case-normalized bindings', () => {
    const result = lower(
      'collisions.ts',
      'export function choose(fooBar: number, foo_bar: number): number { { const fooBar: number = foo_bar; fooBar; } return fooBar + foo_bar; }',
    );
    const output = emitIrModuleRust(result.module).contents;

    expect(output).toContain('pub fn choose(foo_bar: f64, foo_bar_2: f64) -> f64');
    expect(output).toContain('let foo_bar_3: f64 = foo_bar_2;');
    expect(output).toContain('foo_bar_3;');
    expect(output).toContain('return (foo_bar + foo_bar_2);');
  });

  it('keeps a public target name fixed while renaming an internal collision', () => {
    const result = lower(
      'internal-collision.ts',
      'function fooBar(value: number): number { return value; } export function foo_bar(value: number): number { return fooBar(value); }',
    );
    const output = emitIrModuleRust(result.module).contents;

    expect(output).toContain('fn foo_bar_2(value: f64) -> f64');
    expect(output).toContain('pub fn foo_bar(value: f64) -> f64');
    expect(output).toContain('return foo_bar_2(value);');
  });

  it('refuses public value and type collisions introduced by Rust normalization', () => {
    const values = lower(
      'value-collisions.ts',
      'export function fooBar(value: number): number { return value; } export function foo_bar(value: number): number { return value + 1; }',
    );
    const result = lower('type-collisions.ts', 'export type fooBar = number; export type foo_bar = fooBar;');

    try {
      emitIrModuleRust(values.module);
      expect.unreachable('Expected public Rust target names to collide');
    } catch (error) {
      expect(isBackendEmissionFailure(error)).toBe(true);
      expect(error).toMatchObject({
        backend: 'rust',
        code: 'unsupported-ir',
        kind: 'backend-emission',
        message: expect.stringContaining('public declarations share fixed Rust target name foo_bar'),
      });
    }
    expect(() => emitIrModuleRust(result.module)).toThrow('public declarations share fixed Rust target name FooBar');
  });

  it('rejects class state and default parameters that would otherwise be dropped', () => {
    const staticField = lower('config.ts', 'export class Config { static limit: number = 3; value: number = 1; }');
    const defaultParameter = lower('default.ts', 'export function read(value: number = 1): number { return value; }');

    expect(() => emitIrModuleRust(staticField.module)).toThrow('static fields require associated-item lowering');
    expect(() => emitIrModuleRust(defaultParameter.module)).toThrow('default parameter value');
  });
});
