// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/blockScope.ts#BlockScope. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double scoped_accumulate(flight::Array<double> values) {
  double result = 0.0;
  for (auto value : values) {
    const double doubled = (value * 2.0);
    result = (result + doubled);
  }
  return result;
}

inline double nested_scope(double x) {
  double result = x;
  if ((x > 0.0)) {
    const double temp = (result * 2.0);
    result = (temp + 1.0);
  }
  else {
    const double temp_2 = (result * 3.0);
    result = (temp_2 - 1.0);
  }
  return result;
}

inline double multiple_bindings(double a, double b) {
  const double sum = (a + b);
  const double product = (a * b);
  const double diff = (a - b);
  return ((sum + product) + diff);
}

} // namespace flighthq_golden
