// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/importedAmbientAlias.ts#ImportedAmbientAlias. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;
import flighthq.golden.Provider.Failure;
import flighthq.golden.Provider.Holder;
import flighthq.golden.Provider.Pattern;

function read(holder:Holder):Pattern {
  return holder.pattern;
}

function pass(failure:Failure):Failure {
  return failure;
}

function describe(failure:Failure):String {
  return failure.message;
}
