// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/sentinelAssertionConversion.ts#SentinelAssertionConversion. Do not edit.
#pragma once
#include <optional>
#include <stdexcept>
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Point;

using Slot = std::variant<double, flight::String>;

struct Point : public flight::ReferenceEnabled {
  double x;
};

using PointSlot = std::variant<flight::Ref<Point>, double>;

inline Slot present(std::optional<std::variant<double, flight::String>> value) {
  return ([&]() -> std::variant<double, flight::String> { auto asserted_source = value; if (!asserted_source.has_value()) throw std::logic_error("asserted union alternative is not present in the value"); return asserted_source.value(); }());
}

inline std::optional<std::variant<double, flight::String>> widen(Slot value) {
  return static_cast<std::optional<std::variant<double, flight::String>>>(value);
}

inline PointSlot present_record(std::optional<std::variant<flight::Ref<Point>, double>> value) {
  return ([&]() -> std::variant<flight::Ref<Point>, double> { auto asserted_source_2 = value; if (!asserted_source_2.has_value()) throw std::logic_error("asserted union alternative is not present in the value"); return asserted_source_2.value(); }());
}

} // namespace flighthq_golden
