// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nominalInterface.ts#NominalInterface. Do not edit.
package flighthq.golden;

interface Advancer {
  public var step:Float;
  public function advance(by:Float):Float;
}

class Counter implements Advancer {
  public var step:Float = 1;

  public function advance(by:Float):Float {
    return (by + this.step);
  }
}
