// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/intersectionMergedShape.ts#IntersectionMergedShape. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct A;
struct B;

struct A : public flight::ReferenceEnabled {
  std::optional<double> a;
  flight::String shared;
};

struct B : public flight::ReferenceEnabled {
  flight::String b;
  flight::String shared;
};

using BAlias = flight::Ref<B>;

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_A_SHARED_B_32DB0074E08AD860
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_A_SHARED_B_32DB0074E08AD860
struct a_shared_b_32db0074e08ad860 : public flight::ReferenceEnabled {
  std::optional<double> a;
  flight::String shared;
  flight::String b;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_A_SHARED_B_32DB0074E08AD860

inline std::optional<double> read(flight::Ref<a_shared_b_32db0074e08ad860> value) {
  return value->a;
}

} // namespace flighthq_golden
