// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/classInheritance.ts#ClassInheritance. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Base : public flight::ReferenceEnabled {
  double value;
  Base(double value) {
    this->value = value;
  }
  virtual ~Base() = default;
  virtual double doubled() {
    return (this->value * 2.0);
  }
};

struct Child : public Base {
  flight::String label;
  Child(double value, flight::String label) : Base(value) {
    this->label = label;
  }
  flight::String describe() {
    return flight::String("") + flight::to_string(this->label) + flight::String(": ") + flight::to_string(this->doubled()) + flight::String("");
  }
};

inline flight::String create_child(double value, flight::String label) {
  flight::Ref<Child> child = flight::make_ref<Child>(value, label);
  return child->describe();
}

inline double base_doubled(double value) {
  flight::Ref<Base> base = flight::make_ref<Base>(value);
  return base->doubled();
}

} // namespace flighthq_golden
