// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/classInheritance.ts#ClassInheritance. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

struct Base {
  double value;
  Base(double value) {
    this->value = value;
  }
  virtual ~Base() = default;
  virtual double doubled() {
    return (this->value * 2.0);
  }
};

struct Child : public Base {
  std::string label;
  Child(double value, std::string label) : Base(value) {
    this->label = label;
  }
  std::string describe() {
    return std::string("") + std::to_string(this->label) + std::string(": ") + std::to_string(this->doubled()) + std::string("");
  }
};

std::string create_child(double value, std::string label) {
  const Child child = Child(value, label);
  return child.describe();
}

double base_doubled(double value) {
  const Base base = Base(value);
  return base.doubled();
}

} // namespace flighthq_golden
