// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/splitJoin.ts#SplitJoin. Do not edit.
package flighthq.golden;

function csvToList(csv:String):Array<String> {
  return flighthq._internal._StringTools.split(csv, ",");
}

function listToCsv(items:Array<String>):String {
  return items.join(",");
}

function wordCount(text:String):Float {
  final words:Array<String> = flighthq._internal._StringTools.split(text, " ");
  return words.length;
}

function reverseWords(text:String):String {
  final words:Array<String> = flighthq._internal._StringTools.split(text, " ");
  words.reverse();
  return words.join(" ");
}
