// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/destructureParam.ts#DestructureParam. Do not edit.
package flighthq.golden;

typedef Rectangle = { height:Float, width:Float };

function area(parameterPatternValue:Rectangle):Float {
  var width:Float;
  var height:Float;
  final objectPatternValue:Rectangle = parameterPatternValue;
  width = objectPatternValue.width;
  height = objectPatternValue.height;
  return width * height;
}

function perimeter(parameterPatternValue:Rectangle):Float {
  var width:Float;
  var height:Float;
  final objectPatternValue:Rectangle = parameterPatternValue;
  width = objectPatternValue.width;
  height = objectPatternValue.height;
  return 2 * (width + height);
}

function diagonal(parameterPatternValue:Rectangle):Float {
  var width:Float;
  var height:Float;
  final objectPatternValue:Rectangle = parameterPatternValue;
  width = objectPatternValue.width;
  height = objectPatternValue.height;
  return Math.sqrt(((width * width) + (height * height)));
}

function isSquare(parameterPatternValue:Rectangle):Bool {
  var width:Float;
  var height:Float;
  final objectPatternValue:Rectangle = parameterPatternValue;
  width = objectPatternValue.width;
  height = objectPatternValue.height;
  return width == height;
}
