// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayQueue.ts#ArrayQueue. Do not edit.
#![forbid(unsafe_code)]

pub fn dequeue(items: &mut Vec<f64>) -> f64 {
  return items.remove(0);
}

pub fn enqueue(items: &mut Vec<f64>, value: f64) -> () {
  items.push(value);
}

pub fn prepend(items: &mut Vec<String>, value: String) -> () {
  items.insert(0, value);
}

pub fn rotate_first(items: &mut Vec<f64>) -> () {
  let first: f64 = items.remove(0);
  items.push(first);
}
