// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/contextualUnionViewInequivalent.ts#ContextualUnionViewInequivalent. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone)]
pub enum AnonymousUnion {
  Readonly(Color),
  Readonly2(Texture),
}

#[derive(Clone)]
pub enum AnonymousUnion2 {
  Color(Color),
  Texture(Texture),
}

#[derive(Clone, Debug)]
pub struct Color {
  pub r: f64,
  pub g: f64,
}

#[derive(Clone, Debug)]
pub struct Texture {
  pub id: String,
}

pub fn pick(value: AnonymousUnion) -> AnonymousUnion2 {
  return value;
}
