// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/collectionText.ts#CollectionText. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double sum(flight::Array<double> values) {
  double total = 0.0;
  for (auto value : values) {
    total += value;
  }
  return total;
}

inline flight::String comma_joined(flight::Array<flight::String> values) {
  return values.join(flight::String(", "));
}

inline flight::String custom_joined(flight::Array<flight::String> values, flight::String separator) {
  return values.join(separator);
}

} // namespace flighthq_golden
