// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/classMethod.ts#ClassMethod. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Rectangle {
  double width;
  double height;
  Rectangle(double width, double height) {
    this->width = width;
    this->height = height;
  }
  double area() {
    return (this->width * this->height);
  }
  double perimeter() {
    return (2.0 * (this->width + this->height));
  }
  bool is_square() {
    return (this->width == this->height);
  }
  Rectangle scale(double factor) {
    return Rectangle((this->width * factor), (this->height * factor));
  }
};

inline double total_area(flight::Array<Rectangle> rects) {
  double sum = 0.0;
  for (auto rect : rects) {
    sum = (sum + rect.area());
  }
  return sum;
}

} // namespace flighthq_golden
