// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/doWhileAccumulator.ts#DoWhileAccumulator. Do not edit.
#![forbid(unsafe_code)]

pub fn sum_one_to_n(n: f64) -> f64 {
  let mut sum: f64 = 0.0;
  let mut i: f64 = 1.0;
  loop {
    sum += i;
    i += 1.0;
    if !((i <= n)) { break; }
  }
  return sum;
}

pub fn repeat_halve(value: f64) -> f64 {
  let mut result: f64 = value;
  let mut count: f64 = 0.0;
  loop {
    result = f64::floor((result / 2.0));
    count += 1.0;
    if !((result > 0.0)) { break; }
  }
  return count;
}

pub fn reverse_digits(value: f64) -> f64 {
  let mut n: f64 = f64::abs(value);
  let mut reversed: f64 = 0.0;
  loop {
    reversed = (reversed * 10.0) + (n % 10.0);
    n = f64::floor((n / 10.0));
    if !((n > 0.0)) { break; }
  }
  return if (value < 0.0) { -reversed } else { reversed };
}
