// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/contextualUnionViewConversion.ts#ContextualUnionViewConversion. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Color = { r:Float, g:Float };

typedef Texture = { id:String };

function pick(value:Dynamic):Dynamic {
  return value;
}
