// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/accumulator.ts#Accumulator. Do not edit.
#pragma once
#include <vector>

namespace flighthq_golden {

double sum_until(std::vector<double> values, double limit) {
  double total = 0.0;
  for (double value : values) {
    if (((total + value) > limit)) {
      break;
    }
    total = (total + value);
  }
  return total;
}

double count_positive(std::vector<double> values) {
  double count = 0.0;
  for (double value : values) {
    if ((value > 0.0)) {
      count = (count + 1.0);
    }
  }
  return count;
}

double find_first_negative(std::vector<double> values) {
  for (double value : values) {
    if ((value < 0.0)) {
      return value;
    }
  }
  return 0.0;
}

} // namespace flighthq_golden
