// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/accumulator.ts#Accumulator. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double sum_until(flight::Array<double> values, double limit) {
  double total = 0.0;
  for (auto value : values) {
    if (((total + value) > limit)) {
      break;
    }
    total = (total + value);
  }
  return total;
}

inline double count_positive(flight::Array<double> values) {
  double count = 0.0;
  for (auto value : values) {
    if ((value > 0.0)) {
      count = (count + 1.0);
    }
  }
  return count;
}

inline double find_first_negative(flight::Array<double> values) {
  for (auto value : values) {
    if ((value < 0.0)) {
      return value;
    }
  }
  return 0.0;
}

} // namespace flighthq_golden
