// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/finallyAwait.ts#FinallyAwait. Do not edit.
package flighthq.golden;

class FinallyAwait {
  public static function attempt(task:flighthq._internal._Promise<Float>):flighthq._internal._Promise<Float> {
    return new flighthq._internal._Promise(function(resolveTask, rejectTask) {
      try {
        var result:Float = 0;
        var done:Bool = false;
        var taskJoin = function() {
          try {
            resolveTask((done ? result : result));
            return;
          } catch (taskError_3:Dynamic) {
            rejectTask(taskError_3);
          }
        };
        var taskCleanup = function() {
          try {
            done = true;
            taskJoin();
            return;
          } catch (taskError_2:Dynamic) {
            rejectTask(taskError_2);
          }
        };
        try {
          flighthq._internal._Promise.resolve(task).then(
            function(awaitValue) {
              result = awaitValue;
              try {
                taskCleanup();
                return;
              } catch (taskError_5:Dynamic) {
                try {
                  done = true;
                } catch (taskError_6:Dynamic) {
                  rejectTask(taskError_6);
                }
                rejectTask(taskError_5);
              }
            },
            function(awaitError) {
              try {
                done = true;
              } catch (taskError_7:Dynamic) {
                rejectTask(taskError_7);
              }
            }
          );
          return;
        } catch (taskError_4:Dynamic) {
          try {
            done = true;
          } catch (taskError_8:Dynamic) {
            rejectTask(taskError_8);
          }
          rejectTask(taskError_4);
        }
        return;
      } catch (taskError:Dynamic) {
        rejectTask(taskError);
      }
    });
  }
}
