// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/cascadingIf.ts#CascadingIf. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

std::string day_type(double day) {
  if (((day == 0.0) || (day == 6.0))) {
    return "weekend";
  }
  else {
    if (((day >= 1.0) && (day <= 5.0))) {
      return "weekday";
    }
    else {
      return "invalid";
    }
  }
}

std::string range(double value) {
  if ((value < 0.0)) {
    return "negative";
  }
  else {
    if ((value == 0.0)) {
      return "zero";
    }
    else {
      if ((value < 10.0)) {
        return "small";
      }
      else {
        if ((value < 100.0)) {
          return "medium";
        }
        else {
          return "large";
        }
      }
    }
  }
}

std::string season(double month) {
  if (((month >= 3.0) && (month <= 5.0))) {
    return "spring";
  }
  else {
    if (((month >= 6.0) && (month <= 8.0))) {
      return "summer";
    }
    else {
      if (((month >= 9.0) && (month <= 11.0))) {
        return "autumn";
      }
      else {
        return "winter";
      }
    }
  }
}

} // namespace flighthq_golden
