// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/closureReturn.ts#ClosureReturn. Do not edit.
package flighthq.golden;

function makeAdder(base:Float):(Float)->Float {
  return function(x:Float) return (base + x);
}

function applyToEach(values:Array<Float>, transform:(Float)->Float):Array<Float> {
  return values.map(transform);
}

function compose(f:(Float)->Float, g:(Float)->Float):(Float)->Float {
  return function(x:Float) return f(g(x));
}
