// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/conditionalChain.ts#ConditionalChain. Do not edit.
package flighthq.golden;

function classify(value:Float):String {
  if (value < 0) {
    return "negative";
  }
  else {
    if (value == 0) {
      return "zero";
    }
    else {
      if (value < 10) {
        return "small";
      }
      else {
        if (value < 100) {
          return "medium";
        }
        else {
          return "large";
        }
      }
    }
  }
}

function clampedLabel(value:Float):String {
  final clamped:Float = (value < 0) ? 0 : ((value > 100) ? 100 : value);
  return (clamped == 0) ? "min" : ((clamped == 100) ? "max" : "mid");
}

function absoluteDifference(a:Float, b:Float):Float {
  return (a > b) ? (a - b) : (b - a);
}
