// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unionNarrowing.ts#UnionNarrowing. Do not edit.
package flighthq.golden;

function narrow_typeof(value:Dynamic):String {
  if (Std.isOfType(value, String)) {
    return value;
  }
  return Std.string(value);
}

function narrow_typeof_number(value:Dynamic):Float {
  if (Std.isOfType(value, Float)) {
    return value;
  }
  return 0;
}

function narrow_branch(value:Dynamic, flag:Bool):String {
  if (flag && Std.isOfType(value, String)) {
    return value;
  }
  return "default";
}

function assert_string(value:Dynamic):String {
  return cast(value, String);
}

function assert_number(value:Dynamic):Float {
  return cast(value, Float);
}
