// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mapLookup.ts#MapLookup. Do not edit.
#![forbid(unsafe_code)]

pub fn lookup(entries: std::collections::HashMap<String, f64>, key: String) -> f64 {
  let value: Option<f64> = entries.get(&key).cloned();
  if value.is_some() {
    return value.clone().unwrap();
  }
  return -1.0;
}

pub fn get_or_default(entries: std::collections::HashMap<String, String>, key: String, fallback: String) -> String {
  let value: Option<String> = entries.get(&key).cloned();
  if value.is_some() {
    return value.clone().unwrap();
  }
  return fallback;
}
