// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/predicateFilter.ts#PredicateFilter. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function filterAbove(values:Array<Float>, threshold:Float):Array<Float> {
  return values.filter(cast(function(v:Float) return (v > threshold)));
}

function findFirst(values:Array<Float>, threshold:Float):Float {
  final found:Null<Float> = Lambda.find(values, cast(function(v:Float) return (v > threshold)));
  if (js.Syntax.strictEq(found, js.Syntax.code("undefined"))) {
    return - 1;
  }
  return found;
}

function allBelow(values:Array<Float>, limit:Float):Bool {
  return Lambda.foreach(values, cast(function(v:Float) return (v < limit)));
}

function anyNegative(values:Array<Float>):Bool {
  return Lambda.exists(values, cast(function(v:Float) return (v < 0)));
}
