// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/multiCondition.ts#MultiCondition. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

std::string fizzbuzz(double n) {
  if (((n - (15.0 * std::floor((n / 15.0)))) == 0.0)) {
    return "FizzBuzz";
  }
  if (((n - (3.0 * std::floor((n / 3.0)))) == 0.0)) {
    return "Fizz";
  }
  if (((n - (5.0 * std::floor((n / 5.0)))) == 0.0)) {
    return "Buzz";
  }
  return n.to_string();
}

std::string letter_grade(double score) {
  if ((score >= 90.0)) {
    return "A";
  }
  if ((score >= 80.0)) {
    return "B";
  }
  if ((score >= 70.0)) {
    return "C";
  }
  if ((score >= 60.0)) {
    return "D";
  }
  return "F";
}

double median(double a, double b, double c) {
  if (((a <= b) && (b <= c))) {
    return b;
  }
  if (((c <= b) && (b <= a))) {
    return b;
  }
  if (((b <= a) && (a <= c))) {
    return a;
  }
  if (((c <= a) && (a <= b))) {
    return a;
  }
  return c;
}

} // namespace flighthq_golden
