// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/forOfLoop.ts#ForOfLoop. Do not edit.
#pragma once
#include <string>
#include <vector>

namespace flighthq_golden {

double sum(std::vector<double> values) {
  double total = 0.0;
  for (double value : values) {
    total = (total + value);
  }
  return total;
}

std::string collect(std::vector<std::string> items) {
  std::string result = "";
  for (std::string item : items) {
    result = result + item;
  }
  return result;
}

} // namespace flighthq_golden
