// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/classAccessor.ts#ClassAccessor. Do not edit.
package flighthq.golden;

class Counter {
  private var count:Float;

  public static final zero:Float = 0;

  public function new(count:Float) {
    this.count = count;
  }

  public var value(get, set):Float;

  function get_value():Float {
    return this.count;
  }

  function set_value(next:Float):Float {
    this.count = next;
    return next;
  }

  public static function make():Counter {
    return new Counter(0);
  }
}

class ClassAccessor {
  public static function readBack(counter:Counter):Float {
    return counter.value;
  }
}
