// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/staticForIn.ts#StaticForIn. Do not edit.
#![forbid(unsafe_code)]

pub fn select_first_key() -> String {
  for key in ["2".to_owned(), "10".to_owned(), "second".to_owned(), "first".to_owned()] {
    return key;
  }
  return "".to_owned();
}
