// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericCast.ts#NumericCast. Do not edit.
#pragma once

namespace flighthq_golden {

double round_down(double value) {
  return std::floor(value);
}

double round_up(double value) {
  return std::ceil(value);
}

double rounded(double value) {
  return std::round(value);
}

double absolute(double value) {
  return std::abs(value);
}

double integer_part(double value) {
  return ((value >= 0.0) ? std::floor(value) : std::ceil(value));
}

} // namespace flighthq_golden
