// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericCast.ts#NumericCast. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double round_down(double value) {
  return std::floor(value);
}

inline double round_up(double value) {
  return std::ceil(value);
}

inline double rounded(double value) {
  return std::round(value);
}

inline double absolute(double value) {
  return std::abs(value);
}

inline double integer_part(double value) {
  return ((value >= 0.0) ? std::floor(value) : std::ceil(value));
}

} // namespace flighthq_golden
