// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/spreadCall.ts#SpreadCall. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double widest(flight::Array<double> values) {
  return flight::maximum(values);
}

} // namespace flighthq_golden
