// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/bindingProvenance.ts#BindingProvenance. Do not edit.
package flighthq.golden;

class BindingProvenance {
  public static final fallback:Float = 4;

  public static function resolve(fallback:Float):Float {
    final undefined:Float = fallback;
    return undefined;
  }
}
