// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/bindingProvenance.ts#BindingProvenance. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

final fallback:Float = 4;

function resolve(fallback:Float):Float {
  final undefined:Float = fallback;
  return undefined;
}
