// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/contextualOptionalEvidence.ts#ContextualOptionalEvidence. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function pattern():Null<flighthq._internal._RegExp> {
  return (cast new flighthq._internal._RegExp("\\d+", "gu") : flighthq._internal._RegExp);
}

function patternIf(flag:Bool):Null<flighthq._internal._RegExp> {
  return (cast (flag ? new flighthq._internal._RegExp("a", "") : js.Syntax.code("undefined")) : flighthq._internal._RegExp);
}

function size(value:Dynamic):Null<Float> {
  return HaxeReflect.field(value, "size");
}

function label(value:Dynamic):Null<String> {
  return HaxeReflect.field(value, "label");
}
