// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/whileSearch.ts#WhileSearch. Do not edit.
package flighthq.golden;

function firstAbove(values:Array<Float>, threshold:Float):Float {
  var i:Float = 0;
  while (i < values.length) {
    if (values[Std.int(i)] > threshold) {
      return values[Std.int(i)];
    }
    i += 1;
  }
  return - 1;
}

function countOccurrences(text:String, target:String):Float {
  var count:Float = 0;
  var pos:Float = 0;
  while (pos < text.length) {
    if (text.charAt(Std.int(pos)) == target) {
      count += 1;
    }
    pos += 1;
  }
  return count;
}

function indexOfFirst(values:Array<Float>, target:Float):Float {
  var i:Float = 0;
  while (i < values.length) {
    if (values[Std.int(i)] == target) {
      return i;
    }
    i += 1;
  }
  return - 1;
}
