// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mathMinMax.ts#MathMinMax. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double minimum(double a, double b) {
  return flight::minimum(a, b);
}

inline double maximum(double a, double b) {
  return flight::maximum(a, b);
}

inline double clamp(double value, double low, double high) {
  return flight::maximum(low, flight::minimum(value, high));
}

inline double abs_distance(double a, double b) {
  return std::abs((a - b));
}

} // namespace flighthq_golden
