// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericCast.ts#NumericCast. Do not edit.
#![forbid(unsafe_code)]

pub fn round_down(value: f64) -> f64 {
  return f64::floor(value);
}

pub fn round_up(value: f64) -> f64 {
  return f64::ceil(value);
}

pub fn rounded(value: f64) -> f64 {
  return f64::round(value);
}

pub fn absolute(value: f64) -> f64 {
  return f64::abs(value);
}

pub fn integer_part(value: f64) -> f64 {
  return if (value >= 0.0) { f64::floor(value) } else { f64::ceil(value) };
}
