// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericCast.ts#NumericCast. Do not edit.
#![forbid(unsafe_code)]

pub fn truncate(value: f64) -> f64 {
  return f64::trunc(value);
}

pub fn round_down(value: f64) -> f64 {
  return f64::floor(value);
}

pub fn round_up(value: f64) -> f64 {
  return f64::ceil(value);
}

pub fn integer_divide(a: f64, b: f64) -> f64 {
  return f64::trunc((a / b));
}

pub fn remainder(a: f64, b: f64) -> f64 {
  return a - (f64::trunc((a / b)) * b);
}
