// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/variableForInHoisting.ts#VariableForInHoisting. Do not edit.
#pragma once
#include <string>
#include <vector>

namespace flighthq_golden {

struct values {
  double value;
};

std::string select_first_key(values values) {
  auto key;
  for (const std::string& variable_hoisting_iteration_value : std::vector<std::string>{"value"}) {
    {
      key = variable_hoisting_iteration_value;
      return key;
    }
  }
  return "";
}

} // namespace flighthq_golden
