// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/variableForInHoisting.ts#VariableForInHoisting. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Values {
  double value;
};

inline flight::String select_first_key(Values values) {
  flight::String key;
  static_cast<void>(values);
  for (const flight::String& variable_hoisting_iteration_value : flight::Array<flight::String>{flight::String("value")}) {
    {
      key = variable_hoisting_iteration_value;
      return key;
    }
  }
  return flight::String("");
}

} // namespace flighthq_golden
