// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/dualSentinelUnion.ts#DualSentinelUnion. Do not edit.
#pragma once
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::String resolve(std::variant<flight::String, flight::Null, flight::Undefined> value) {
  if (std::holds_alternative<flight::Null>(value)) {
    return flight::String("null");
  }
  if (std::holds_alternative<flight::Undefined>(value)) {
    return flight::String("undefined");
  }
  return std::get<flight::String>(value);
}

inline double coerce(std::variant<double, flight::Null, flight::Undefined> value, double fallback) {
  if ((std::holds_alternative<flight::Null>(value) || std::holds_alternative<flight::Undefined>(value))) {
    return fallback;
  }
  return std::get<double>(value);
}

inline std::variant<flight::String, flight::Null, flight::Undefined> assign_dual(double flag) {
  if ((flag == 0.0)) {
    return std::variant<flight::String, flight::Null, flight::Undefined>{std::in_place_type<flight::Null>, flight::null};
  }
  if ((flag == 1.0)) {
    return std::variant<flight::String, flight::Null, flight::Undefined>{std::in_place_type<flight::Undefined>, flight::undefined};
  }
  return std::variant<flight::String, flight::Null, flight::Undefined>{std::in_place_type<flight::String>, flight::String("present")};
}

} // namespace flighthq_golden
