// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/collectionFold.ts#CollectionFold. Do not edit.
package flighthq.golden;

function total(values:Array<Float>):Float {
  return Lambda.fold(values, function(value:Float, accumulated:Float) return (accumulated + value), 0);
}
