// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/splitJoin.ts#SplitJoin. Do not edit.
#![forbid(unsafe_code)]

pub fn csv_to_list(csv: String) -> Vec<String> {
  return csv.split(",").map(|s| s.to_string()).collect::<Vec<String>>();
}

pub fn list_to_csv(items: Vec<String>) -> String {
  return items.join(",");
}

pub fn word_count(text: String) -> f64 {
  let words: Vec<String> = text.split(" ").map(|s| s.to_string()).collect::<Vec<String>>();
  return words.len() as f64;
}

pub fn reverse_words(text: String) -> String {
  let mut words: Vec<String> = text.split(" ").map(|s| s.to_string()).collect::<Vec<String>>();
  words.reverse();
  return words.join(" ");
}
