// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/negativeArithmetic.ts#NegativeArithmetic. Do not edit.
#![forbid(unsafe_code)]

pub fn negate(value: f64) -> f64 {
  return -value;
}

pub fn double_negate(value: f64) -> f64 {
  return --value;
}

pub fn subtract_from_zero(value: f64) -> f64 {
  return 0.0 - value;
}

pub fn negative_product(a: f64, b: f64) -> f64 {
  return -(a * b);
}

pub fn absolute_difference(a: f64, b: f64) -> f64 {
  let diff: f64 = a - b;
  return if (diff < 0.0) { -diff } else { diff };
}
