import path from 'node:path';

import { createBackendEmissionError, indentSource } from '../../compiler-emission/src/index.js';
import type { CompilerBackend, EmittedFile, HaxeBackendOptions } from '../../compiler-types/src/index.js';
import type {
  IrClassDeclaration,
  IrDeclaration,
  IrEnumDeclaration,
  IrExpression,
  IrFunctionDeclaration,
  IrImport,
  IrInterfaceDeclaration,
  IrModule,
  IrObjectTypeMember,
  IrParameter,
  IrStatement,
  IrType,
  IrTypeDeclaration,
  IrTypeParameter,
  IrVariable,
  IrVariableDeclaration,
} from '../../compiler-types/src/index.js';

interface EmitContext {
  module: Readonly<IrModule>;
  options: Readonly<HaxeBackendOptions>;
  packageName: string;
}

export const haxeBackend: CompilerBackend<HaxeBackendOptions> = {
  emitModule(module, { options }) {
    return [emitHaxeModule(module, options)];
  },
  name: 'haxe',
};

export function emitHaxeModule(module: Readonly<IrModule>, options: Readonly<HaxeBackendOptions> = {}): EmittedFile {
  const packageName = packageNameToHaxePackage(module.packageName, options.rootPackage);
  const context: EmitContext = { module, options, packageName };
  if (module.exports.length > 0) {
    emissionError(context, 're-exports and export assignments require Haxe module-facade lowering');
  }
  const moduleName = haxeImplementationModule(module.source);
  const typeDeclarations = module.declarations.filter(
    (declaration) =>
      declaration.kind === 'class' ||
      declaration.kind === 'enum' ||
      declaration.kind === 'interface' ||
      declaration.kind === 'type',
  );
  const valueDeclarations = module.declarations.filter(
    (declaration): declaration is IrFunctionDeclaration | IrVariableDeclaration =>
      declaration.kind === 'function' || declaration.kind === 'variable',
  );
  const lines = [
    options.generatedHeader ?? '// Generated by @flighthq/tool-compiler. Do not edit.',
    `package ${packageName};`,
  ];
  const imports = emitImports(module.imports, context);
  if (imports.length > 0) lines.push('', ...imports);
  for (const declaration of typeDeclarations) lines.push('', ...emitTypeDeclaration(declaration, context));
  if (valueDeclarations.length > 0) {
    lines.push('', `class ${moduleName} {`);
    valueDeclarations.forEach((declaration, index) => {
      if (index > 0) lines.push('');
      lines.push(...indentSource(emitModuleValue(declaration, context)));
    });
    lines.push('}');
  }
  return {
    contents: lines.join('\n'),
    path: `${packageName.replaceAll('.', '/')}/${moduleName}.hx`,
  };
}

export function packageNameToHaxePackage(packageName: string, rootPackage = 'flighthq'): string {
  const bareName = packageName.replace(/^@[^/]+\//u, '');
  const parts = bareName.split(/[-_]/u).filter(Boolean);
  if (parts.length === 0) throw new Error(`Cannot map empty npm package name: ${packageName}`);
  const segment = parts
    .map((part, index) =>
      index === 0 ? part.toLowerCase() : `${part.slice(0, 1).toUpperCase()}${part.slice(1).toLowerCase()}`,
    )
    .join('');
  return `${rootPackage}.${segment}`;
}

export function sourcePathToHaxeModule(sourcePath: string): string | undefined {
  const filename = path.basename(sourcePath).replace(/\.tsx?$/u, '');
  if (
    filename.toLowerCase() === 'index' ||
    filename.toLowerCase() === 'internal' ||
    /test(?:helper|util)/iu.test(filename)
  ) {
    return undefined;
  }
  return pascalCase(filename);
}

function emitClass(declaration: Readonly<IrClassDeclaration>, context: EmitContext): string[] {
  if (declaration.implements.length > 0) {
    emissionError(context, `class ${declaration.name} implements interfaces that require nominal Haxe lowering`);
  }
  const parameters = emitTypeParameters(declaration.typeParameters, context);
  const extendsType = declaration.extends ? ` extends ${emitType(declaration.extends, context)}` : '';
  const abstract = declaration.abstract ? 'abstract ' : '';
  const lines = [
    `${declaration.exported ? '' : 'private '}${abstract}class ${safeHaxeName(declaration.name)}${parameters}${extendsType} {`,
  ];
  declaration.fields.forEach((field, index) => {
    if (index > 0) lines.push('');
    const visibility = field.visibility === 'public' ? 'public ' : field.visibility === 'private' ? 'private ' : '';
    const storage = field.readonly ? 'final' : 'var';
    const static_ = field.static ? 'static ' : '';
    const initializer = field.initializer ? ` = ${emitExpression(field.initializer, context)}` : '';
    lines.push(
      `  ${visibility}${static_}${storage} ${safeHaxeName(field.name)}:${emitType(field.type, context)}${initializer};`,
    );
  });
  if (declaration.constructorParameters.length > 0 || declaration.constructorBody.length > 0) {
    if (declaration.fields.length > 0) lines.push('');
    lines.push(`  public function new(${emitParameters(declaration.constructorParameters, context)}) {`);
    lines.push(...indentSource(emitStatements(declaration.constructorBody, context), 2), '  }');
  }
  declaration.methods.forEach((method) => {
    if (lines.length > 1) lines.push('');
    if (method.async) emissionError(context, `async method ${method.name} requires the Haxe async-lowering pass`);
    const visibility = method.visibility === 'public' ? 'public ' : method.visibility === 'private' ? 'private ' : '';
    const static_ = method.static ? 'static ' : '';
    lines.push(
      `  ${visibility}${static_}function ${safeHaxeName(method.name)}${emitTypeParameters(method.typeParameters, context)}(${emitParameters(method.parameters, context)}):${emitType(method.returns, context)} {`,
      ...indentSource(emitStatements(method.body, context), 2),
      '  }',
    );
  });
  lines.push('}');
  return lines;
}

function emitEnum(declaration: Readonly<IrEnumDeclaration>, context: EmitContext): string[] {
  const kinds = new Set(declaration.members.map((member) => typeof member.value));
  if (kinds.size > 1) emissionError(context, `enum ${declaration.name} mixes string and numeric values`);
  if (declaration.members.some((member) => typeof member.value === 'number' && !Number.isFinite(member.value))) {
    emissionError(context, `enum ${declaration.name} has a non-finite numeric value`);
  }
  const underlying = kinds.has('string')
    ? 'String'
    : declaration.members.some((member) => !Number.isInteger(member.value))
      ? 'Float'
      : 'Int';
  const lines = [
    `enum abstract ${safeHaxeName(declaration.name)}(${underlying}) from ${underlying} to ${underlying} {`,
  ];
  declaration.members.forEach((member) => {
    const value = typeof member.value === 'string' ? JSON.stringify(member.value) : String(member.value);
    lines.push(`  var ${safeHaxeName(member.name)} = ${value};`);
  });
  lines.push('}');
  return lines;
}

function emitExpression(expression: Readonly<IrExpression>, context: EmitContext): string {
  switch (expression.kind) {
    case 'array':
      return `[${expression.elements.map((element) => (element ? emitExpression(element, context) : 'null')).join(', ')}]`;
    case 'assignment':
      return `${emitExpression(expression.left, context)} ${mapOperator(expression.operator, true, context)} ${emitExpression(expression.right, context)}`;
    case 'await':
      emissionError(context, 'await requires the Haxe async-lowering pass');
    case 'binary':
      return `(${emitExpression(expression.left, context)} ${mapOperator(expression.operator, false, context)} ${emitExpression(expression.right, context)})`;
    case 'call':
      if (expression.optional) emissionError(context, 'optional calls require null-safe call lowering');
      return `${emitExpression(expression.callee, context)}(${expression.arguments.map((argument) => emitExpression(argument, context)).join(', ')})`;
    case 'cast':
      return `(cast ${emitExpression(expression.expression, context)} : ${emitType(expression.type, context)})`;
    case 'conditional':
      return `(${emitExpression(expression.condition, context)} ? ${emitExpression(expression.whenTrue, context)} : ${emitExpression(expression.whenFalse, context)})`;
    case 'element':
      if (expression.optional) emissionError(context, 'optional element access requires null-safe access lowering');
      return `${emitExpression(expression.object, context)}[${emitExpression(expression.index, context)}]`;
    case 'function':
      if (expression.async) emissionError(context, 'async closures require the Haxe async-lowering pass');
      if (expression.typeParameters.length > 0)
        emissionError(context, 'generic function expressions are not valid Haxe values');
      return expression.expression
        ? `function(${emitParameters(expression.parameters, context)}) return ${emitExpression(expression.expression, context)}`
        : `function(${emitParameters(expression.parameters, context)}) {\n${indentSource(emitStatements(expression.body, context)).join('\n')}\n}`;
    case 'identifier':
      return safeHaxeName(expression.name);
    case 'literal':
      return emitLiteral(expression.value);
    case 'new':
      return `new ${emitExpression(expression.callee, context)}(${expression.arguments.map((argument) => emitExpression(argument, context)).join(', ')})`;
    case 'object':
      return `{ ${expression.members
        .map((member) => {
          if (member.kind === 'spread') emissionError(context, 'object spread requires structural-copy lowering');
          if (member.kind === 'computedProperty')
            emissionError(context, 'computed object properties require runtime lowering');
          return `${safeHaxeName(member.name)}: ${emitExpression(member.value, context)}`;
        })
        .join(', ')} }`;
    case 'property':
      if (expression.optional) emissionError(context, 'optional property access requires null-safe access lowering');
      return `${emitExpression(expression.object, context)}.${safeHaxeName(expression.name)}`;
    case 'regexp':
      return `~/${expression.pattern}/${expression.flags}`;
    case 'spread':
      emissionError(context, 'spread expressions require call or collection lowering');
    case 'template':
      return expression.parts
        .map((part) => (typeof part === 'string' ? emitLiteral(part) : `Std.string(${emitExpression(part, context)})`))
        .join(' + ');
    case 'unary': {
      const operand = emitExpression(expression.operand, context);
      if (!haxeUnaryOperators.has(expression.operator)) {
        emissionError(context, `operator ${expression.operator} requires Haxe semantic lowering`);
      }
      return expression.postfix ? `${operand}${expression.operator}` : `${expression.operator} ${operand}`;
    }
  }
}

function emitFunction(declaration: Readonly<IrFunctionDeclaration>, context: EmitContext): string[] {
  if (declaration.async)
    emissionError(context, `async function ${declaration.name} requires the Haxe async-lowering pass`);
  const access = declaration.exported ? 'public ' : 'private ';
  return [
    `${access}static function ${safeHaxeName(declaration.name)}${emitTypeParameters(declaration.typeParameters, context)}(${emitParameters(declaration.parameters, context)}):${emitType(declaration.returns, context)} {`,
    ...indentSource(emitStatements(declaration.body, context)),
    '}',
  ];
}

function emitImports(imports: readonly IrImport[], context: EmitContext): string[] {
  const emitted = new Set<string>();
  for (const imported of imports) {
    if (imported.bindings.length === 0) continue;
    const modulePath = haxeImportModule(imported.specifier, context);
    for (const binding of imported.bindings) {
      if (binding.imported === '*' || binding.imported === 'default') {
        emissionError(context, `${binding.imported} imports require explicit Haxe mapping for ${imported.specifier}`);
      }
      emitted.add(
        `import ${modulePath}.${safeHaxeName(binding.imported)}${binding.imported === binding.local ? '' : ` as ${safeHaxeName(binding.local)}`};`,
      );
    }
  }
  return [...emitted].sort();
}

function emitInterface(declaration: Readonly<IrInterfaceDeclaration>, context: EmitContext): string[] {
  if (declaration.extends.length > 0)
    emissionError(context, `interface ${declaration.name} inheritance requires structural flattening`);
  return [
    `typedef ${safeHaxeName(declaration.name)}${emitTypeParameters(declaration.typeParameters, context)} = ${emitAnonymousType(declaration.members, context)};`,
  ];
}

function emitLiteral(value: boolean | null | number | string): string {
  if (typeof value === 'string') return JSON.stringify(value);
  if (value === null) return 'null';
  return String(value);
}

function emitModuleValue(
  declaration: Readonly<IrFunctionDeclaration | IrVariableDeclaration>,
  context: EmitContext,
): string[] {
  return declaration.kind === 'function'
    ? emitFunction(declaration, context)
    : emitVariableDeclaration(declaration, context);
}

function emitParameters(parameters: readonly IrParameter[], context: EmitContext): string {
  return parameters
    .map((parameter) => {
      const name = safeHaxeName(parameter.name);
      const type = emitType(parameter.type, context);
      if (parameter.rest) return `...${name}:${type}`;
      if (parameter.initializer) return `${name}:${type} = ${emitExpression(parameter.initializer, context)}`;
      return `${parameter.optional ? '?' : ''}${name}:${type}`;
    })
    .join(', ');
}

function emitStatement(statement: Readonly<IrStatement>, context: EmitContext): string[] {
  switch (statement.kind) {
    case 'block':
      return ['{', ...indentSource(emitStatements(statement.statements, context)), '}'];
    case 'break':
      return ['break;'];
    case 'continue':
      return ['continue;'];
    case 'do':
      return [
        'do {',
        ...indentSource(emitStatementBody(statement.body, context)),
        `} while (${emitExpression(statement.condition, context)});`,
      ];
    case 'expression':
      return [`${emitExpression(statement.expression, context)};`];
    case 'for':
      emissionError(context, 'C-style for loops require control-flow lowering before Haxe emission');
    case 'forIn':
      return [
        `for (${safeHaxeName(statement.variable.name)} in Reflect.fields(${emitExpression(statement.object, context)})) {`,
        ...indentSource(emitStatementBody(statement.body, context)),
        '}',
      ];
    case 'forOf':
      if (statement.await) emissionError(context, 'async iteration requires the Haxe async-lowering pass');
      return [
        `for (${safeHaxeName(statement.variable.name)} in ${emitExpression(statement.iterable, context)}) {`,
        ...indentSource(emitStatementBody(statement.body, context)),
        '}',
      ];
    case 'if': {
      const lines = [
        `if (${emitExpression(statement.condition, context)}) {`,
        ...indentSource(emitStatementBody(statement.consequent, context)),
        '}',
      ];
      if (statement.otherwise)
        lines.push('else {', ...indentSource(emitStatementBody(statement.otherwise, context)), '}');
      return lines;
    }
    case 'return':
      return [`return${statement.expression ? ` ${emitExpression(statement.expression, context)}` : ''};`];
    case 'switch': {
      assertNoSwitchFallthrough(statement, context);
      const lines = [`switch (${emitExpression(statement.expression, context)}) {`];
      for (const clause of statement.cases) {
        lines.push(`  ${clause.expression ? `case ${emitExpression(clause.expression, context)}` : 'default'}:`);
        lines.push(
          ...indentSource(
            emitStatements(
              clause.statements.filter((item) => item.kind !== 'break'),
              context,
            ),
            2,
          ),
        );
      }
      lines.push('}');
      return lines;
    }
    case 'throw':
      return [`throw ${emitExpression(statement.expression, context)};`];
    case 'try':
      if (statement.finallyBody) emissionError(context, 'finally blocks require completion-preserving Haxe lowering');
      return [
        'try {',
        ...indentSource(emitStatementBody(statement.tryBody, context)),
        '}',
        ...(statement.catchBody
          ? [
              `catch (${safeHaxeName(statement.catchName ?? 'error')}:Dynamic) {`,
              ...indentSource(emitStatementBody(statement.catchBody, context)),
              '}',
            ]
          : []),
      ];
    case 'variable':
      return statement.declarations.map((variable) => emitVariable(variable, context));
    case 'while':
      return [
        `while (${emitExpression(statement.condition, context)}) {`,
        ...indentSource(emitStatementBody(statement.body, context)),
        '}',
      ];
  }
}

function emitStatementBody(statement: Readonly<IrStatement>, context: EmitContext): string[] {
  return statement.kind === 'block' ? emitStatements(statement.statements, context) : emitStatement(statement, context);
}

function emitStatements(statements: readonly IrStatement[], context: EmitContext): string[] {
  return statements.flatMap((statement) => emitStatement(statement, context));
}

function emitType(type: Readonly<IrType>, context: EmitContext): string {
  switch (type.kind) {
    case 'array':
      return `Array<${emitType(type.element, context)}>`;
    case 'function':
      return `${type.parameters.map((parameter) => emitType(parameter.type, context)).join('->')}->${emitType(type.returns, context)}`;
    case 'indexedAccess':
    case 'keyof':
    case 'typeOf':
      return 'Dynamic';
    case 'intersection':
      return type.types.length === 1 ? emitType(type.types[0]!, context) : 'Dynamic';
    case 'literal':
      return typeof type.value === 'boolean' ? 'Bool' : typeof type.value === 'number' ? 'Float' : 'String';
    case 'named': {
      if ((type.name === 'Readonly' || type.name === 'Partial' || type.name === 'Required') && type.typeArguments[0]) {
        return emitType(type.typeArguments[0], context);
      }
      const arguments_ = type.typeArguments.map((argument) => emitType(argument, context));
      return `${qualifiedHaxeName(type.name)}${arguments_.length > 0 ? `<${arguments_.join(', ')}>` : ''}`;
    }
    case 'never':
      return 'Dynamic';
    case 'null':
    case 'undefined':
      return 'Dynamic';
    case 'object':
      return emitAnonymousType(type.members, context);
    case 'primitive':
      return {
        bigint: 'haxe.Int64',
        boolean: 'Bool',
        number: 'Float',
        string: 'String',
        symbol: 'Dynamic',
        void: 'Void',
      }[type.name];
    case 'tuple':
      return 'Array<Dynamic>';
    case 'union': {
      const concrete = type.types.filter((item) => item.kind !== 'null' && item.kind !== 'undefined');
      return concrete.length === 1 && concrete.length !== type.types.length
        ? `Null<${emitType(concrete[0]!, context)}>`
        : 'Dynamic';
    }
    case 'unknown':
      return 'Dynamic';
  }
}

function emitAnonymousType(members: readonly IrObjectTypeMember[], context: EmitContext): string {
  return `{ ${members
    .map((member) => `${member.optional ? '?' : ''}${safeHaxeName(member.name)}:${emitType(member.type, context)}`)
    .join(', ')} }`;
}

function emitTypeDeclaration(declaration: Readonly<IrDeclaration>, context: EmitContext): string[] {
  switch (declaration.kind) {
    case 'class':
      return emitClass(declaration, context);
    case 'enum':
      return emitEnum(declaration, context);
    case 'interface':
      return emitInterface(declaration, context);
    case 'type':
      return emitTypeAlias(declaration, context);
    default:
      emissionError(context, `unexpected value declaration ${declaration.name} in type emission`);
  }
}

function emitTypeAlias(declaration: Readonly<IrTypeDeclaration>, context: EmitContext): string[] {
  return [
    `typedef ${safeHaxeName(declaration.name)}${emitTypeParameters(declaration.typeParameters, context)} = ${emitType(declaration.type, context)};`,
  ];
}

function emitTypeParameters(parameters: readonly IrTypeParameter[], context: EmitContext): string {
  if (parameters.length === 0) return '';
  return `<${parameters
    .map(
      (parameter) =>
        `${safeHaxeName(parameter.name)}${parameter.constraint ? `:${emitType(parameter.constraint, context)}` : ''}`,
    )
    .join(', ')}>`;
}

function emitVariable(variable: Readonly<IrVariable>, context: EmitContext): string {
  const type = variable.type ? `:${emitType(variable.type, context)}` : '';
  const initializer = variable.initializer ? ` = ${emitExpression(variable.initializer, context)}` : '';
  return `${variable.mutable ? 'var' : 'final'} ${safeHaxeName(variable.name)}${type}${initializer};`;
}

function emitVariableDeclaration(declaration: Readonly<IrVariableDeclaration>, context: EmitContext): string[] {
  if (!declaration.initializer) emissionError(context, `module variable ${declaration.name} requires an initializer`);
  const access = declaration.exported ? 'public ' : 'private ';
  const storage = declaration.mutable ? 'var' : 'final';
  const type = declaration.type ? `:${emitType(declaration.type, context)}` : '';
  return [
    `${access}static ${storage} ${safeHaxeName(declaration.name)}${type} = ${emitExpression(declaration.initializer, context)};`,
  ];
}

function emissionError(context: EmitContext, message: string): never {
  throw createBackendEmissionError('haxe', context.module.source, message);
}

function haxeImportModule(specifier: string, context: EmitContext): string {
  if (specifier.startsWith('.')) {
    const target = path.posix.normalize(
      path.posix.join(path.posix.dirname(context.module.source), specifier.replace(/\.[cm]?js$/u, '')),
    );
    return `${context.packageName}.${haxeImplementationModule(target)}`;
  }
  if (specifier.startsWith('@')) {
    const packageName = /^(@[^/]+\/[^/]+)/u.exec(specifier)?.[1];
    if (!packageName) emissionError(context, `cannot identify package import ${specifier}`);
    const haxePackage = packageNameToHaxePackage(packageName, context.options.rootPackage);
    const packageModule = pascalCase(haxePackage.split('.').at(-1)!);
    return `${haxePackage}.${packageModule}`;
  }
  emissionError(context, `external import ${specifier} requires a runtime or standard-library mapping`);
}

function haxeImplementationModule(sourcePath: string): string {
  const filename = path.posix.basename(sourcePath).replace(/\.tsx?$/u, '');
  return sourcePathToHaxeModule(sourcePath) ?? `_${pascalCase(filename)}`;
}

function mapOperator(operator: string, assignment: boolean, context: EmitContext): string {
  const allowed = assignment ? haxeAssignmentOperators : haxeBinaryOperators;
  if (!allowed.has(operator)) emissionError(context, `operator ${operator} requires Haxe semantic lowering`);
  return { '===': '==', '!==': '!=' }[operator] ?? operator;
}

function assertNoSwitchFallthrough(statement: Extract<IrStatement, { kind: 'switch' }>, context: EmitContext): void {
  statement.cases.slice(0, -1).forEach((clause) => {
    const last = clause.statements.at(-1);
    if (!last || (last.kind !== 'break' && last.kind !== 'return' && last.kind !== 'throw')) {
      emissionError(context, 'switch fallthrough requires control-flow lowering before Haxe emission');
    }
  });
}

function pascalCase(value: string): string {
  const match = /^(?<prefix>_*)(?<name>.*)$/u.exec(value);
  const prefix = match?.groups?.prefix ?? '';
  const name = match?.groups?.name ?? value;
  return `${prefix}${name
    .split(/[-_]/u)
    .filter(Boolean)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join('')}`;
}

function qualifiedHaxeName(name: string): string {
  return name
    .split('.')
    .map((segment) => safeHaxeName(segment))
    .join('.');
}

function safeHaxeName(name: string): string {
  return haxeKeywords.has(name) ? `${name}_` : name;
}

const haxeKeywords = new Set([
  'abstract',
  'break',
  'case',
  'cast',
  'catch',
  'class',
  'continue',
  'default',
  'do',
  'dynamic',
  'else',
  'enum',
  'extends',
  'extern',
  'false',
  'final',
  'for',
  'function',
  'if',
  'implements',
  'import',
  'in',
  'inline',
  'interface',
  'macro',
  'new',
  'null',
  'operator',
  'overload',
  'override',
  'package',
  'private',
  'public',
  'return',
  'static',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typedef',
  'untyped',
  'using',
  'var',
  'while',
]);

const haxeAssignmentOperators = new Set(['=', '+=', '-=', '*=', '/=', '%=', '&=', '|=', '^=', '<<=', '>>=']);

const haxeBinaryOperators = new Set([
  '!==',
  '!=',
  '%',
  '&',
  '&&',
  '*',
  '+',
  '-',
  '/',
  '<',
  '<<',
  '<=',
  '===',
  '==',
  '>',
  '>=',
  '>>',
  '^',
  '|',
  '||',
]);

const haxeUnaryOperators = new Set(['!', '+', '-', '++', '--', '~']);
