import type { CompilerHaxeAmbientMemberBinding, IrResolvedMember } from '../../compiler-types/src/index.js';

// How Haxe spells a member of the ambient surface.
//
// A rename is the common case and stays data. A member Haxe puts somewhere else entirely — `trim` is
// a `StringTools` function, not a method — is a static call with the receiver as its first argument.
// A member absent from this table has no agreed Haxe spelling and is refused rather than guessed at,
// because a name that happens to exist on the target is the most expensive kind of coincidence.

export function getCompilerHaxeAmbientMemberBinding(
  member: Readonly<IrResolvedMember>,
): CompilerHaxeAmbientMemberBinding | undefined {
  return haxeAmbientMemberBindings[`${member.receiver}.${member.name}`];
}

const haxeAmbientMemberBindings: Readonly<Record<string, CompilerHaxeAmbientMemberBinding>> = {
  'array.concat': { kind: 'method', targetName: 'concat' },
  'array.copyWithin': { kind: 'runtimeCall', targetName: '_Array.copyWithin' },
  'array.every': { kind: 'staticCall', targetPath: 'Lambda.foreach' },
  'array.filter': { kind: 'method', targetName: 'filter' },
  'array.flatMap': { kind: 'runtimeCall', targetName: '_Array.flatMap' },
  'array.find': { kind: 'staticCall', targetPath: 'Lambda.find' },
  'array.findIndex': { kind: 'runtimeCall', targetName: '_Array.findIndex' },
  'array.forEach': { kind: 'staticCall', targetPath: 'Lambda.iter' },
  'array.includes': { kind: 'method', targetName: 'contains' },
  'array.indexOf': { intArguments: [1], kind: 'method', targetName: 'indexOf' },
  'array.join': { kind: 'method', targetName: 'join' },
  'array.lastIndexOf': { intArguments: [1], kind: 'method', targetName: 'lastIndexOf' },
  'array.length': { kind: 'property', targetName: 'length' },
  'array.map': { kind: 'method', targetName: 'map' },
  'array.pop': { kind: 'method', targetName: 'pop' },
  'array.push': { kind: 'method', targetName: 'push' },
  'array.reduce': { kind: 'staticFold', targetPath: 'Lambda.fold' },
  'array.reverse': { kind: 'method', targetName: 'reverse' },
  'array.some': { kind: 'staticCall', targetPath: 'Lambda.exists' },
  'array.sort': { kind: 'runtimeCall', targetName: '_Array.sort' },
  'array.splice': { intArguments: [0, 1], kind: 'method', targetName: 'splice' },
  'array.shift': { kind: 'method', targetName: 'shift' },
  'array.slice': { kind: 'method', targetName: 'slice' },
  'array.unshift': { kind: 'method', targetName: 'unshift' },
  'date.getDate': { kind: 'method', targetName: 'getDate' },
  'date.getDay': { kind: 'method', targetName: 'getDay' },
  'date.getFullYear': { kind: 'method', targetName: 'getFullYear' },
  'date.getHours': { kind: 'method', targetName: 'getHours' },
  'date.getMilliseconds': { kind: 'method', targetName: 'getMilliseconds' },
  'date.getMinutes': { kind: 'method', targetName: 'getMinutes' },
  'date.getMonth': { kind: 'method', targetName: 'getMonth' },
  'date.getSeconds': { kind: 'method', targetName: 'getSeconds' },
  'date.getTime': { kind: 'method', targetName: 'getTime' },
  'date.toISOString': { kind: 'method', targetName: 'toISOString' },
  'date.toString': { kind: 'method', targetName: 'toString' },
  'dataView.buffer': { kind: 'property', targetName: 'buffer' },
  'dataView.byteLength': { kind: 'property', targetName: 'byteLength' },
  'dataView.byteOffset': { kind: 'property', targetName: 'byteOffset' },
  'dataView.getFloat32': { intArguments: [0], kind: 'method', targetName: 'getFloat32' },
  'dataView.getFloat64': { intArguments: [0], kind: 'method', targetName: 'getFloat64' },
  'dataView.getInt8': { intArguments: [0], kind: 'method', targetName: 'getInt8' },
  'dataView.getInt16': { intArguments: [0], kind: 'method', targetName: 'getInt16' },
  'dataView.getInt32': { intArguments: [0], kind: 'method', targetName: 'getInt32' },
  'dataView.getUint8': { intArguments: [0], kind: 'method', targetName: 'getUint8' },
  'dataView.getUint16': { intArguments: [0], kind: 'method', targetName: 'getUint16' },
  'dataView.getUint32': { intArguments: [0], kind: 'method', targetName: 'getUint32' },
  'dataView.setFloat32': { intArguments: [0], kind: 'method', targetName: 'setFloat32' },
  'dataView.setFloat64': { intArguments: [0], kind: 'method', targetName: 'setFloat64' },
  'dataView.setInt8': { intArguments: [0], kind: 'method', targetName: 'setInt8' },
  'dataView.setInt16': { intArguments: [0], kind: 'method', targetName: 'setInt16' },
  'dataView.setInt32': { intArguments: [0], kind: 'method', targetName: 'setInt32' },
  'dataView.setUint8': { intArguments: [0], kind: 'method', targetName: 'setUint8' },
  'dataView.setUint16': { intArguments: [0], kind: 'method', targetName: 'setUint16' },
  'dataView.setUint32': { intArguments: [0], kind: 'method', targetName: 'setUint32' },
  'error.message': { kind: 'property', targetName: 'message' },
  'number.toFixed': { kind: 'runtimeCall', targetName: '_Number.toFixed' },
  'number.toString': { kind: 'staticCall', targetPath: 'Std.string' },
  'regexp.exec': { kind: 'method', targetName: 'exec' },
  'regexp.test': { kind: 'method', targetName: 'test' },
  'map.delete': { kind: 'method', targetName: 'delete' },
  'map.entries': { kind: 'method', targetName: 'entries' },
  'map.clear': { kind: 'method', targetName: 'clear' },
  'map.forEach': { kind: 'method', targetName: 'forEach' },
  'map.get': { kind: 'method', targetName: 'get' },
  'map.has': { kind: 'method', targetName: 'has' },
  'map.keys': { kind: 'method', targetName: 'keys' },
  'map.set': { kind: 'method', targetName: 'set' },
  'map.size': { kind: 'property', targetName: 'size' },
  'map.values': { kind: 'method', targetName: 'values' },
  'set.add': { kind: 'method', targetName: 'add' },
  'set.clear': { kind: 'method', targetName: 'clear' },
  'set.delete': { kind: 'method', targetName: 'delete' },
  'set.has': { kind: 'method', targetName: 'has' },
  'set.size': { kind: 'property', targetName: 'size' },
  'string.charAt': { intArguments: [0], kind: 'method', targetName: 'charAt' },
  'string.charCodeAt': { intArguments: [0], kind: 'method', targetName: 'charCodeAt' },
  'string.codePointAt': { kind: 'runtimeCall', targetName: '_StringTools.codePointAt' },
  'string.endsWith': { kind: 'staticCall', targetPath: 'StringTools.endsWith' },
  'string.includes': { kind: 'staticCall', targetPath: 'StringTools.contains' },
  'string.indexOf': { intArguments: [1], kind: 'method', targetName: 'indexOf' },
  'string.lastIndexOf': { intArguments: [1], kind: 'method', targetName: 'lastIndexOf' },
  'string.length': { kind: 'property', targetName: 'length' },
  'string.match': { kind: 'runtimeCall', targetName: '_StringTools.match' },
  'string.padStart': { kind: 'runtimeCall', targetName: '_StringTools.padStart' },
  'string.padEnd': { kind: 'runtimeCall', targetName: '_StringTools.padEnd' },
  'string.replace': { kind: 'runtimeCall', targetName: '_StringTools.replaceFirst' },
  'string.search': { kind: 'runtimeCall', targetName: '_StringTools.search' },
  'string.slice': { kind: 'runtimeCall', targetName: '_StringTools.slice' },
  'string.split': { kind: 'method', targetName: 'split' },
  'string.startsWith': { kind: 'staticCall', targetPath: 'StringTools.startsWith' },
  'string.substring': { intArguments: [0, 1], kind: 'method', targetName: 'substring' },
  'string.toLowerCase': { kind: 'method', targetName: 'toLowerCase' },
  'string.toUpperCase': { kind: 'method', targetName: 'toUpperCase' },
  'string.trim': { kind: 'staticCall', targetPath: 'StringTools.trim' },
  'string.trimStart': { kind: 'runtimeCall', targetName: '_StringTools.trimStart' },
  'task.then': { kind: 'method', targetName: 'then' },
  'textDecoder.decode': { kind: 'method', targetName: 'decode' },
  'typedArray.buffer': { kind: 'property', targetName: 'buffer' },
  'typedArray.byteLength': { kind: 'property', targetName: 'byteLength' },
  'typedArray.byteOffset': { kind: 'property', targetName: 'byteOffset' },
  'typedArray.length': { kind: 'property', targetName: 'length' },
  'typedArray.fill': { intArguments: [1, 2], kind: 'method', targetName: 'fill' },
  'typedArray.set': { intArguments: [1], kind: 'method', targetName: 'set' },
  'typedArray.slice': { kind: 'method', targetName: 'slice' },
  'typedArray.subarray': { kind: 'method', targetName: 'subarray' },
  'tuple.length': { kind: 'property', targetName: 'length' },
};
