import ts from 'typescript';

import { isBackendEmissionFailure } from '../../compiler-emission/src/index.js';
import { lowerTypeScriptSource } from '../../compiler-semantic/src/index.js';
import { createHaxeCompilerBackend, emitIrModuleHaxe } from './haxeCompilerBackend.js';

function lower(file: string, source: string) {
  return lowerPackage('@flighthq/math', file, source);
}

function lowerPackage(packageName: string, file: string, source: string) {
  const packageDirectory = packageName.slice(packageName.lastIndexOf('/') + 1);
  const sourceFile = ts.createSourceFile(
    `/flight/packages/${packageDirectory}/src/${file}`,
    source,
    ts.ScriptTarget.Latest,
    true,
  );
  return lowerTypeScriptSource(sourceFile, {
    packageName,
    upstreamDirectory: '/flight',
  });
}

describe('createHaxeCompilerBackend', () => {
  it('creates independent stateless backend records with Haxe identity', () => {
    const first = createHaxeCompilerBackend();
    const second = createHaxeCompilerBackend();
    const module = lower('value.ts', 'export const value = 1;').module;

    expect(first).not.toBe(second);
    expect(first.name).toBe('haxe');
    expect(first.emitModule(module, { modules: [module], options: {} })).toEqual([emitIrModuleHaxe(module)]);
  });

  it('uses explicit package-export resolution from the complete backend module context', () => {
    const target = lowerPackage('@flighthq/types', 'public.ts', 'export interface Box { value: number }').module;
    const subject = lowerPackage(
      '@flighthq/core',
      'use.ts',
      "import type { Box } from '@flighthq/types/public'; export const box: Box = {};",
    ).module;
    const backend = createHaxeCompilerBackend();

    expect(() => backend.emitModule(subject, { modules: [subject, target], options: {} })).not.toThrow();
    expect(() =>
      backend.emitModule(subject, {
        moduleResolution: {
          edges: [
            {
              specifier: '@flighthq/types/public',
              target: { packageName: '@flighthq/types', source: target.source },
            },
          ],
          schema: 'flight-compiler-module-resolution/1',
        },
        modules: [subject, target],
        options: {},
      }),
    ).toThrow('structural object compatibility missing-required-property');
  });
});

describe('emitIrModuleHaxe', () => {
  it('reports structural object incompatibility before Haxe source emission', () => {
    const result = lower(
      'duplicate-object.ts',
      'export function create(): { value: number } { return { value: 1, value: 2 }; }',
    );

    expect(() => emitIrModuleHaxe(result.module)).toThrow(
      'structural object compatibility duplicate-property-requires-normalization',
    );
    try {
      emitIrModuleHaxe(result.module);
    } catch (error) {
      expect(isBackendEmissionFailure(error)).toBe(true);
    }
  });

  it('constructs generic structural records with substituted nested target types', () => {
    const result = lower(
      'generic-object.ts',
      `
        interface Item { label: string }
        interface Box<Value> { value: Value; optional?: Value }
        export function create(): Box<Item> { return { value: { label: 'flight' } }; }
      `,
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('typedef Box<Value> = { value:Value, ?optional:Value };');
    expect(output).toContain('public static function create():Box<Item>');
    expect(output).toContain('return { value: { label: "flight" } };');
  });

  it('refuses optional nullable parameters until Haxe preserves distinct null and undefined sentinels', () => {
    const result = lower('optional-nullable.ts', 'export function choose(value?: number | null): void { value; }');

    expect(() => emitIrModuleHaxe(result.module)).toThrow(
      'optional nullable parameters require distinct Haxe null and undefined sentinels',
    );
  });

  it('emits shared traceable provenance with an optional upstream commit', () => {
    const module = lower('value.ts', 'export const value = 1;').module;
    const commit = '0123456789abcdef0123456789abcdef01234567';

    expect(emitIrModuleHaxe(module).contents.split('\n')[0]).toBe(
      '// Generated by @flighthq/tool-compiler from @flighthq/math/packages/math/src/value.ts#Value. Do not edit.',
    );
    expect(emitIrModuleHaxe(module, { upstreamCommit: commit }).contents.split('\n')[0]).toBe(
      `// Generated by @flighthq/tool-compiler from @flighthq/math/packages/math/src/value.ts#Value at ${commit}. Do not edit.`,
    );
  });

  it('emits explicit type and value runtime bindings and rejects incomplete symbol spaces first', () => {
    const supported = lower(
      'external-types.ts',
      'export function preserve(values: Map<string, number>, bytes: Uint8Array, task: Promise<number>): Promise<number> { values; bytes; return task; }',
    );
    const missing = lower('external-missing.ts', 'export type operator = Date; export type operator_ = Date;');
    const missingValue = lower('external-value-missing.ts', 'export function fail(): void { throw new Error(); }');
    const values = lower(
      'external-values.ts',
      'export function create(): Promise<number> { const values = new Map<string, number>(); const bytes = new Uint8Array(3); values; bytes; return Promise.resolve(1); }',
    );
    const output = emitIrModuleHaxe(supported.module).contents;
    const custom = emitIrModuleHaxe(supported.module, { runtimeModule: 'custom.runtime' }).contents;
    const valueOutput = emitIrModuleHaxe(values.module).contents;
    const customValueOutput = emitIrModuleHaxe(values.module, { runtimeModule: 'custom.runtime' }).contents;

    expect(output).toContain('values:flighthq._internal._Map<String, Float>');
    expect(output).toContain('bytes:flighthq._internal._UInt8Array');
    expect(output).toContain('task:flighthq._internal._Promise<Float>');
    expect(custom).toContain('task:custom.runtime._Promise<Float>');
    expect(valueOutput).toContain('new flighthq._internal._Map()');
    expect(valueOutput).toContain('new flighthq._internal._UInt8Array(3)');
    expect(valueOutput).toContain('flighthq._internal._Promise.resolve(1)');
    expect(customValueOutput).toContain('new custom.runtime._UInt8Array(3)');
    expect(customValueOutput).toContain('new custom.runtime._Map()');
    expect(customValueOutput).toContain('custom.runtime._Promise.resolve(1)');
    expect(() => emitIrModuleHaxe(missing.module)).toThrow(
      'runtime external symbol binding plan is incomplete (missing: Date[type])',
    );
    expect(() => emitIrModuleHaxe(missingValue.module)).toThrow(
      'runtime external symbol binding plan is incomplete (missing: Error[value])',
    );
  });

  it('refuses runtime constructor arities absent from the versioned Haxe ABI plan', () => {
    const fixed = lower('array-constructor.ts', 'export function create(): number[] { return new Array<number>(3); }');
    const dynamic = lower(
      'map-constructor-spread.ts',
      'export function create(values: []): Map<string, number> { return new Map<string, number>(...values); }',
    );

    expect(() => emitIrModuleHaxe(fixed.module)).toThrow(
      'runtime external constructor ABI plan is incomplete (missing: Array[value](1))',
    );
    expect(() => emitIrModuleHaxe(dynamic.module)).toThrow(
      'runtime external constructor ABI plan is incomplete (missing: Map[value](...))',
    );
  });

  it('refuses qualified constructors outside direct ambient ABI identity', () => {
    const result = lower(
      'qualified-constructor.ts',
      'class Value {} export function create(namespace: { Value: typeof Value }): Value { return new namespace.Value(); }',
    );

    expect(() => emitIrModuleHaxe(result.module)).toThrow('qualified constructors require Haxe type-path lowering');
  });

  it('elects C-style for lowering without lowering native Haxe default parameters', () => {
    const loop = lower(
      'loop.ts',
      'export function total(limit: number): number { let total = 0; for (let index = 0; index < limit; index++) { total += index; } return total; }',
    );
    const defaults = lower(
      'defaults.ts',
      'export function scale(value: number, factor: number = 2): number { return value * factor; }',
    );
    const output = emitIrModuleHaxe(loop.module).contents;

    expect(output).toContain('var index:Float = 0;');
    expect(output).toContain('while ((index < limit))');
    expect(output).toContain('index += 1;');
    expect(emitIrModuleHaxe(defaults.module).contents).toContain('factor:Float = 2');
  });

  it('emits one overload implementation and calls its native default ABI', () => {
    const result = lower(
      'overload-default.ts',
      `
        function choose(value: number): number;
        function choose(value: number, radix?: number): number;
        function choose(value: number, radix = 10): number { return value + radix; }
        export function read(): number { return choose(1); }
      `,
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output.match(/static function choose/gu)).toHaveLength(1);
    expect(output).toContain('static function choose(value:Float, radix:Float = 10):Float');
    expect(output).toContain('return choose(1);');
  });

  it('emits one class method overload implementation and calls its native default ABI', () => {
    const result = lower(
      'method-overload-default.ts',
      `
        export class Picker {
          choose(value: number): number;
          choose(value: number, radix?: number): number;
          choose(value: number, radix = 10): number { return value + radix; }
        }
        export function read(picker: Picker): number { return picker.choose(1); }
      `,
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output.match(/function choose/gu)).toHaveLength(1);
    expect(output).toContain('public function choose(value:Float, radix:Float = 10):Float');
    expect(output).toContain('return picker.choose(1);');
  });

  it('emits one constructor implementation and calls its native default ABI', () => {
    const result = lower(
      'constructor-overload-default.ts',
      `
        export class Box {
          constructor(value: number);
          constructor(value: number, radix?: number);
          constructor(value: number, radix = 10) { value; radix; }
        }
        export function create(): Box { return new Box(1); }
      `,
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output.match(/public function new/gu)).toHaveLength(1);
    expect(output).toContain('public function new(value:Float, radix:Float = 10)');
    expect(output).toContain('return new Box(1);');
  });

  it('emits parameter-property storage at base and derived initialization boundaries', () => {
    const base = lower(
      'reader.ts',
      'export class Reader { constructor(readonly source: string, public position: number) { position; } }',
    );
    const derived = lower(
      'derived.ts',
      `
        class Base { constructor(value: string) { value; } }
        export class Derived extends Base {
          code = 1;
          constructor(value: string, readonly label: string) {
            value;
            super(value);
            label;
          }
        }
      `,
    );
    const baseOutput = emitIrModuleHaxe(base.module).contents;
    const derivedOutput = emitIrModuleHaxe(derived.module).contents;

    expect(base.diagnostics).toEqual([]);
    expect(baseOutput).toContain('final source:String;');
    expect(baseOutput).toContain('public var position:Float;');
    expect(baseOutput).toContain(
      'public function new(source:String, position:Float) {\n    this.source = source;\n    this.position = position;\n    position;\n  }',
    );
    expect(derived.diagnostics).toEqual([]);
    expect(derivedOutput).toContain('var code:Float;');
    expect(derivedOutput).toContain(
      'value;\n    super(value);\n    this.code = 1;\n    this.label = label;\n    label;',
    );
    expect(derivedOutput.indexOf('super(value)')).toBeLessThan(derivedOutput.indexOf('this.code = 1'));
    expect(derivedOutput.indexOf('this.code = 1')).toBeLessThan(derivedOutput.indexOf('this.label = label'));
  });

  it('refuses derived constructor shapes whose field timing cannot be preserved', () => {
    const implicit = lower('implicit-derived.ts', 'class Base {} export class Derived extends Base {}');
    const conditional = lower(
      'conditional-super.ts',
      'class Base {} export class Derived extends Base { value = 1; constructor(flag: boolean) { if (flag) super(); else super(); } }',
    );
    const repeated = lower(
      'repeated-super.ts',
      'class Base {} export class Derived extends Base { constructor(flag: boolean) { super(); if (flag) super(); } }',
    );
    const base = lower('base-super.ts', 'export class Base { constructor() { super(); } }');

    expect(() => emitIrModuleHaxe(implicit.module)).toThrow(
      'class Derived implicit derived constructor requires inherited-ABI forwarding',
    );
    expect(() => emitIrModuleHaxe(conditional.module)).toThrow(
      'super constructor calls require a direct derived-constructor statement in Haxe',
    );
    expect(() => emitIrModuleHaxe(repeated.module)).toThrow(
      'super constructor calls require a direct derived-constructor statement in Haxe',
    );
    expect(() => emitIrModuleHaxe(base.module)).toThrow(
      'super constructor calls require a direct derived-constructor statement in Haxe',
    );
  });

  it('maps ambient Error inheritance to Haxe exception storage', () => {
    const result = lower(
      'timeout.ts',
      `
        export class Timeout extends Error {
          readonly channel: string;
          constructor(channel: string) {
            super(channel);
            this.name = 'Timeout';
            this.channel = channel;
          }
        }
      `,
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(result.diagnostics).toEqual([]);
    expect(output).toContain('class Timeout extends haxe.Exception {');
    expect(output).toContain('public var name:String;');
    expect(output).toContain(
      'super(channel);\n    this.name = "Error";\n    this.name = "Timeout";\n    this.channel = channel;',
    );
  });

  it('evaluates fixed extra arguments before erasing them from a Haxe call', () => {
    const result = lower(
      'extra-argument.ts',
      'function effect(value: number): number { return value; } function choose(value: number): number { return value; } export function read(): number { return choose(effect(1), effect(2)); }',
    );
    const property = lower(
      'property-extra-argument.ts',
      'export class Picker { choose(value: number): number { return value; } } export function read(picker: Picker): number { return picker.choose(1, 2); }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('final callArgument0 = effect(1);');
    expect(output).toContain('final callArgument1 = effect(2);');
    expect(output).toContain('choose(callArgument0);');
    expect(output).not.toContain('choose(effect(1), effect(2))');
    expect(output.indexOf('callArgument0 = effect(1)')).toBeLessThan(output.indexOf('callArgument1 = effect(2)'));
    expect(output.indexOf('callArgument1 = effect(2)')).toBeLessThan(output.indexOf('choose(callArgument0)'));
    expect(() => emitIrModuleHaxe(property.module)).toThrow('fixed extra call arguments remain after erasure');
  });

  it('elects fixed array binding lowering and reports residual destructuring semantics', () => {
    const fixed = lower(
      'array-binding.ts',
      'export function select(values: [number, number, number]): number { const [first, , third]: [number, number, number] = values; third; return first; }',
    );
    const defaulted = lower(
      'array-default.ts',
      'export function select(values: [number?]): number { const [first = 0]: [number?] = values; return first; }',
    );
    const requiredDefault = lower(
      'array-required-default.ts',
      'export function select(values: [number | undefined]): number { const [first = 0]: [number | undefined] = values; return first; }',
    );
    const dynamicIndex = lower(
      'tuple-index.ts',
      'export function select(values: [number], index: number): number { return values[index]; }',
    );
    const rest = lower(
      'array-rest.ts',
      'export function select(values: [number, ...number[]]): number[] { const [first, ...rest]: [number, ...number[]] = values; first; return rest; }',
    );
    const nestedDefault = lower(
      'array-nested-default.ts',
      'export function select(values: [[number]?]): number { const [[first] = [1]]: [[number]?] = values; return first; }',
    );
    const fixedRest = lower(
      'array-fixed-rest.ts',
      'export function select(values: [number, string, boolean]): [string, boolean] { const [first, ...rest]: [number, string, boolean] = values; first; return rest; }',
    );
    const emptyRest = lower(
      'array-empty-rest.ts',
      'export function select(values: [number]): [] { const [first, ...rest]: [number] = values; first; return rest; }',
    );
    const optionalRest = lower(
      'array-optional-rest.ts',
      'export function select(values: [number, string?]): [string?] { const [first, ...rest]: [number, string?] = values; first; return rest; }',
    );
    const mixedRest = lower(
      'array-mixed-rest.ts',
      'export function select(values: [number, string, ...boolean[]]): [string, ...boolean[]] { const [first, ...rest]: [number, string, ...boolean[]] = values; first; return rest; }',
    );
    const iteration = lower(
      'array-iteration.ts',
      'export function visit(rows: Array<[number, number]>): number { for (const [first, second] of rows) { second; return first; } return 0; }',
    );
    const output = emitIrModuleHaxe(fixed.module).contents;

    expect(output).toContain('final arrayPatternValue:Array<Dynamic> = values;');
    expect(output).toContain('final first:Float = arrayPatternValue[0];');
    expect(output).toContain('final third:Float = arrayPatternValue[2];');
    expect(emitIrModuleHaxe(defaulted.module).contents).toContain('final first:Float = (arrayPatternValue[0] ?? 0);');
    expect(emitIrModuleHaxe(requiredDefault.module).contents).toContain(
      'final first:Float = (arrayPatternValue[0] ?? 0);',
    );
    expect(emitIrModuleHaxe(rest.module).contents).toContain('final rest:Array<Float> = arrayPatternValue.slice(1);');
    expect(emitIrModuleHaxe(nestedDefault.module).contents).toContain('(arrayPatternValue[0] ?? [1])');
    expect(emitIrModuleHaxe(fixedRest.module).contents).toContain(
      'final rest:Array<Dynamic> = arrayPatternValue.slice(1);',
    );
    expect(emitIrModuleHaxe(emptyRest.module).contents).toContain(
      'final rest:Array<Dynamic> = arrayPatternValue.slice(1);',
    );
    expect(emitIrModuleHaxe(optionalRest.module).contents).toContain(
      'final rest:Array<Dynamic> = arrayPatternValue.slice(1);',
    );
    expect(emitIrModuleHaxe(mixedRest.module).contents).toContain(
      'final rest:Array<Dynamic> = arrayPatternValue.slice(1);',
    );
    expect(emitIrModuleHaxe(iteration.module).contents).toContain(
      'for (arrayPatternValue in rows) {\n      final first:Float = arrayPatternValue[0];\n      final second:Float = arrayPatternValue[1];',
    );
    expect(() => emitIrModuleHaxe(dynamicIndex.module)).toThrow(
      'tuple projection requires one statically known nonnegative integer index',
    );
  });

  it('elects object binding lowering with named and proven-string computed rest copies', () => {
    const named = lower(
      'object-binding.ts',
      `
        type Shape = { value?: number; other: boolean };
        export function select(source: Shape): number {
          const { value = 1, ...rest }: Shape = source;
          rest.other;
          return value;
        }
      `,
    );
    const computed = lower(
      'object-computed.ts',
      `
        type Shape = { value: number; other: boolean };
        export function select(source: Shape, key: string): object {
          const { [key]: value, ...rest }: Shape = source;
          value;
          return rest;
        }
      `,
    );
    const output = emitIrModuleHaxe(named.module).contents;

    expect(output).toContain('final objectPatternValue:Shape = source;');
    expect(output).toContain('final value:Float = (objectPatternValue.value ?? 1);');
    expect(output).toContain('Reflect.copy(objectPatternValue)');
    expect(output).toContain('Reflect.deleteField(objectRestValue, "value")');
    const computedOutput = emitIrModuleHaxe(computed.module).contents;
    expect(computedOutput).toContain('Reflect.field(objectPatternValue, objectPatternKey)');
    expect(computedOutput).toContain('Reflect.deleteField(objectRestValue, objectPatternKey)');
  });

  it('elects function-scoped variable hoisting after destructuring normalization', () => {
    const named = lower(
      'variable-hoisting.ts',
      'export function select(): number { { var value: number = 1; } return value; }',
    );
    const pattern = lower(
      'variable-pattern-hoisting.ts',
      'export function select(values: [number, string]): string { var [first, second]: [number, string] = values; first; return second; }',
    );
    const iteration = lower(
      'variable-iteration-hoisting.ts',
      'export function visit(values: number[]): void { for (var value of values) value += 1; } export function keys(values: { value: number }): void { for (var key in values) key; }',
    );
    const namedOutput = emitIrModuleHaxe(named.module).contents;
    const patternOutput = emitIrModuleHaxe(pattern.module).contents;
    const iterationOutput = emitIrModuleHaxe(iteration.module).contents;

    expect(namedOutput).toContain('var value:Float;\n    {\n      value = 1;\n    }\n    return value;');
    expect(patternOutput).toContain(
      'var first:Float;\n    var second:String;\n    final arrayPatternValue:Array<Dynamic> = values;\n    first = arrayPatternValue[0];\n    second = arrayPatternValue[1];',
    );
    expect(iterationOutput).toContain(
      'var value:Float;\n    for (variableHoistingIterationValue in values) {\n      value = variableHoistingIterationValue;\n      value += 1;',
    );
    // A written shape has a known key set, so iteration is over that set rather than over whatever
    // reflection reports at runtime.
    expect(iterationOutput).toContain(
      'var key;\n    for (variableHoistingIterationValue in ["value"]) {\n      key = variableHoistingIterationValue;\n      key;',
    );
  });

  it('emits contextual fixed tuple expressions with explicit optional positions', () => {
    const result = lower(
      'tuple-expression.ts',
      "export function create(): [number, string?] { const present: [number, string?] = [1, 'flight']; const value: [number, string?] = [2]; present; return value; }",
    );

    expect(result.diagnostics).toEqual([]);
    expect(emitIrModuleHaxe(result.module).contents).toContain('final present:Array<Dynamic> = [1, "flight"];');
    expect(emitIrModuleHaxe(result.module).contents).toContain('final value:Array<Dynamic> = [2, null];');
  });

  it('emits statically ordered pure-object for-in keys', () => {
    const result = lower(
      'static-for-in.ts',
      "export function first(): string { for (const key in { second: 2, 10: 10, 2: 2, first: 1 }) return key; return ''; }",
    );

    expect(emitIrModuleHaxe(result.module).contents).toContain('for (key in ["2", "10", "second", "first"])');
  });

  it('preserves effectful object construction before iterating its closed keys', () => {
    const result = lower(
      'effectful-for-in.ts',
      'function mark(): number { return 1; } export function visit(): void { for (const key in { value: mark() }) key; }',
    );

    const output = emitIrModuleHaxe(result.module).contents;
    expect(output).toContain('final forInObjectValue = { value: mark() };');
    expect(output).toContain('for (key in ["value"])');
  });

  it('emits target-native optional property and method targets without duplicating receiver evaluation', () => {
    const result = lower(
      'optional-property.ts',
      `
        interface Value { count: number; read(): number }
        export function count(value?: Value): number | undefined { return value?.count; }
        export function read(value?: Value): number | undefined { return value?.read(); }
      `,
    );

    const output = emitIrModuleHaxe(result.module).contents;
    expect(output).toContain('return value?.count;');
    expect(output).toContain('return value?.read();');
  });

  it('emits neutral optional element and call contracts through Haxe safe navigation', () => {
    const result = lower(
      'optional-targets.ts',
      `
        export function first(values?: number[]): number | undefined { return values?.[0]; }
        export function invoke(callback?: () => number): number | undefined { return callback?.(); }
      `,
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('return values?.[0];');
    expect(output).toContain('return callback?.();');
  });

  it('emits expression-position destructuring with the original aggregate completion value', () => {
    const result = lower(
      'assignment-completion.ts',
      'export function assign(tuple: [number]): [number] { let value = 0; return ([value] = tuple); }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('return ({ final destructuringAssignmentValue:Array<Dynamic> = tuple;');
    expect(output).toContain('value = destructuringAssignmentValue[0];');
    expect(output).toContain('destructuringAssignmentValue; })');
    expect(output).not.toContain('(function()');
  });

  it('represents observable function-entry undefined as a Dynamic null sentinel', () => {
    const result = lower('entry-undefined.ts', 'export function read(): number { var value: number; return value; }');
    const declaration = result.module.declarations[0];
    if (declaration?.kind !== 'function' || declaration.body[0]?.kind !== 'variable') {
      throw new Error('Expected function variable prefix');
    }
    const variable = declaration.body[0].declarations[0];
    if (!variable || 'pattern' in variable) throw new Error('Expected named variable');
    (variable as { initialValue?: 'undefined' }).initialValue = 'undefined';

    expect(emitIrModuleHaxe(result.module).contents).toContain('var value:Dynamic = null;');
  });

  it('emits fixed tuple spreads with collision-free sequential evaluation carriers', () => {
    const result = lower(
      'tuple-spread.ts',
      `
        function marker(value: number): number { return value; }
        function optional(): [boolean?] { return []; }
        export function combine(tupleSpreadElement: number, tupleSpreadValue: [number, string]): [number, number, string, boolean?] {
          const output: [number, number, string, boolean?] = [marker(tupleSpreadElement), ...tupleSpreadValue, ...optional()];
          marker(tupleSpreadValue[0]);
          return output;
        }
      `,
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(result.diagnostics).toEqual([]);
    expect(output).toContain(
      '(function() { final tupleSpreadElement_2 = marker(tupleSpreadElement); final tupleSpreadValue_2 = tupleSpreadValue; final tupleSpreadValue_3 = optional(); return [tupleSpreadElement_2, tupleSpreadValue_2[0], tupleSpreadValue_2[1], tupleSpreadValue_3[0]]; })()',
    );
  });

  it('reports pass-named failures from the elected lowering plan', () => {
    const result = lower(
      'unsafe-loop.ts',
      'export function loop(): void { for (let index = 0; index < 1; index++) { try { continue; } finally { index; } } }',
    );

    expect(() => emitIrModuleHaxe(result.module)).toThrow(
      'Compiler lowering pass c-style-for failed for @flighthq/math/packages/math/src/unsafe-loop.ts: continue across a finally block requires completion-record lowering',
    );
  });

  it('emits numeric and string enums from neutral representation', () => {
    const numeric = lower('mode.ts', 'export enum Mode { A = 1, B, C = Mode.A << 3, D }');
    const strings = lower('kind.ts', "export enum Kind { A = 'a', B = 'b' }");

    expect(emitIrModuleHaxe(numeric.module).contents).toContain('var D = 9;');
    expect(emitIrModuleHaxe(strings.module).contents).toContain('enum abstract Kind(String) from String to String');
  });

  it('uses one identity for emitted and imported index modules and rejects default imports', () => {
    const index = lower('index.ts', 'export function helper(): number { return 1; }');
    const consumer = lower(
      'consumer.ts',
      "import { helper } from './index.js'; export function use(): number { return helper(); }",
    );
    const defaultImport = lower(
      'default.ts',
      "import helper from './index.js'; export function use(): number { return helper(); }",
    );

    expect(emitIrModuleHaxe(index.module).path).toBe('flighthq/math/_Index.hx');
    expect(emitIrModuleHaxe(index.module).contents).toContain('class _Index');
    expect(emitIrModuleHaxe(consumer.module).contents).toContain('import flighthq.math._Index.helper;');
    expect(() => emitIrModuleHaxe(defaultImport.module)).toThrow('default imports require explicit Haxe mapping');
  });

  it('emits type-only imports and their references from one type-space identity', () => {
    const result = lower(
      'type-import.ts',
      "import type { sourceType as localType } from './types.js'; export type Alias = localType;",
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('import flighthq.math.Types.SourceType as LocalType;');
    expect(output).toContain('typedef Alias = LocalType;');
  });

  it('rejects module facades and emits normalized switch fallthrough', () => {
    const barrel = lower('barrel.ts', "export * from './other.js';");
    const fallthrough = lower(
      'switch.ts',
      'export function choose(a: number): number { switch (a) { case 1: case 2: return 2; default: return 0; } }',
    );
    const output = emitIrModuleHaxe(fallthrough.module).contents;

    expect(() => emitIrModuleHaxe(barrel.module)).toThrow('module-facade lowering');
    expect(output).toContain('case 1:\n        return 2;\n      case 2:\n        return 2;');
  });

  it('emits binding-sensitive switch fallthrough through an identity-safe state loop', () => {
    const result = lower(
      'switch-binding-state.ts',
      'function mark(): void {} export function choose(a: number): number { switch (a) { case 1: mark(); case 2: const local: number = a; return local; default: return 0; } }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('var switchFallthroughState:Float = -1;');
    expect(output).toContain('while ((switchFallthroughState >= 0))');
    expect(output.match(/final local/g)).toHaveLength(1);
  });

  it.each([
    [
      'assignment',
      'export function power(a: number, b: number): number { a **= b; return a; }',
      'operator **= requires Haxe semantic lowering',
    ],
    [
      'binary',
      'export function power(a: number, b: number): number { return a ** b; }',
      'operator ** requires Haxe semantic lowering',
    ],
    [
      'keyword unary',
      'export function type(a: number): string { return typeof a; }',
      'operator typeof requires Haxe semantic lowering',
    ],
  ])('refuses unsupported %s operators explicitly', (family, source, message) => {
    const result = lower(`${family.replaceAll(' ', '-')}-operator.ts`, source);

    expect(() => emitIrModuleHaxe(result.module)).toThrow(message);
  });

  it('emits contextual undefined as null but rejects unrepresentable undefined expressions', () => {
    const nullable = lower('nullable.ts', 'export function nullable(): string | null { return null; }');
    const undefinedNullable = lower(
      'undefined-nullable.ts',
      'export function undefinedNullable(): number | undefined { return undefined; }',
    );
    const undefinedValue = lower('missing.ts', 'export function missing(): undefined { return undefined; }');
    const explicitDefault = lower(
      'explicit-default.ts',
      'function fallback(value = 1): number { return value; } export function read(): number { return fallback((undefined as number | undefined)); }',
    );

    expect(emitIrModuleHaxe(nullable.module).contents).toContain(
      'static function nullable():Null<String> {\n    return null;',
    );
    expect(() => emitIrModuleHaxe(undefinedValue.module)).toThrow(
      'undefined expressions require Haxe nullability lowering',
    );
    expect(emitIrModuleHaxe(undefinedNullable.module).contents).toContain('return null;');
    expect(() => emitIrModuleHaxe(explicitDefault.module)).toThrow(
      'explicit undefined default arguments require Haxe omission lowering',
    );
  });

  it('emits a local binding named undefined without confusing it with the ambient value', () => {
    const result = lower(
      'local-undefined.ts',
      'export function read(value: number): number { const undefined: number = value; return undefined; }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('final undefined:Float = value;');
    expect(output).toContain('return undefined;');
  });

  it('uses binding identity to keep renamed declarations and references aligned', () => {
    const result = lower('rename.ts', 'export function read(): number { return read(); }');
    const declaration = result.module.declarations[0];
    if (declaration?.kind !== 'function') throw new Error('Expected function declaration');
    const renamed = {
      ...result.module,
      declarations: [{ ...declaration, binding: { ...declaration.binding, name: 'renamed' } }],
    };
    const output = emitIrModuleHaxe(renamed).contents;

    expect(output).toContain('static function renamed():Float');
    expect(output).toContain('return renamed();');
  });

  it('allocates collision-free Haxe names for shadowed and keyword-normalized bindings', () => {
    const result = lower(
      'collisions.ts',
      'export function choose(operator: number, operator_: number): number { { const operator: number = operator_; operator; } return operator + operator_; }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('static function choose(operator_:Float, operator__2:Float):Float');
    expect(output).toContain('final operator__3:Float = operator__2;');
    expect(output).toContain('operator__3;');
    expect(output).toContain('return (operator_ + operator__2);');
  });

  it('refuses public type collisions introduced by Haxe normalization', () => {
    const result = lower('type-collisions.ts', 'export type operator = number; export type operator_ = operator;');

    expect(() => emitIrModuleHaxe(result.module)).toThrow('public declarations share fixed Haxe target name Operator');
  });

  it('preserves public source spellings when Haxe normalization does not collide', () => {
    const result = lower(
      'value-spellings.ts',
      'export function fooBar(value: number): number { return value; } export function foo_bar(value: number): number { return value + 1; }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('static function fooBar(value:Float):Float');
    expect(output).toContain('static function foo_bar(value:Float):Float');
  });

  it('preserves final locals and abstract classes', () => {
    const result = lower(
      'base.ts',
      'export abstract class Base {} export function read(): number { const value: number = 1; return value; }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('abstract class Base');
    expect(output).toContain('final value:Float = 1;');
  });

  it('emits supported postfix operators from the closed target mapping', () => {
    const result = lower(
      'increment.ts',
      'export function increment(value: number): number { let result: number = value; return result++; }',
    );

    expect(emitIrModuleHaxe(result.module).contents).toContain('return result++;');
  });

  it('emits supported assignment, binary, and prefix operators from closed target mappings', () => {
    const result = lower(
      'operators.ts',
      'export function operators(left: number, right: number, disabled: boolean): boolean { let value: number = left; value += right; return value === right && !disabled; }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('value += right;');
    expect(output).toContain('return ((value == right) && ! disabled);');
  });

  it('emits only operators whose static domains preserve Haxe meaning', () => {
    const strings = lower(
      'string-operators.ts',
      'export function join(left: string, right: string): string { return left + right; }',
    );
    const mixed = lower(
      'mixed-operators.ts',
      'export function join(left: string, right: number): string { return left + right; }',
    );
    const loose = lower(
      'loose-equality.ts',
      'export function equal(left: number, right: number): boolean { return left == right; }',
    );

    expect(emitIrModuleHaxe(strings.module).contents).toContain('return (left + right);');
    expect(() => emitIrModuleHaxe(mixed.module)).toThrow(
      'operator + on string and number requires Haxe type-directed lowering',
    );
    expect(() => emitIrModuleHaxe(loose.module)).toThrow(
      'operator == on number and number requires Haxe type-directed lowering',
    );
  });

  it('emits completion-preserving async functions through the Haxe task runtime ABI', () => {
    const result = lower(
      'task.ts',
      'export async function read(input: Promise<number>): Promise<number> { const value = await input; return await Promise.resolve(value); }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('return new flighthq._internal._Promise(function(resolveTask, rejectTask)');
    expect(output).toContain('flighthq._internal._Promise.resolve(input).then(');
    expect(output).toContain('value = awaitValue;');
    expect(output).toContain('resolveTask(awaitValue_2);');
    expect(output).toContain('rejectTask(awaitError);');
    expect(output).not.toContain('await ');
  });

  it('emits completion-preserving async methods and closures through the same task plan', () => {
    const result = lower(
      'task-values.ts',
      `
        export class Reader {
          async read(input: Promise<number>): Promise<number> { return await input; }
        }
        export const read = async (input: Promise<number>): Promise<number> => await input;
      `,
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output.match(/return new flighthq\._internal\._Promise\(/gu)).toHaveLength(2);
    expect(output.match(/flighthq\._internal\._Promise\.resolve\(input\)\.then\(/gu)).toHaveLength(2);
    expect(output).not.toContain('await ');
  });

  it('converts invalid task-runtime configuration to a tagged backend failure', () => {
    const result = lower('task-runtime.ts', 'export async function read(): Promise<number> { return 1; }');

    try {
      emitIrModuleHaxe(result.module, { runtimeModule: 'invalid-module' });
      expect.unreachable('Expected Haxe emission to fail');
    } catch (error) {
      expect(isBackendEmissionFailure(error)).toBe(true);
      expect(error).toMatchObject({
        backend: 'haxe',
        code: 'unsupported-ir',
        kind: 'backend-emission',
        packageName: '@flighthq/math',
        source: 'packages/math/src/task-runtime.ts',
      });
    }
  });

  it('returns a tagged emission failure', () => {
    const result = lower(
      'unsupported.ts',
      'export async function read(value: boolean): Promise<number> { if (value) return 1; return 0; }',
    );

    try {
      emitIrModuleHaxe(result.module);
      expect.unreachable('Expected Haxe emission to fail');
    } catch (error) {
      expect(isBackendEmissionFailure(error)).toBe(true);
      expect(error).toMatchObject({
        backend: 'haxe',
        code: 'unsupported-ir',
        kind: 'backend-emission',
        name: 'BackendEmissionError',
        packageName: '@flighthq/math',
        source: 'packages/math/src/unsupported.ts',
      });
    }
  });

  it('emits nested labeled exits through Haxe completion state', () => {
    const result = lower(
      'labeled-flow.ts',
      'export function scan(limit: number): number { let count = 0; outer: while (count < limit) { while (true) { count += 1; if (count < limit) continue outer; break outer; } } done: { if (count < 0) break done; } return count; }',
    );
    const labeledSwitch = lower(
      'labeled-switch.ts',
      'export function scan(value: number): void { done: switch (value) { case 1: break done; } }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('var outerControlFlowState:Int = 0;');
    expect(output).toContain('outerControlFlowState = 2;');
    expect(output).toContain('outerControlFlowState = 1;');
    expect(output).toContain('if (outerControlFlowState == 2) { outerControlFlowState = 0; continue; }');
    expect(output).toContain('var doneControlFlowState:Int = 0;');
    expect(output).toContain('do {\n      if ((count < 0))');
    expect(() => emitIrModuleHaxe(labeledSwitch.module)).toThrow(
      'labeled switch done requires Haxe switch completion lowering',
    );
  });

  it('emits structurally flattened generic interface inheritance', () => {
    const result = lower(
      'interface-inheritance.ts',
      'interface Base<Value> { value: Value; } export interface Child extends Base<number> { own: boolean; }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('typedef Child = { value:Float, own:Bool };');
  });

  it('emits an implemented shape as a nominal interface and leaves an unimplemented one structural', () => {
    // Haxe `implements` names a nominal type, so a shape a class implements cannot stay a typedef.
    // A shape nothing implements does stay one, because that is the idiomatic structural form.
    const implemented = lower(
      'nominal.ts',
      'export interface Advancer { step: number; advance(by: number): number; } export class Counter implements Advancer { step: number = 1; advance(by: number): number { return by + this.step; } }',
    );
    const structural = lower('shape.ts', 'export interface Point { x: number; y: number; }');

    const nominal = emitIrModuleHaxe(implemented.module).contents;
    expect(nominal).toContain('interface Advancer {');
    expect(nominal).toContain('  public var step:Float;');
    expect(nominal).toContain('  public function advance(by:Float):Float;');
    expect(nominal).toContain('class Counter implements Advancer {');
    expect(emitIrModuleHaxe(structural.module).contents).toContain('typedef Point = { x:Float, y:Float };');
  });

  it('refuses a class implementing an interface it cannot name in this module', () => {
    const external = lower(
      'external.ts',
      "import type { Advancer } from './advancer.js'; export class Counter implements Advancer { step: number = 1; }",
    );

    expect(() => emitIrModuleHaxe(external.module)).toThrow('implements an interface declared outside this module');
  });

  it('compares against a single absent value directly, and refuses where the source admits both', () => {
    // Haxe has one absent value, so `x == null` says exactly what `x === undefined` says when the
    // operand cannot also be null. When it can be both, the two comparisons differ and Haxe cannot
    // tell them apart, so the difference has to be lowered rather than emitted.
    const single = lower(
      'single.ts',
      'export function widen(value: number | undefined, fallback: number): number { if (value === undefined) return fallback; return value; }',
    );
    const both = lower(
      'both.ts',
      'export function widen(value: number | null | undefined, fallback: number): number { if (value === undefined) return fallback; return fallback; }',
    );

    const singleOutput = emitIrModuleHaxe(single.module).contents;
    expect(singleOutput).toContain('if ((value == null)) {');
    // Narrowing proved the value present, so it is returned directly: `Null<T>` exists to unify
    // with `T`, and the proof guarantees any runtime check that unification inserts will pass.
    expect(singleOutput).toContain('return value;');
    // The type refuses before the comparison does, which is the earlier and better place for it:
    // a type Haxe cannot spell is a refusal about the signature, not about one operator.
    expect(() => emitIrModuleHaxe(both.module)).toThrow(
      'types containing both null and undefined require distinct Haxe sentinels',
    );
  });

  it('narrows a computed array index to Int, and leaves an integer literal alone', () => {
    // Haxe indexes arrays with `Int` while the neutral numeric domain has only `number`, so every
    // index arrives as `Float`. Emitting it directly produced Haxe that does not compile, which
    // pinning bytes cannot catch.
    const result = lower(
      'array-index.ts',
      'export function at(values: number[], index: number): number { return values[index] ?? values[0] ?? 0; }',
    );
    const output = emitIrModuleHaxe(result.module).contents;

    expect(output).toContain('values[Std.int(index)]');
    expect(output).toContain('values[0]');
    expect(output).not.toContain('Std.int(0)');
  });
});
