// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mathExtended.ts#MathExtended. Do not edit.
#pragma once
#include <cmath>
#include <cstdint>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double circle_area(double radius) {
  return ((flight::pi * radius) * radius);
}

inline double hypotenuse(double a, double b) {
  return std::sqrt(((a * a) + (b * b)));
}

inline double ceil_divide(double numerator, double denominator) {
  return std::ceil((numerator / denominator));
}

inline double degrees_to_radians(double degrees) {
  return ((degrees * flight::pi) / 180.0);
}

inline double absolute_value(double value) {
  return std::abs(value);
}

} // namespace flighthq_golden
