// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mathMinMax.ts#MathMinMax. Do not edit.
package flighthq.golden;

function minimum(a:Float, b:Float):Float {
  return Math.min(a, b);
}

function maximum(a:Float, b:Float):Float {
  return Math.max(a, b);
}

function clamp(value:Float, low:Float, high:Float):Float {
  return Math.max(low, Math.min(value, high));
}

function absDistance(a:Float, b:Float):Float {
  return Math.abs((a - b));
}
