// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/cStyleForEmission.ts#CStyleForEmission. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double total(double limit) {
  double sum = 0.0;
  {
    double index = 0.0;
    while ((index < limit)) {
      {
        sum += index;
      }
      index += 1.0;
    }
  }
  return sum;
}

} // namespace flighthq_golden
