// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayConcat.ts#ArrayConcat. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline flight::Array<double> merge_arrays(flight::Array<double> a, flight::Array<double> b) {
  return a.concat(b);
}

inline flight::Array<double> append_one(flight::Array<double> values, double extra) {
  return values.concat(flight::Array{extra});
}

} // namespace flighthq_golden
