// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayTransform.ts#ArrayTransform. Do not edit.
package flighthq.golden;

function doubleAll(values:Array<Float>):Array<Float> {
  return values.map(function(v:Float) return (v * 2));
}

function filterPositive(values:Array<Float>):Array<Float> {
  return values.filter(function(v:Float) return (v > 0));
}

function sumAll(values:Array<Float>):Float {
  return Lambda.fold(values, function(v:Float, acc:Float) return (acc + v), 0);
}

function allPositive(values:Array<Float>):Bool {
  return Lambda.foreach(values, function(v:Float) return (v > 0));
}

function hasNegative(values:Array<Float>):Bool {
  return Lambda.exists(values, function(v:Float) return (v < 0));
}
