// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/genericFunction.ts#GenericFunction. Do not edit.
#pragma once
#include <tuple>
#include <vector>

namespace flighthq_golden {

template <typename T>
T identity(T value) {
  return value;
}

template <typename T>
T first_element(std::vector<T> items) {
  return items[static_cast<size_t>(0.0)];
}

template <typename A, typename B>
std::tuple<A, B> pair(A a, B b) {
  return std::make_tuple(a, b);
}

} // namespace flighthq_golden
