// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/genericFunction.ts#GenericFunction. Do not edit.
#pragma once
#include <tuple>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

template <typename T>
inline T identity(T value) {
  return value;
}

template <typename T>
inline T first_element(flight::Array<T> items) {
  return items.element(0.0);
}

template <typename A, typename B>
inline std::tuple<A, B> pair(A a, B b) {
  return std::make_tuple(a, b);
}

} // namespace flighthq_golden
