// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayForOfProduct.ts#ArrayForOfProduct. Do not edit.
#pragma once
#include <cmath>
#include <cstdint>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double product(flight::Array<double> values) {
  double result = 1.0;
  for (auto value : values) {
    result *= value;
  }
  return result;
}

inline double max(flight::Array<double> values) {
  double best = values.element(0.0);
  for (auto value : values) {
    if ((value > best)) {
      best = value;
    }
  }
  return best;
}

inline double count_positive(flight::Array<double> values) {
  double count = 0.0;
  for (auto value : values) {
    if ((value > 0.0)) {
      count += 1.0;
    }
  }
  return count;
}

inline double sum_absolute(flight::Array<double> values) {
  double total = 0.0;
  for (auto value : values) {
    total += std::abs(value);
  }
  return total;
}

} // namespace flighthq_golden
