// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/catchFinallyAwait.ts#CatchFinallyAwait. Do not edit.
package flighthq.golden;

class CatchFinallyAwait {
  public static function attempt(task:flighthq._internal._Promise<Float>, log:Array<Float>):flighthq._internal._Promise<Float> {
    return new flighthq._internal._Promise(function(resolveTask, rejectTask) {
      try {
        var result:Float = 0;
        var taskJoin = function() {
          try {
            resolveTask(result);
            return;
          } catch (taskError_3:Dynamic) {
            rejectTask(taskError_3);
          }
        };
        var cleanupValue:Dynamic = null;
        var taskCleanup = function() {
          try {
            log.push(result);
            taskJoin();
            return;
          } catch (taskError_2:Dynamic) {
            rejectTask(taskError_2);
          }
        };
        var taskRejected = function(taskRejection:Dynamic) {
          try {
            log.push(result);
          } catch (taskError_4:Dynamic) {
            rejectTask(taskError_4);
          }
          rejectTask(taskRejection);
        };
        try {
          var taskJoin_2 = function() {
            try {
              taskCleanup();
              return;
            } catch (taskError_6:Dynamic) {
              taskRejected(taskError_6);
              return;
            }
          };
          var taskRejected_2 = function(taskRejection_2:Dynamic) {
            try {
              result = 1;
              taskJoin_2();
              return;
            } catch (taskError_7:Dynamic) {
              taskRejected(taskError_7);
              return;
            }
          };
          try {
            flighthq._internal._Promise.resolve(task).then(
              function(awaitValue) {
                result = awaitValue;
                try {
                  taskJoin_2();
                  return;
                } catch (taskError_9:Dynamic) {
                  taskRejected_2(taskError_9);
                  return;
                }
              },
              function(awaitError) {
                taskRejected_2(awaitError);
                return;
              }
            );
            return;
          } catch (taskError_8:Dynamic) {
            taskRejected_2(taskError_8);
            return;
          }
          return;
        } catch (taskError_5:Dynamic) {
          taskRejected(taskError_5);
          return;
        }
        return;
      } catch (taskError:Dynamic) {
        rejectTask(taskError);
      }
    });
  }
}
