// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/catchFinallyAwait.ts#CatchFinallyAwait. Do not edit.
package flighthq.golden;

class CatchFinallyAwait {
  public static function attempt(task:flighthq._internal._Promise<Float>, log:Array<Float>):flighthq._internal._Promise<Float> {
    return new flighthq._internal._Promise(function(resolveTask, rejectTask) {
      try {
        var result:Float = 0;
        var taskJoin = function() {
          try {
            resolveTask(result);
            return;
          } catch (taskError_3:Dynamic) {
            rejectTask(taskError_3);
          }
        };
        var cleanupValue;
        var taskCleanup = function() {
          try {
            log.push(result);
            taskJoin();
            return;
          } catch (taskError_2:Dynamic) {
            rejectTask(taskError_2);
          }
        };
        try {
          var taskJoin_2 = function() {
            try {
              taskCleanup();
              return;
            } catch (taskError_5:Dynamic) {
              try {
                log.push(result);
              } catch (taskError_6:Dynamic) {
                rejectTask(taskError_6);
              }
              rejectTask(taskError_5);
            }
          };
          try {
            flighthq._internal._Promise.resolve(task).then(
              function(awaitValue) {
                result = awaitValue;
                try {
                  taskJoin_2();
                  return;
                } catch (taskError_8:Dynamic) {
                  try {
                    result = 1;
                    taskJoin_2();
                    return;
                  } catch (taskError_9:Dynamic) {
                    try {
                      log.push(result);
                    } catch (taskError_10:Dynamic) {
                      rejectTask(taskError_10);
                    }
                    rejectTask(taskError_9);
                  }
                }
              },
              function(awaitError) {
                try {
                  result = 1;
                  taskJoin_2();
                  return;
                } catch (taskError_11:Dynamic) {
                  try {
                    log.push(result);
                  } catch (taskError_12:Dynamic) {
                    rejectTask(taskError_12);
                  }
                  rejectTask(taskError_11);
                }
              }
            );
            return;
          } catch (taskError_7:Dynamic) {
            try {
              result = 1;
              taskJoin_2();
              return;
            } catch (taskError_13:Dynamic) {
              try {
                log.push(result);
              } catch (taskError_14:Dynamic) {
                rejectTask(taskError_14);
              }
              rejectTask(taskError_13);
            }
          }
          return;
        } catch (taskError_4:Dynamic) {
          try {
            log.push(result);
          } catch (taskError_15:Dynamic) {
            rejectTask(taskError_15);
          }
          rejectTask(taskError_4);
        }
        return;
      } catch (taskError:Dynamic) {
        rejectTask(taskError);
      }
    });
  }
}
