// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedAccess.ts#NestedAccess. Do not edit.
#pragma once

namespace flighthq_golden {

struct Point {
  double x;
  double y;
};

struct Rect {
  Point origin;
  Point size;
};

double area(Rect rect) {
  return (rect.size.x * rect.size.y);
}

Point translate(Rect rect, double dx, double dy) {
  return {.x = (rect.origin.x + dx), .y = (rect.origin.y + dy)};
}

double diagonal(Rect rect) {
  const double w = rect.size.x;
  const double h = rect.size.y;
  return std::sqrt(((w * w) + (h * h)));
}

} // namespace flighthq_golden
