// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/booleanLogic.ts#BooleanLogic. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline bool both(bool a, bool b) {
  return (a && b);
}

inline bool either(bool a, bool b) {
  return (a || b);
}

inline bool negate(bool value) {
  return !value;
}

inline bool in_range(double value, double min, double max) {
  return ((value >= min) && (value <= max));
}

inline double clamped_sign(double value) {
  if ((value > 0.0)) {
    return 1.0;
  }
  else {
    if ((value < 0.0)) {
      return -1.0;
    }
  }
  return 0.0;
}

} // namespace flighthq_golden
