// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/booleanLogic.ts#BooleanLogic. Do not edit.
#pragma once

namespace flighthq_golden {

bool both(bool a, bool b) {
  return (a && b);
}

bool either(bool a, bool b) {
  return (a || b);
}

bool negate(bool value) {
  return !value;
}

bool in_range(double value, double min, double max) {
  return ((value >= min) && (value <= max));
}

double clamped_sign(double value) {
  if ((value > 0.0)) {
    return 1.0;
  }
  else {
    if ((value < 0.0)) {
      return -1.0;
    }
  }
  return 0.0;
}

} // namespace flighthq_golden
