// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/provider.ts#Provider. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Info;

struct Info : public flight::ReferenceEnabled {
  double value;
};

using InfoAlias = flight::Ref<Info>;

using NestedAlias = InfoAlias;

} // namespace flighthq_golden
