// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringConcat.ts#StringConcat. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

std::string greet_user(std::string name) {
  return "Hello, " + name + "!";
}

std::string format_pair(std::string key, double value) {
  return key + "=" + value.to_string();
}

std::string repeat(std::string text, double count) {
  std::string result = "";
  {
    double i = 0.0;
    while ((i < count)) {
      {
        result += text;
      }
      i += 1.0;
    }
  }
  return result;
}

} // namespace flighthq_golden
