// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/shapes.ts#Shapes. Do not edit.
#pragma once

namespace flighthq_golden {

struct Range {
  double max;
  double min;
};

enum class mode {
  Fast = 1.0,
  Safe = 2.0,
  Strict = 8.0,
  Debug = 9.0,
};

Range widen(Range range, double by) {
  return {.max = (range.max + by), .min = (range.min - by)};
}

} // namespace flighthq_golden
