// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringTransform.ts#StringTransform. Do not edit.
package flighthq.golden;

function findFirst(text:String, search:String):Float {
  return text.indexOf(search);
}

function findLast(text:String, search:String):Float {
  return text.lastIndexOf(search);
}

function countTokens(text:String, delimiter:String):Float {
  final parts:Array<String> = text.split(delimiter);
  return parts.length;
}

function splitAndJoin(text:String, delimiter:String, joiner:String):String {
  final parts:Array<String> = text.split(delimiter);
  return parts.join(joiner);
}
