// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringTemplate.ts#StringTemplate. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

std::string greet(std::string name) {
  return std::string("Hello, ") + std::to_string(name) + std::string("!");
}

std::string format_coord(double x, double y) {
  return std::string("(") + std::to_string(x) + std::string(", ") + std::to_string(y) + std::string(")");
}

std::string wrap_tag(std::string tag, std::string content) {
  return std::string("<") + std::to_string(tag) + std::string(">") + std::to_string(content) + std::string("</") + std::to_string(tag) + std::string(">");
}

std::string repeat_line(std::string text, double count) {
  std::string result = "";
  {
    double i = 0.0;
    while ((i < count)) {
      {
        result = std::string("") + std::to_string(result) + std::string("") + std::to_string(text) + std::string("\n");
      }
      i += 1.0;
    }
  }
  return result;
}

} // namespace flighthq_golden
