// Generated by @flighthq/tool-compiler. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct RuntimeTypes {
  pub values: std::collections::HashMap<String, f64>,
  pub task: FlightTask<f64>,
  pub bytes: Vec<u8>,
}
