// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/optionalCoalesce.ts#OptionalCoalesce. Do not edit.
package flighthq.golden;

typedef Holder = { value:Float };

class OptionalCoalesce {
  public static function read(holder:Null<Holder>):Float {
    return holder?.value ?? 0;
  }
}
