// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringTransform.ts#StringTransform. Do not edit.
#pragma once
#include <string>
#include <vector>

namespace flighthq_golden {

double find_first(std::string text, std::string search) {
  return text.find(search);
}

double find_last(std::string text, std::string search) {
  return text.last_index_of(search);
}

double count_tokens(std::string text, std::string delimiter) {
  const std::vector<std::string> parts = text.split(delimiter);
  return static_cast<double>(parts.size());
}

std::string split_and_join(std::string text, std::string delimiter, std::string joiner) {
  const std::vector<std::string> parts = text.split(delimiter);
  return parts.join(joiner);
}

} // namespace flighthq_golden
