// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/erasedCallableReturnDomain.ts#ErasedCallableReturnDomain. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Point = { x:Float };

typedef NumberSlot = Dynamic;

typedef TextSlot = Null<()->String>;

typedef FlagSlot = Null<()->Bool>;

typedef PointSlot = Null<()->Point>;

function takeNumber(value:NumberSlot):Float {
  return (Std.isOfType(value, String) ? 0 : 1);
}

function takeText(value:TextSlot):Float {
  return (flighthq._internal._Js.strictEqual(flighthq._internal._Js.typeOf(value), "undefined") ? 0 : 1);
}

function takeFlag(value:FlagSlot):Float {
  return (flighthq._internal._Js.strictEqual(flighthq._internal._Js.typeOf(value), "undefined") ? 0 : 1);
}

function takePoint(value:PointSlot):Float {
  return (flighthq._internal._Js.strictEqual(flighthq._internal._Js.typeOf(value), "undefined") ? 0 : 1);
}

function passNumber(handler:()->Dynamic):Float {
  return takeNumber((cast handler : NumberSlot));
}

function passText(handler:()->Dynamic):Float {
  return takeText((cast handler : TextSlot));
}

function passFlag(handler:()->Dynamic):Float {
  return takeFlag((cast handler : FlagSlot));
}

function passPoint(handler:()->Dynamic):Float {
  return takePoint((cast handler : PointSlot));
}
