// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedArray.ts#NestedArray. Do not edit.
package flighthq.golden;

function sumRow(grid:Array<Array<Float>>, row:Float):Float {
  var total:Float = 0;
  for (value in grid[Std.int(row)]) {
    total += value;
  }
  return total;
}

function flatten(grid:Array<Array<Float>>):Array<Float> {
  final result:Array<Float> = [];
  for (row in grid) {
    for (value in row) {
      result.push(value);
    }
  }
  return result;
}

function transpose(grid:Array<Array<Float>>):Array<Array<Float>> {
  final rows:Float = grid.length;
  final cols:Float = grid[0].length;
  final result:Array<Array<Float>> = [];
  {
    var c:Float = 0;
    while (c < cols) {
      {
        final row:Array<Float> = [];
        {
          var r:Float = 0;
          while (r < rows) {
            {
              row.push(grid[Std.int(r)][Std.int(c)]);
            }
            r += 1;
          }
        }
        result.push(row);
      }
      c += 1;
    }
  }
  return result;
}
