// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/moduleImports.ts#ModuleImports. Do not edit.
#pragma once
#include <flight/runtime.hpp>

#include "helper.hpp"

namespace flighthq_golden {

inline double use(double value) {
  return helper(value);
}

} // namespace flighthq_golden
