// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/templateExpression.ts#TemplateExpression. Do not edit.
#![forbid(unsafe_code)]

pub fn greet(name: String) -> String {
  return format!("Hello, {}!", name);
}

pub fn format_coordinate(x: f64, y: f64) -> String {
  return format!("({}, {})", x, y);
}

pub fn multi_line(title: String, body: String) -> String {
  return format!("Title: {}\nBody: {}", title, body);
}

pub fn nested(a: f64, b: f64) -> String {
  return format!("sum={}, product={}", (a + b), (a * b));
}
