// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/classShape.ts#ClassShape. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct Counter {
    step: f64,
    pub label: String,
}

impl Counter {
  pub fn new() -> Self {
    Self {
      step: 1.0,
      label: "counter".to_owned(),
    }
  }

  pub fn advance(&self, by: f64) -> f64 {
    return (by + self.step);
  }
}
