// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/variableForInHoisting.ts#VariableForInHoisting. Do not edit.
package flighthq.golden;

typedef Values = { value:Float };

class VariableForInHoisting {
  public static function selectFirstKey(values:Values):String {
    var key;
    for (variableHoistingIterationValue in Reflect.fields(values)) {
      key = variableHoistingIterationValue;
      return key;
    }
    return "";
  }
}
