// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/dualSentinelUnion.ts#DualSentinelUnion. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone)]
pub enum AnonymousUnion {
  String(String),
  Null,
  Undefined,
}

#[derive(Clone)]
pub enum AnonymousUnion2 {
  F64(f64),
  Null,
  Undefined,
}

pub fn resolve(value: AnonymousUnion) -> String {
  if matches!(&value, AnonymousUnion::Null) {
    return "null".to_owned();
  }
  if matches!(&value, AnonymousUnion::Undefined) {
    return "undefined".to_owned();
  }
  return match &value { AnonymousUnion::String(value) => value.clone(), _ => unreachable!() };
}

pub fn coerce(value: AnonymousUnion2, fallback: f64) -> f64 {
  if matches!(&value, AnonymousUnion2::Null) || matches!(&value, AnonymousUnion2::Undefined) {
    return fallback;
  }
  return match &value { AnonymousUnion2::F64(value) => value.clone(), _ => unreachable!() };
}

pub fn assign_dual(flag: f64) -> AnonymousUnion {
  if flag == 0.0 {
    return AnonymousUnion::Null;
  }
  if flag == 1.0 {
    return AnonymousUnion::Undefined;
  }
  return AnonymousUnion::String("present".to_owned());
}
