// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/defaultParameter.ts#DefaultParameter. Do not edit.
#![forbid(unsafe_code)]

pub fn scale(value: f64, factor: Option<f64>) -> f64 {
  let factor = factor.unwrap_or_else(|| 2.0);
  return (value * factor);
}
