// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringCharAt.ts#StringCharAt. Do not edit.
#![forbid(unsafe_code)]

pub fn first_char(text: String) -> String {
  return text.chars().nth(0.0 as usize).map(|c| c.to_string()).unwrap_or_default();
}

pub fn last_char(text: String) -> String {
  return text.chars().nth(((text.len() as f64) - 1.0) as usize).map(|c| c.to_string()).unwrap_or_default();
}

pub fn is_upper_first(text: String) -> bool {
  let first: String = text.chars().nth(0.0 as usize).map(|c| c.to_string()).unwrap_or_default();
  return first == first.to_uppercase();
}
