// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/contextualUnionRemapShapes.ts#ContextualUnionRemapShapes. Do not edit.
#pragma once
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Circle;
struct Aabb;
struct Obb;
struct Capsule;

struct Circle : public flight::ReferenceEnabled {
  double radius;
};

struct Aabb : public flight::ReferenceEnabled {
  double min;
  double max;
};

struct Obb : public flight::ReferenceEnabled {
  double center;
  double rotation;
};

struct Capsule : public flight::ReferenceEnabled {
  double start;
  double end;
  double radius;
};

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_RADIUS_KIND_760AA12BB25EB337
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_RADIUS_KIND_760AA12BB25EB337
struct radius_kind_760aa12bb25eb337 : public flight::ReferenceEnabled {
  double radius;
  flight::String kind;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_RADIUS_KIND_760AA12BB25EB337

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_MIN_MAX_KIND_72E8996A00A70E06
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_MIN_MAX_KIND_72E8996A00A70E06
struct min_max_kind_72e8996a00a70e06 : public flight::ReferenceEnabled {
  double min;
  double max;
  flight::String kind;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_MIN_MAX_KIND_72E8996A00A70E06

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_CENTER_ROTATION_KIND_0EE0F73E01180422
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_CENTER_ROTATION_KIND_0EE0F73E01180422
struct center_rotation_kind_0ee0f73e01180422 : public flight::ReferenceEnabled {
  double center;
  double rotation;
  flight::String kind;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_CENTER_ROTATION_KIND_0EE0F73E01180422

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_START_END_RADIUS_KIND_F5A7726390EDCFD7
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_START_END_RADIUS_KIND_F5A7726390EDCFD7
struct start_end_radius_kind_f5a7726390edcfd7 : public flight::ReferenceEnabled {
  double start;
  double end;
  double radius;
  flight::String kind;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_GOLDEN_START_END_RADIUS_KIND_F5A7726390EDCFD7

using Shape = std::variant<flight::Ref<center_rotation_kind_0ee0f73e01180422>, flight::Ref<radius_kind_760aa12bb25eb337>, flight::Ref<min_max_kind_72e8996a00a70e06>, flight::Ref<start_end_radius_kind_f5a7726390edcfd7>>;

} // namespace flighthq_golden
