// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/earlyExit.ts#EarlyExit. Do not edit.
#![forbid(unsafe_code)]

pub fn abs(value: f64) -> f64 {
  if value < 0.0 {
    return -value;
  }
  return value;
}

pub fn sign(value: f64) -> f64 {
  if value > 0.0 {
    return 1.0;
  }
  if value < 0.0 {
    return -1.0;
  }
  return 0.0;
}

pub fn classify(score: f64) -> String {
  if score >= 90.0 {
    return "excellent".to_owned();
  }
  if score >= 70.0 {
    return "good".to_owned();
  }
  if score >= 50.0 {
    return "average".to_owned();
  }
  return "poor".to_owned();
}

pub fn first_positive(a: f64, b: f64, c: f64) -> f64 {
  if a > 0.0 {
    return a;
  }
  if b > 0.0 {
    return b;
  }
  if c > 0.0 {
    return c;
  }
  return 0.0;
}
