// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayReduce.ts#ArrayReduce. Do not edit.
#![forbid(unsafe_code)]

pub fn sum(values: Vec<f64>) -> f64 {
  return values.into_iter().fold(0.0, |acc, v| acc + v);
}

pub fn product(values: Vec<f64>) -> f64 {
  return values.into_iter().fold(1.0, |acc, v| acc * v);
}

pub fn max_value(values: Vec<f64>) -> f64 {
  let mut best: f64 = 0.0;
  for v in values {
    if v > best {
      best = v;
    }
  }
  return best;
}

pub fn count_above(values: Vec<f64>, threshold: f64) -> f64 {
  return values.into_iter().fold(0.0, |count, v| if (v > threshold) { (count + 1.0) } else { count });
}
