// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/abstractClass.ts#AbstractClass. Do not edit.
package flighthq.golden;

abstract class Shape {
  public abstract function area():Float;

  public function describe():Float {
    return this.area();
  }
}

class Square extends Shape {
  private var side:Float;

  public function new(side:Float) {
    super();
    this.side = side;
  }

  public override function area():Float {
    return (this.side * this.side);
  }
}
