// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/awaitConditionAwait.ts#AwaitConditionAwait. Do not edit.
#![forbid(unsafe_code)]

use flight_runtime::FlightTask;

pub async fn decide(task: FlightTask<bool>) -> f64 {
  let mut total: f64 = 0.0;
  {
    let await_value = task.await;
    if await_value {
      total = 1.0;
    }
    else {
      total = 2.0;
    }
  }
  return total;
}
