// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mathMembers.ts#MathMembers. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double widest(double first, double second) {
  return flight::maximum(first, std::abs(second));
}

} // namespace flighthq_golden
