// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedControl.ts#NestedControl. Do not edit.
#![forbid(unsafe_code)]

pub fn sum_matrix(rows: f64, cols: f64) -> f64 {
  let mut total: f64 = 0.0;
  {
    let mut r: f64 = 0.0;
    while r < rows {
      {
        {
          let mut c: f64 = 0.0;
          while c < cols {
            {
              total += (r * cols) + c;
            }
            c += 1.0;
          }
        }
      }
      r += 1.0;
    }
  }
  return total;
}

pub fn classify_range(value: f64) -> String {
  if value < 0.0 {
    return "negative".to_owned();
  }
  else {
    if value == 0.0 {
      return "zero".to_owned();
    }
    else {
      if value < 10.0 {
        return "small".to_owned();
      }
      else {
        if value < 100.0 {
          return "medium".to_owned();
        }
        else {
          return "large".to_owned();
        }
      }
    }
  }
}

pub fn count_divisible(limit: f64, divisor: f64) -> f64 {
  let mut count: f64 = 0.0;
  let mut i: f64 = 1.0;
  while i <= limit {
    if (i % divisor) == 0.0 {
      count += 1.0;
    }
    i += 1.0;
  }
  return count;
}
