// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringBuild.ts#StringBuild. Do not edit.
package flighthq.golden;

function reverse(text:String):String {
  var result:String = "";
  {
    var i:Float = text.length - 1;
    while (i >= 0) {
      {
        result = (result + text.charAt(Std.int(i)));
      }
      i -= 1;
    }
  }
  return result;
}

function countChar(text:String, ch:String):Float {
  var count:Float = 0;
  {
    var i:Float = 0;
    while (i < text.length) {
      {
        if (text.charAt(Std.int(i)) == ch) {
          count = (count + 1);
        }
      }
      i += 1;
    }
  }
  return count;
}

function truncate(text:String, maxLength:Float):String {
  if (text.length <= maxLength) {
    return text;
  }
  return text.substring(0, Std.int(maxLength)) + "...";
}
