// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nullishPresenceTest.ts#NullishPresenceTest. Do not edit.
#pragma once
#include <flight/record.hpp>
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline bool compares_equals_string(flight::String value) {
  return false;
}

inline bool compares_indexed(flight::Record<flight::String, flight::String> values, flight::String key) {
  return values.get(key).has_value();
}

inline bool compares_number(double flag) {
  return true;
}

inline bool compares_nullable(std::optional<flight::String> value) {
  return value.has_value();
}

inline bool compares_string(flight::String value) {
  return true;
}

inline bool compares_string_loose(flight::String value) {
  return true;
}

} // namespace flighthq_golden
