// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringRepeat.ts#StringRepeat. Do not edit.
#pragma once
#include <string>
#include <vector>

namespace flighthq_golden {

std::string repeat_string(std::string text, double count) {
  std::string result = "";
  {
    double i = 0.0;
    while ((i < count)) {
      {
        result = result + text;
      }
      i += 1.0;
    }
  }
  return result;
}

std::string join_with_separator(std::vector<std::string> items, std::string separator) {
  if ((static_cast<double>(items.size()) == 0.0)) {
    return "";
  }
  std::string result = items[static_cast<size_t>(0.0)];
  {
    double i = 1.0;
    while ((i < static_cast<double>(items.size()))) {
      {
        result = result + separator + items[static_cast<size_t>(i)];
      }
      i += 1.0;
    }
  }
  return result;
}

std::string pad_left(std::string text, double width, std::string fill) {
  std::string result = text;
  while ((static_cast<double>(result.size()) < width)) {
    result = fill + result;
  }
  return result;
}

std::string surround_with(std::string text, std::string left, std::string right) {
  return left + text + right;
}

} // namespace flighthq_golden
