// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/optionalAccumulator.ts#OptionalAccumulator. Do not edit.
package flighthq.golden;

typedef Item = { name:String, count:Float };

function busiestCount(items:Array<Item>):Float {
  var best:Null<Item> = js.Syntax.code("undefined");
  for (item in items) {
    if (js.Syntax.strictEq(best, js.Syntax.code("undefined")) || (item.count > cast(best).count)) {
      (best = item);
    }
  }
  return js.Syntax.strictEq(best, js.Syntax.code("undefined")) ? 0 : cast(best).count;
}
