// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/optionalAccumulator.ts#OptionalAccumulator. Do not edit.
package flighthq.golden;

typedef Item = { name:String, count:Float };

function busiestCount(items:Array<Item>):Float {
  var best:Null<Item> = null;
  for (item in items) {
    if ((best == null) || (item.count > cast(best).count)) {
      best = item;
    }
  }
  return (best == null) ? 0 : cast(best).count;
}
