// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayBinding.ts#ArrayBinding. Do not edit.
package flighthq.golden;

class ArrayBinding {
  public static function select(values:Array<Dynamic>):Float {
    final arrayPatternValue:Array<Dynamic> = values;
    final third:Float = arrayPatternValue[2];
    return third;
  }

  public static function selectDefault(values:Array<Dynamic>):Float {
    final arrayPatternValue:Array<Dynamic> = values;
    final first:Float = (arrayPatternValue[0] ?? 4);
    return first;
  }

  public static function selectRest(values:Array<Dynamic>):Array<Float> {
    final arrayPatternValue:Array<Dynamic> = values;
    final rest:Array<Float> = arrayPatternValue.slice(1);
    return rest;
  }

  public static function createValues():Array<Dynamic> {
    final values:Array<Dynamic> = [1, null];
    return values;
  }
}
