// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayBinding.ts#ArrayBinding. Do not edit.
package flighthq.golden;

class ArrayBinding {
  public static function select(values:Array<Float>):Float {
    final arrayPatternValue:Array<Float> = values;
    final third:Float = arrayPatternValue[2];
    return third;
  }
}
