// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/generics.ts#Generics. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct Pair<Left: Clone, Right: Clone> {
  pub left: Left,
  pub right: Right,
}

pub fn identity<Value: Clone>(value: Value) -> Value {
  return value;
}
