// Generated by @flighthq/tool-compiler. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct Pair<Left, Right> {
  pub left: Left,
  pub right: Right,
}

pub fn identity<Value>(value: Value) -> Value {
  return value;
}
