// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/optionalMember.ts#OptionalMember. Do not edit.
#pragma once
#include <optional>
#include <string>

namespace flighthq_golden {

struct options {
  double retries;
  std::string label;
};

std::string summarize(options options) {
  const double retries = options.retries.value_or(0.0);
  return std::string("") + std::to_string(options.label) + std::string(":") + std::to_string(retries) + std::string("");
}

std::string pick(bool flag, std::string first, std::string second) {
  return (flag ? first : second);
}

std::string classify(double value) {
  {
    auto switch_value = value;
    if (switch_value == 0.0) {
      return "zero";
    }
    else if (switch_value == 1.0) {
      return "one";
    }
    else {
      return "many";
    }
  }
}

} // namespace flighthq_golden
