// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/constructedClass.ts#ConstructedClass. Do not edit.
package flighthq.golden;

class Point {
  public var x:Float;

  public var y:Float;

  public function new(x:Float, y:Float) {
    this.x = x;
    this.y = y;
  }

  public function length():Float {
    return (this.x + this.y);
  }

  public function describe():String {
    return "point " + Std.string(this.x) + ", " + Std.string(this.y);
  }

  public function bare():String {
    return Std.string(this.x);
  }
}

class ConstructedClass {
  public static function origin():Point {
    return new Point(0, 0);
  }
}
