// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/variableHoisting.ts#VariableHoisting. Do not edit.
package flighthq.golden;

class VariableHoisting {
  public static function selectNested():Float {
    var value:Float;
    {
      value = 1;
    }
    return value;
  }

  public static function selectLoop(limit:Float):Float {
    var index:Float;
    var total:Float = 0;
    index = 0;
    {
      while ((index < limit)) {
        total += index;
        index += 1;
      }
    }
    return (total + index);
  }

  public static function selectPattern(values:Array<Dynamic>):String {
    var first:Float;
    var second:String;
    final arrayPatternValue:Array<Dynamic> = values;
    first = arrayPatternValue[0];
    second = arrayPatternValue[1];
    if ((first < 0)) {
      return "";
    }
    return second;
  }

  public static function incrementValues(values:Array<Float>):Void {
    var value:Float;
    for (variableHoistingIterationValue in values) {
      value = variableHoistingIterationValue;
      value += 1;
    }
  }
}
