// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/variableHoisting.ts#VariableHoisting. Do not edit.
package flighthq.golden;

function selectNested():Float {
  var value:Float;
  {
    value = 1;
  }
  return value;
}

function selectLoop(limit:Float):Float {
  var index:Float;
  var total:Float = 0;
  index = 0;
  {
    while (index < limit) {
      total += index;
      index += 1;
    }
  }
  return total + index;
}

function selectPattern(values:Array<Dynamic>):String {
  var first:Float;
  var second:String;
  final arrayPatternValue:Array<Dynamic> = values;
  first = arrayPatternValue[0];
  second = arrayPatternValue[1];
  if (first < 0) {
    return "";
  }
  return second;
}

function incrementValues(values:Array<Float>):Void {
  var value:Float;
  for (variableHoistingIterationValue in values) {
    value = variableHoistingIterationValue;
    value += 1;
  }
}
