// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/returnExpression.ts#ReturnExpression. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

double abs(double value) {
  return ((value < 0.0) ? -value : value);
}

double max_of_three(double a, double b, double c) {
  return (((a >= b) && (a >= c)) ? a : ((b >= c) ? b : c));
}

std::string describe(double value) {
  return ((value == 0.0) ? "zero" : ((value > 0.0) ? "positive" : "negative"));
}

double safe_div(double a, double b) {
  return ((b != 0.0) ? (a / b) : 0.0);
}

bool between(double value, double lo, double hi) {
  return ((value >= lo) && (value <= hi));
}

} // namespace flighthq_golden
