// Generated by @flighthq/tool-compiler. Do not edit.
package flighthq.golden;

class Counter {
  private var step:Float = 1;

  public final label:String = "counter";

  public function advance(by:Float):Float {
    return (by + this_.step);
  }
}
