// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/moduleImports.ts#ModuleImports. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;
import flighthq.golden.Helper.helper;

function use(value:Float):Float {
  return helper(value);
}
