// Generated by @flighthq/tool-compiler. Do not edit.
package flighthq.golden;

import flighthq.golden.Helper.helper;

class ModuleImports {
  public static function use(value:Float):Float {
    return helper(value);
  }
}
