// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringCharCode.ts#StringCharCode. Do not edit.
package flighthq.golden;

function charCodeFirst(text:String):Float {
  return text.charCodeAt(0);
}

function isDigitCode(text:String, index:Float):Bool {
  final code:Float = text.charCodeAt(index);
  return (code >= 48) && (code <= 57);
}

function sumCharCodes(text:String):Float {
  var total:Float = 0;
  {
    var i:Float = 0;
    while (i < text.length) {
      {
        total = (total + text.charCodeAt(i));
      }
      i = (i + 1);
    }
  }
  return total;
}
