// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/spreadCall.ts#SpreadCall. Do not edit.
#![forbid(unsafe_code)]

pub fn widest(values: Vec<f64>) -> f64 {
  return values.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
}
