// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/methodChain.ts#MethodChain. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

std::string trim_lower(std::string text) {
  return text.trim().to_lower();
}

std::string trim_upper(std::string text) {
  return text.trim().to_upper();
}

double measure_trimmed(std::string text) {
  return static_cast<double>(text.trim().size());
}

double lower_length(std::string text) {
  return static_cast<double>(text.to_lower().size());
}

} // namespace flighthq_golden
