// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nominalInterface.ts#NominalInterface. Do not edit.
#![forbid(unsafe_code)]

pub trait Advancer {
  fn step(&self) -> f64;
  fn advance(&self, by: f64) -> f64;
}

#[derive(Clone, Debug)]
pub struct Counter {
    pub step: f64,
}

impl Advancer for Counter {
  fn advance(&self, by: f64) -> f64 {
    return by + self.step;
  }

  fn step(&self) -> f64 {
    self.step.clone()
  }
}

impl Counter {
  pub fn new() -> Self {
    Self {
      step: 1.0,
    }
  }
}
