// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/contextualAliasAlternative.ts#ContextualAliasAlternative. Do not edit.
#pragma once
#include <functional>
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Point;
template <typename Value>
struct Box;

struct Point : public flight::ReferenceEnabled {
  double x;
};

template <typename Value>
struct Box : public flight::ReferenceEnabled {
  Value value;
};

using PointAlias = flight::Ref<Point>;

using ArraySlot = std::variant<flight::Array<PointAlias>, double>;

using MapSlot = std::variant<flight::Map<flight::String, PointAlias>, bool>;

using CallableSlot = std::variant<std::function<PointAlias()>, flight::String>;

using GenericSlot = std::variant<flight::Ref<Box<PointAlias>>, double>;

inline ArraySlot store_array(flight::Array<flight::Ref<Point>> values) {
  return std::variant<flight::Array<PointAlias>, double>{std::in_place_type<flight::Array<PointAlias>>, values};
}

inline MapSlot store_map(flight::Map<flight::String, flight::Ref<Point>> values) {
  return std::variant<flight::Map<flight::String, PointAlias>, bool>{std::in_place_type<flight::Map<flight::String, PointAlias>>, values};
}

inline CallableSlot store_callable(std::function<flight::Ref<Point>()> handler) {
  return std::variant<std::function<PointAlias()>, flight::String>{std::in_place_type<std::function<PointAlias()>>, handler};
}

inline GenericSlot store_generic(flight::Ref<Box<flight::Ref<Point>>> box) {
  return std::variant<flight::Ref<Box<PointAlias>>, double>{std::in_place_type<flight::Ref<Box<PointAlias>>>, box};
}

} // namespace flighthq_golden
