// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unionNarrowing.ts#UnionNarrowing. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
enum StrOrF64 {
  Str(String),
  F64(f64),
}

impl StrOrF64 {
  fn as_str(&self) -> &String {
    match self {
      StrOrF64::Str(value) => value,
      _ => panic!("StrOrF64 is not Str"),
    }
  }
  fn as_f64(&self) -> &f64 {
    match self {
      StrOrF64::F64(value) => value,
      _ => panic!("StrOrF64 is not F64"),
    }
  }
}

impl std::fmt::Display for StrOrF64 {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    match self {
      StrOrF64::Str(value) => write!(f, "{}", value),
      StrOrF64::F64(value) => write!(f, "{}", value),
    }
  }
}

pub fn narrow_typeof(value: StrOrF64) -> String {
  if matches!(value, StrOrF64::Str(_)) {
    return *value.as_str();
  }
  return *value.as_f64().to_string();
}

pub fn narrow_typeof_number(value: StrOrF64) -> f64 {
  if matches!(value, StrOrF64::F64(_)) {
    return *value.as_f64();
  }
  return 0.0;
}

pub fn narrow_branch(value: StrOrF64, flag: bool) -> String {
  if flag && matches!(value, StrOrF64::Str(_)) {
    return *value.as_str();
  }
  return "default".to_owned();
}

pub fn assert_string(value: StrOrF64) -> String {
  return value as String;
}

pub fn assert_number(value: StrOrF64) -> f64 {
  return value as f64;
}
