// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/logicalShortCircuit.ts#LogicalShortCircuit. Do not edit.
package flighthq.golden;

function bothPositive(a:Float, b:Float):Float {
  return ((a > 0) && (b > 0)) ? (a + b) : 0;
}

function eitherLarge(a:Float, b:Float):Bool {
  return (a > 100) || (b > 100);
}

function guardedDivide(a:Float, b:Float):Float {
  return ((b != 0) && ((a / b) > 1)) ? (a / b) : 0;
}

function rangeCheck(value:Float, low:Float, high:Float):Bool {
  return (value >= low) && (value <= high);
}
