// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/objectBinding.ts#ObjectBinding. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
struct Shape {
  pub other: bool,
  pub value: f64,
}

pub fn project(parameter_pattern_value: Shape, source: Shape) -> f64 {
  let mut value: f64;
  let object_pattern_value: Shape = parameter_pattern_value;
  value = object_pattern_value.value;
  let mut assigned: f64 = 0.0;
  {
    let destructuring_assignment_value: Shape = source;
    assigned = destructuring_assignment_value.value;
  }
  return (value + assigned);
}
