// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/traitInterface.ts#TraitInterface. Do not edit.
#pragma once
#include <functional>
#include <flight/runtime.hpp>

namespace flighthq_golden {

struct Advancer {
  std::function<double(double)> advance;
};

struct Counter {
  double step = 1.0;
  double advance(double by) {
    return (by + this->step);
  }
  void reset() {
    this->step = 1.0;
  }
};

} // namespace flighthq_golden
