// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mapLookup.ts#MapLookup. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double lookup(flight::Map<flight::String, double> entries, flight::String key) {
  const std::optional<double> value = entries.get(key);
  if (value.has_value()) {
    return value.value();
  }
  return -1.0;
}

inline flight::String get_or_default(flight::Map<flight::String, flight::String> entries, flight::String key, flight::String fallback) {
  const std::optional<flight::String> value = entries.get(key);
  if (value.has_value()) {
    return value.value();
  }
  return fallback;
}

} // namespace flighthq_golden
