// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/logicalAssignment.ts#LogicalAssignment. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double or_assign(double a, double b) {
  double value = a;
  ([&]() { auto&& assignment_target = value; if (!assignment_target) assignment_target = b; return assignment_target; }());
  return value;
}

inline double and_assign(double a, double b) {
  double value = a;
  ([&]() { auto&& assignment_target = value; if (assignment_target) assignment_target = b; return assignment_target; }());
  return value;
}

inline flight::String nullish_assign(std::optional<flight::String> a, flight::String fallback) {
  std::optional<flight::String> value = a;
  ([&]() { auto&& assignment_target = value; if (!assignment_target.has_value()) assignment_target = std::optional<flight::String>{fallback}; return assignment_target.value(); }());
  return value.value();
}

inline double or_assign_expr(double a, double b) {
  double value = a;
  const double result = ([&]() { auto&& assignment_target = value; if (!assignment_target) assignment_target = b; return assignment_target; }());
  return result;
}

inline double and_assign_expr(double a, double b) {
  double value = a;
  const double result = ([&]() { auto&& assignment_target = value; if (assignment_target) assignment_target = b; return assignment_target; }());
  return result;
}

inline flight::String nullish_assign_expr(std::optional<flight::String> a, flight::String fallback) {
  std::optional<flight::String> value = a;
  const flight::String result = ([&]() { auto&& assignment_target = value; if (!assignment_target.has_value()) assignment_target = std::optional<flight::String>{fallback}; return assignment_target.value(); }());
  return result;
}

} // namespace flighthq_golden
