// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/destructureParam.ts#DestructureParam. Do not edit.
#pragma once

namespace flighthq_golden {

struct rectangle {
  double height;
  double width;
};

double area(rectangle parameter_pattern_value) {
  double width;
  double height;
  const rectangle object_pattern_value = parameter_pattern_value;
  width = object_pattern_value.width;
  height = object_pattern_value.height;
  return (width * height);
}

double perimeter(rectangle parameter_pattern_value) {
  double width;
  double height;
  const rectangle object_pattern_value = parameter_pattern_value;
  width = object_pattern_value.width;
  height = object_pattern_value.height;
  return (2.0 * (width + height));
}

double diagonal(rectangle parameter_pattern_value) {
  double width;
  double height;
  const rectangle object_pattern_value = parameter_pattern_value;
  width = object_pattern_value.width;
  height = object_pattern_value.height;
  return std::sqrt(((width * width) + (height * height)));
}

bool is_square(rectangle parameter_pattern_value) {
  double width;
  double height;
  const rectangle object_pattern_value = parameter_pattern_value;
  width = object_pattern_value.width;
  height = object_pattern_value.height;
  return (width == height);
}

} // namespace flighthq_golden
