// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/earlyReturn.ts#EarlyReturn. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double find_first(flight::Array<double> items, double target) {
  for (double item : items) {
    if ((item == target)) {
      return item;
    }
  }
  return -1.0;
}

inline bool validate_positive(double value) {
  if ((value <= 0.0)) {
    return false;
  }
  return true;
}

inline flight::String classify(double value) {
  if ((value < 0.0)) {
    return flight::String("negative");
  }
  if ((value == 0.0)) {
    return flight::String("zero");
  }
  return flight::String("positive");
}

} // namespace flighthq_golden
