// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/moduloArithmetic.ts#ModuloArithmetic. Do not edit.
#pragma once
#include <cmath>
#include <cstdint>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double remainder(double a, double b) {
  return std::fmod(a, b);
}

inline bool is_even(double value) {
  return (std::fmod(value, 2.0) == 0.0);
}

inline double wrap_around(double value, double limit) {
  return std::fmod((std::fmod(value, limit) + limit), limit);
}

inline double divide_and_remainder(double a, double b) {
  const double quotient = std::floor((a / b));
  const double rem = std::fmod(a, b);
  return ((quotient * b) + rem);
}

} // namespace flighthq_golden
