// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/declareField.ts#DeclareField. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

struct Config {
  flight::String label;
  double flags;
  double value = 0.0;
  flight::String get_label() {
    return this->label;
  }
  double get_flags() {
    return this->flags;
  }
  double get_value() {
    return this->value;
  }
};

} // namespace flighthq_golden
