// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/declareField.ts#DeclareField. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

struct Config {
  std::string label;
  double flags;
  double value;
  std::string get_label() {
    return this->label;
  }
  double get_flags() {
    return this->flags;
  }
  double get_value() {
    return this->value;
  }
};

} // namespace flighthq_golden
