// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/conditionalAssign.ts#ConditionalAssign. Do not edit.
package flighthq.golden;

function sign(value:Float):String {
  var label:String;
  if (value > 0) {
    label = "positive";
  }
  else {
    if (value < 0) {
      label = "negative";
    }
    else {
      label = "zero";
    }
  }
  return label;
}

function bounds(values:Array<Float>):Float {
  var min:Float = values[0];
  var max:Float = values[0];
  for (v in values) {
    if (v < min) {
      min = v;
    }
    if (v > max) {
      max = v;
    }
  }
  return max - min;
}

function grade(score:Float):String {
  var letter:String;
  if (score >= 90) {
    letter = "A";
  }
  else {
    if (score >= 80) {
      letter = "B";
    }
    else {
      if (score >= 70) {
        letter = "C";
      }
      else {
        if (score >= 60) {
          letter = "D";
        }
        else {
          letter = "F";
        }
      }
    }
  }
  return letter;
}
