// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unsupportedSwitch.ts#UnsupportedSwitch. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double classify(double value) {
  {
    auto switch_value = value;
    if (switch_value == 1.0) {
      return 5.0;
    }
    else if (switch_value == 2.0) {
      return 5.0;
    }
    else {
      return 0.0;
    }
  }
}

} // namespace flighthq_golden
