// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unsupportedSwitch.ts#UnsupportedSwitch. Do not edit.
#pragma once
#include <stdexcept>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double classify(double value) {
  {
    auto switch_value = value;
    if (switch_value == 1.0) {
      return 5.0;
    }
    else if (switch_value == 2.0) {
      return 5.0;
    }
    else {
      return 0.0;
    }
  }
  throw std::logic_error("Flight function completed without a value");
}

} // namespace flighthq_golden
