// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeofPresenceGuard.ts#TypeofPresenceGuard. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Texture = { size:Float, name:String };

function read():Null<Texture> {
  return (cast js.Syntax.code("undefined") : Texture);
}

function sizeWhenPresent():Float {
  final texture:Null<Texture> = read();
  if (!flighthq._internal._Js.strictEqual(flighthq._internal._Js.typeOf(texture), "undefined")) {
    return (cast texture : Texture).size;
  }
  return 0;
}

function sizeWhenAbsent():Float {
  final texture:Null<Texture> = read();
  if (flighthq._internal._Js.strictEqual(flighthq._internal._Js.typeOf(texture), "undefined")) {
    return 0;
  }
  return (cast texture : Texture).size;
}
