// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/literalUnion.ts#LiteralUnion. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

using Lane = flight::String;

struct Route {
  Lane lane;
  double cost;
};

inline bool is_fast(Route route) {
  return (route.lane == flight::String("fast"));
}

inline flight::String lane_name(Route route) {
  return route.lane;
}

inline flight::String describe(Lane lane) {
  return ((lane == flight::String("fast")) ? flight::String("quick") : flight::String("careful"));
}

} // namespace flighthq_golden
