// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/literalUnion.ts#LiteralUnion. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

using Lane = std::string;

struct Route {
  Lane lane;
  double cost;
};

bool is_fast(Route route) {
  return (route.lane == "fast");
}

std::string lane_name(Route route) {
  return route.lane;
}

std::string describe(Lane lane) {
  return ((lane == "fast") ? "quick" : "careful");
}

} // namespace flighthq_golden
