// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nameCollision.ts#NameCollision. Do not edit.
#![forbid(unsafe_code)]

pub fn foo_bar(value: f64) -> f64 {
  return value;
}

pub fn foo_bar_2(value: f64) -> f64 {
  return value + 1.0;
}
