// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/templateExpression.ts#TemplateExpression. Do not edit.
package flighthq.golden;

function greet(name:String):String {
  return "Hello, " + Std.string(name) + "!";
}

function formatCoordinate(x:Float, y:Float):String {
  return "(" + Std.string(x) + ", " + Std.string(y) + ")";
}

function multiLine(title:String, body:String):String {
  return "Title: " + Std.string(title) + "\nBody: " + Std.string(body);
}

function nested(a:Float, b:Float):String {
  return "sum=" + Std.string((a + b)) + ", product=" + Std.string((a * b));
}
