// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/closedKeyWriteDispatch.ts#ClosedKeyWriteDispatch. Do not edit.
#pragma once
#include <optional>
#include <stdexcept>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Pairs;

struct Pairs : public flight::ReferenceEnabled {
  std::optional<double> alpha;
  std::optional<double> beta;
};

inline void set(flight::Ref<Pairs> pairs, flight::String key, double value) {
  ([&]() { const auto& selection_receiver = pairs; const auto selection_key = key; if (selection_key == flight::String("alpha")) { selection_receiver->alpha = value; return; } if (selection_key == flight::String("beta")) { selection_receiver->beta = value; return; } throw std::logic_error("Flight finite-key write reached no member"); }());
}

} // namespace flighthq_golden
