// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/returnExpression.ts#ReturnExpression. Do not edit.
#![forbid(unsafe_code)]

pub fn abs(value: f64) -> f64 {
  return if (value < 0.0) { -value } else { value };
}

pub fn max_of_three(a: f64, b: f64, c: f64) -> f64 {
  return if ((a >= b) && (a >= c)) { a } else { if (b >= c) { b } else { c } };
}

pub fn describe(value: f64) -> String {
  return if (value == 0.0) { "zero".to_owned() } else { if (value > 0.0) { "positive".to_owned() } else { "negative".to_owned() } };
}

pub fn safe_div(a: f64, b: f64) -> f64 {
  return if (b != 0.0) { (a / b) } else { 0.0 };
}

pub fn between(value: f64, lo: f64, hi: f64) -> bool {
  return (value >= lo) && (value <= hi);
}
