// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/reassignment.ts#Reassignment. Do not edit.
#pragma once
#include <string>
#include <vector>

namespace flighthq_golden {

std::string conditional_reassign(double value) {
  std::string label = "zero";
  if ((value > 0.0)) {
    label = "positive";
  }
  else {
    if ((value < 0.0)) {
      label = "negative";
    }
  }
  return label;
}

double swap_values(double a, double b) {
  double x = a;
  double y = b;
  const double temp = x;
  x = y;
  y = temp;
  return (x - y);
}

double accumulate(std::vector<double> values) {
  double sum = 0.0;
  double count = 0.0;
  for (double v : values) {
    sum += v;
    count += 1.0;
  }
  return (sum + count);
}

double narrow_down(double max) {
  double result = max;
  while ((result > 1.0)) {
    result = std::floor((result / 2.0));
  }
  return result;
}

} // namespace flighthq_golden
