// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayBinding.ts#ArrayBinding. Do not edit.
#![forbid(unsafe_code)]

pub fn select(values: (f64, f64, f64)) -> f64 {
  let array_pattern_value: (f64, f64, f64) = values;
  let third: f64 = array_pattern_value.2;
  return third;
}
