// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mathExtended.ts#MathExtended. Do not edit.
package flighthq.golden;

function circleArea(radius:Float):Float {
  return (Math.PI * radius) * radius;
}

function hypotenuse(a:Float, b:Float):Float {
  return Math.sqrt(((a * a) + (b * b)));
}

function ceilDivide(numerator:Float, denominator:Float):Float {
  return Math.ceil((numerator / denominator));
}

function degreesToRadians(degrees:Float):Float {
  return (degrees * Math.PI) / 180;
}

function signOf(value:Float):Float {
  return Math.sign(value);
}
