// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/repeatedArgument.ts#RepeatedArgument. Do not edit.
package flighthq.golden;

class RepeatedArgument {
  public static function total(values:Array<Float>):Float {
    return values.length;
  }

  public static function report(values:Array<Float>):Float {
    return total(values) + total(values);
  }

  public static function eachTotal(rows:Array<Float>):Float {
    var sum:Float = 0;
    {
      var index:Float = 0;
      while (index < 2) {
        {
          sum += total(rows);
        }
        index += 1;
      }
    }
    return sum;
  }
}
