// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/ambientMembers.ts#AmbientMembers. Do not edit.
package flighthq.golden;

class AmbientMembers {
  public static function doubled(values:Array<Float>):Array<Float> {
    return values.map(function(value:Float) return (value * 2));
  }

  public static function positives(values:Array<Float>):Array<Float> {
    return values.filter(function(value:Float) return (value > 0));
  }

  public static function shout(text:String):String {
    return text.toUpperCase();
  }

  public static function tidy(text:String):String {
    return StringTools.trim(text);
  }

  public static function leads(text:String):Bool {
    return StringTools.startsWith(text, "go");
  }
}
