// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/ambientMembers.ts#AmbientMembers. Do not edit.
package flighthq.golden;

function doubled(values:Array<Float>):Array<Float> {
  return values.map(function(value:Float) return (value * 2));
}

function positives(values:Array<Float>):Array<Float> {
  return values.filter(function(value:Float) return (value > 0));
}

function shout(text:String):String {
  return text.toUpperCase();
}

function tidy(text:String):String {
  return StringTools.trim(text);
}

function leads(text:String):Bool {
  return StringTools.startsWith(text, "go");
}
