// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/exponentiation.ts#Exponentiation. Do not edit.
#![forbid(unsafe_code)]

pub fn square(x: f64) -> f64 {
  return f64::powf(x, 2.0);
}

pub fn cube(x: f64) -> f64 {
  return f64::powf(x, 3.0);
}

pub fn nth_power(base: f64, exp: f64) -> f64 {
  return f64::powf(base, exp);
}

pub fn square_root(x: f64) -> f64 {
  return f64::powf(x, 0.5);
}

pub fn accum_power(base: f64, exp: f64) -> f64 {
  let mut result: f64 = base;
  result = f64::powf(result, exp);
  return result;
}
