// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/textInterpolation.ts#TextInterpolation. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

std::string label(double count, std::string name) {
  return std::string("") + std::to_string(name) + std::string(" has ") + std::to_string(count) + std::string(" items");
}

std::string ratio(double numerator, double denominator) {
  return std::string("") + std::to_string((numerator / denominator)) + std::string("");
}

std::string flag(bool enabled) {
  return std::string("") + std::to_string(enabled) + std::string("");
}

std::string joined(std::string first, std::string second) {
  return first + second;
}

} // namespace flighthq_golden
