// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/contextualUnionViewAbsence.ts#ContextualUnionViewAbsence. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Color = { r:Float, g:Float };

typedef Texture = { id:String };

function keepAbsence(value:Dynamic):Dynamic {
  return value;
}

function fromPresent(value:Dynamic):Dynamic {
  return value;
}

function fromOptional(value:Dynamic):Dynamic {
  return value;
}
