// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/restParameter.ts#RestParameter. Do not edit.
#![forbid(unsafe_code)]

pub fn sum(values: Vec<f64>) -> f64 {
  let mut total: f64 = 0.0;
  for value in values {
    total += value;
  }
  return total;
}

pub fn counted(items: Vec<f64>) -> f64 {
  return items.len() as f64;
}
