// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/compoundAssignment.ts#CompoundAssignment. Do not edit.
package flighthq.golden;

function accumulate(initial:Float, steps:Float):Float {
  var value:Float = initial;
  {
    var i:Float = 0;
    while (i < steps) {
      {
        value += i;
      }
      i += 1;
    }
  }
  return value;
}

function scale(base:Float, factor:Float):Float {
  var result:Float = base;
  result *= factor;
  return result;
}

function halve(value:Float):Float {
  var result:Float = value;
  result /= 2;
  return result;
}

function remainder(value:Float, divisor:Float):Float {
  var result:Float = value;
  result %= divisor;
  return result;
}
