// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/booleanExpression.ts#BooleanExpression. Do not edit.
#pragma once

namespace flighthq_golden {

bool negate(bool value) {
  return !value;
}

bool double_negate(bool value) {
  return !!value;
}

bool and(bool a, bool b) {
  return (a && b);
}

bool or(bool a, bool b) {
  return (a || b);
}

bool xor(bool a, bool b) {
  return ((a && !b) || (!a && b));
}

bool implies(bool a, bool b) {
  return (!a || b);
}

} // namespace flighthq_golden
