// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringEnum.ts#StringEnum. Do not edit.
package flighthq.golden;

enum abstract Lane(String) from String to String {
  var Fast = "fast";
  var Safe = "safe";
}
