// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/dateOperations.ts#DateOperations. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

double timestamp(FlightDate when) {
  return when.get_time();
}

double year(FlightDate when) {
  return when.get_full_year();
}

std::string format(FlightDate when) {
  return when.to_isostring();
}

} // namespace flighthq_golden
