// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/dateOperations.ts#DateOperations. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double timestamp(flight::Date when) {
  return when.get_time();
}

inline double year(flight::Date when) {
  return when.get_full_year();
}

inline flight::String format(flight::Date when) {
  return when.to_isostring();
}

} // namespace flighthq_golden
