// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/dateOperations.ts#DateOperations. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double timestamp(flight::Date when) {
  return when.get_time();
}

inline double year(flight::Date when) {
  return when.get_full_year();
}

inline flight::String format(flight::Date when) {
  return when.to_isostring();
}

} // namespace flighthq_golden
