// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/collectionFold.ts#CollectionFold. Do not edit.
#![forbid(unsafe_code)]

pub fn total(values: Vec<f64>) -> f64 {
  return values.into_iter().fold(0.0, |accumulated, value| accumulated + value);
}
