// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedClosure.ts#NestedClosure. Do not edit.
#![forbid(unsafe_code)]

use flight_runtime::FlightCallback;

pub fn create_counter(initial: f64) -> FlightCallback<(), f64> {
  let mut count: f64 = initial;
  return || {
  count = count + 1.0;
  return count;
};
}

pub fn apply_twice(value: f64, transform: FlightCallback<(f64,), f64>) -> f64 {
  return transform(transform(value));
}

pub fn filter_and_map(items: Vec<f64>, threshold: f64) -> Vec<String> {
  return items.into_iter().filter(|&item| item > threshold).collect::<Vec<_>>().into_iter().map(|item| item.to_string()).collect::<Vec<_>>();
}
