// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/recursiveComputation.ts#RecursiveComputation. Do not edit.
#pragma once

namespace flighthq_golden {

double factorial(double n) {
  if ((n <= 1.0)) {
    return 1.0;
  }
  return (n * factorial((n - 1.0)));
}

double fibonacci(double n) {
  if ((n <= 0.0)) {
    return 0.0;
  }
  if ((n == 1.0)) {
    return 1.0;
  }
  return (fibonacci((n - 1.0)) + fibonacci((n - 2.0)));
}

double sum_of_digits(double n) {
  if ((n < 10.0)) {
    return n;
  }
  return ((n % 10.0) + sum_of_digits(std::floor((n / 10.0))));
}

double power(double base, double exp) {
  if ((exp == 0.0)) {
    return 1.0;
  }
  return (base * power(base, (exp - 1.0)));
}

} // namespace flighthq_golden
