// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/recursiveComputation.ts#RecursiveComputation. Do not edit.
#pragma once
#include <cmath>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double factorial(double n) {
  if ((n <= 1.0)) {
    return 1.0;
  }
  return (n * factorial((n - 1.0)));
}

inline double fibonacci(double n) {
  if ((n <= 0.0)) {
    return 0.0;
  }
  if ((n == 1.0)) {
    return 1.0;
  }
  return (fibonacci((n - 1.0)) + fibonacci((n - 2.0)));
}

inline double sum_of_digits(double n) {
  if ((n < 10.0)) {
    return n;
  }
  return (std::fmod(n, 10.0) + sum_of_digits(std::floor((n / 10.0))));
}

inline double power(double base, double exp) {
  if ((exp == 0.0)) {
    return 1.0;
  }
  return (base * power(base, (exp - 1.0)));
}

} // namespace flighthq_golden
