// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/generics.ts#Generics. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

template <typename Left, typename Right>
struct Pair : public flight::ReferenceEnabled {
  Left left;
  Right right;
};

template <typename Value>
inline Value identity(Value value) {
  return value;
}

} // namespace flighthq_golden
