// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/generics.ts#Generics. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

struct left_right {
  Left left;
  Right right;
};

template <typename Left, typename Right>
using Pair = left_right;

template <typename Value>
inline Value identity(Value value) {
  return value;
}

} // namespace flighthq_golden
