// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/closedKeyWriteUnfittedValue.ts#ClosedKeyWriteUnfittedValue. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Style = { ?fontSize:Float, ?color:String };

function set(style:Style, key:Dynamic, value:Dynamic):Void {
  (function() { final assignmentReceiver:Dynamic = style; final assignmentKey:Dynamic = key; final assignmentValue:Dynamic = value; flighthq._internal._Js.setProperty(assignmentReceiver, assignmentKey, assignmentValue); return assignmentValue; })();
}
