// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/conditionalAwait.ts#ConditionalAwait. Do not edit.
package flighthq.golden;

class ConditionalAwait {
  public static function choose(task:flighthq._internal._Promise<Float>, flag:Bool):flighthq._internal._Promise<Float> {
    return new flighthq._internal._Promise(function(resolveTask, rejectTask) {
      try {
        var total:Float = 0;
        var taskJoin = function() {
          try {
            resolveTask(total);
            return;
          } catch (taskError_2:Dynamic) {
            rejectTask(taskError_2);
          }
        };
        if (flag) {
          try {
            flighthq._internal._Promise.resolve(task).then(
              function(awaitValue) {
                total = awaitValue;
                try {
                  taskJoin();
                  return;
                } catch (taskError_4:Dynamic) {
                  rejectTask(taskError_4);
                }
              },
              function(awaitError) {
                rejectTask(awaitError);
              }
            );
            return;
          } catch (taskError_3:Dynamic) {
            rejectTask(taskError_3);
          }
        } else {
          try {
            total = 1;
            taskJoin();
            return;
          } catch (taskError_5:Dynamic) {
            rejectTask(taskError_5);
          }
        }
        return;
      } catch (taskError:Dynamic) {
        rejectTask(taskError);
      }
    });
  }
}
