// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayAccumulate.ts#ArrayAccumulate. Do not edit.
#pragma once
#include <vector>

namespace flighthq_golden {

std::vector<double> running_sum(std::vector<double> values) {
  const std::vector<double> result = std::vector{};
  double sum = 0.0;
  for (double value : values) {
    sum = (sum + value);
    result.push_back(sum);
  }
  return result;
}

std::vector<double> filter_positive(std::vector<double> values) {
  const std::vector<double> result = std::vector{};
  for (double value : values) {
    if ((value > 0.0)) {
      result.push_back(value);
    }
  }
  return result;
}

double sum_squares(std::vector<double> values) {
  double total = 0.0;
  for (double value : values) {
    total = (total + (value * value));
  }
  return total;
}

} // namespace flighthq_golden
