// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayAccumulate.ts#ArrayAccumulate. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline flight::Array<double> running_sum(flight::Array<double> values) {
  flight::Array<double> result = flight::Array<double>{};
  double sum = 0.0;
  for (double value : values) {
    sum = (sum + value);
    result.push(sum);
  }
  return result;
}

inline flight::Array<double> filter_positive(flight::Array<double> values) {
  flight::Array<double> result = flight::Array<double>{};
  for (double value : values) {
    if ((value > 0.0)) {
      result.push(value);
    }
  }
  return result;
}

inline double sum_squares(flight::Array<double> values) {
  double total = 0.0;
  for (double value : values) {
    total = (total + (value * value));
  }
  return total;
}

} // namespace flighthq_golden
