// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/tryAwait.ts#TryAwait. Do not edit.
package flighthq.golden;

function attempt(task:flighthq._internal._Promise<Float>, fallback:Float):flighthq._internal._Promise<Float> {
  return new flighthq._internal._Promise(function(resolveTask, rejectTask) {
    try {
      var result:Float = 0;
      var taskJoin = function() {
        try {
          resolveTask(result);
          return;
        } catch (taskError_2:Dynamic) {
          rejectTask(taskError_2);
        }
      };
      var taskRejected = function(taskRejection:Dynamic) {
        try {
          result = fallback;
          taskJoin();
          return;
        } catch (taskError_3:Dynamic) {
          rejectTask(taskError_3);
        }
      };
      try {
        flighthq._internal._Promise.resolve(task).then(
          function(awaitValue) {
            result = awaitValue;
            try {
              taskJoin();
              return;
            } catch (taskError_5:Dynamic) {
              taskRejected(taskError_5);
              return;
            }
          },
          function(awaitError) {
            taskRejected(awaitError);
            return;
          }
        );
        return;
      } catch (taskError_4:Dynamic) {
        taskRejected(taskError_4);
        return;
      }
      return;
    } catch (taskError:Dynamic) {
      rejectTask(taskError);
    }
  });
}
