// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/tryAwait.ts#TryAwait. Do not edit.
package flighthq.golden;

class TryAwait {
  public static function attempt(task:flighthq._internal._Promise<Float>, fallback:Float):flighthq._internal._Promise<Float> {
    return new flighthq._internal._Promise(function(resolveTask, rejectTask) {
      try {
        var result:Float = 0;
        var taskJoin = function() {
          try {
            resolveTask(result);
            return;
          } catch (taskError_2:Dynamic) {
            rejectTask(taskError_2);
          }
        };
        try {
          flighthq._internal._Promise.resolve(task).then(
            function(awaitValue) {
              result = awaitValue;
              try {
                taskJoin();
                return;
              } catch (taskError_4:Dynamic) {
                try {
                  result = fallback;
                  taskJoin();
                  return;
                } catch (taskError_5:Dynamic) {
                  rejectTask(taskError_5);
                }
              }
            },
            function(awaitError) {
              try {
                result = fallback;
                taskJoin();
                return;
              } catch (taskError_6:Dynamic) {
                rejectTask(taskError_6);
              }
            }
          );
          return;
        } catch (taskError_3:Dynamic) {
          try {
            result = fallback;
            taskJoin();
            return;
          } catch (taskError_7:Dynamic) {
            rejectTask(taskError_7);
          }
        }
        return;
      } catch (taskError:Dynamic) {
        rejectTask(taskError);
      }
    });
  }
}
