// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/bitwiseAssignment.ts#BitwiseAssignment. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double mask_bits(double value, double mask) {
  double result = value;
  result &= mask;
  return result;
}

inline double set_bits(double value, double bits) {
  double result = value;
  result |= bits;
  return result;
}

inline double toggle_bits(double value, double bits) {
  double result = value;
  result ^= bits;
  return result;
}

inline double shift_left(double value, double count) {
  double result = value;
  result <<= count;
  return result;
}

inline double shift_right(double value, double count) {
  double result = value;
  result >>= count;
  return result;
}

} // namespace flighthq_golden
