// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/exponentiation.ts#Exponentiation. Do not edit.
#pragma once
#include <cmath>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double square(double x) {
  return std::pow(x, 2.0);
}

inline double cube(double x) {
  return std::pow(x, 3.0);
}

inline double nth_power(double base, double exp) {
  return std::pow(base, exp);
}

inline double square_root(double x) {
  return std::pow(x, 0.5);
}

inline double accum_power(double base, double exp) {
  double result = base;
  result = exp;
  return result;
}

} // namespace flighthq_golden
