// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/loopBreakContinue.ts#LoopBreakContinue. Do not edit.
package flighthq.golden;

function sumUntilNegative(values:Array<Float>):Float {
  var total:Float = 0;
  for (value in values) {
    if (value < 0) {
      break;
    }
    total += value;
  }
  return total;
}

function sumSkipOdd(values:Array<Float>):Float {
  var total:Float = 0;
  for (value in values) {
    if ((value - (2 * Math.floor((value / 2)))) != 0) {
      continue;
    }
    total += value;
  }
  return total;
}

function firstMultiple(limit:Float, divisor:Float):Float {
  var i:Float = 1;
  while (i <= limit) {
    if ((i - (divisor * Math.floor((i / divisor)))) == 0) {
      return i;
    }
    i += 1;
  }
  return - 1;
}

function countUntilSum(values:Array<Float>, target:Float):Float {
  var total:Float = 0;
  var count:Float = 0;
  for (value in values) {
    total += value;
    count += 1;
    if (total >= target) {
      break;
    }
  }
  return count;
}
