// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/tupleAccess.ts#TupleAccess. Do not edit.
#![forbid(unsafe_code)]

pub fn first(pair: (f64, String)) -> f64 {
  return pair.0;
}

pub fn second(pair: (f64, String)) -> String {
  return pair.1;
}

pub fn swap(pair: (f64, String)) -> (String, f64) {
  return (pair.1, pair.0);
}

pub fn sum_pair(pair: (f64, f64)) -> f64 {
  return pair.0 + pair.1;
}
