// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/loopJumpAwait.ts#LoopJumpAwait. Do not edit.
#![forbid(unsafe_code)]

use flight_runtime::FlightTask;

pub async fn drain(task: FlightTask<f64>, stop: bool, skip: bool) -> f64 {
  let mut last: f64 = 0.0;
  loop {
    last = task.clone().await;
    if skip {
      continue;
    }
    if stop {
      break;
    }
  }
  return last;
}
