// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/bitwiseNot.ts#BitwiseNot. Do not edit.
#pragma once
#include <cstdint>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double complement(double value) {
  return static_cast<double>(~static_cast<int32_t>(value));
}

inline double extract_low_byte(double value) {
  return static_cast<double>(static_cast<int32_t>(static_cast<double>(~static_cast<int32_t>(value))) & static_cast<int32_t>(255.0));
}

inline double toggle_sign(double value) {
  return (static_cast<double>(~static_cast<int32_t>(value)) + 1.0);
}

inline double mask_and_complement(double value, double mask) {
  return static_cast<double>(~static_cast<int32_t>(static_cast<double>(static_cast<int32_t>(value) & static_cast<int32_t>(mask))));
}

} // namespace flighthq_golden
