// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/labeledBreak.ts#LabeledBreak. Do not edit.
#![forbid(unsafe_code)]

pub fn find_pair(values: Vec<f64>, target: f64) -> f64 {
  let mut found: f64 = -1.0;
  {
    let mut i: f64 = 0.0;
    while i < (values.len() as f64) {
      {
        {
          let mut j: f64 = i + 1.0;
          while j < (values.len() as f64) {
            {
              if (values[i as usize] + values[j as usize]) == target {
                found = (i * 100.0) + j;
                break;
              }
            }
            j += 1.0;
          }
        }
        if found >= 0.0 {
          break;
        }
      }
      i += 1.0;
    }
  }
  return found;
}

pub fn first_above(matrix: Vec<Vec<f64>>, threshold: f64) -> f64 {
  let mut result: f64 = -1.0;
  for row in matrix {
    for cell in row {
      if cell > threshold {
        result = cell;
        break;
      }
    }
    if result >= 0.0 {
      break;
    }
  }
  return result;
}
