// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/collectionQuery.ts#CollectionQuery. Do not edit.
package flighthq.golden;

class CollectionQuery {
  public static function hasValue(values:Array<Float>, value:Float):Bool {
    return values.contains(value);
  }

  public static function anyPositive(values:Array<Float>):Bool {
    return Lambda.exists(values, function(value:Float) return (value > 0));
  }

  public static function allPositive(values:Array<Float>):Bool {
    return Lambda.foreach(values, function(value:Float) return (value > 0));
  }
}
