// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringBuild.ts#StringBuild. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::String reverse(flight::String text) {
  flight::String result = flight::String("");
  {
    double i = (static_cast<double>(text.length()) - 1.0);
    while ((i >= 0.0)) {
      {
        result = result + text.char_at(i);
      }
      i -= 1.0;
    }
  }
  return result;
}

inline double count_char(flight::String text, flight::String ch) {
  double count = 0.0;
  {
    double i = 0.0;
    while ((i < static_cast<double>(text.length()))) {
      {
        if ((text.char_at(i) == ch)) {
          count = (count + 1.0);
        }
      }
      i += 1.0;
    }
  }
  return count;
}

inline flight::String truncate(flight::String text, double max_length) {
  if ((static_cast<double>(text.length()) <= max_length)) {
    return text;
  }
  return text.substring(0.0, max_length) + flight::String("...");
}

} // namespace flighthq_golden
