// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/tupleAccess.ts#TupleAccess. Do not edit.
package flighthq.golden;

function first(pair:Array<Dynamic>):Float {
  return pair[0];
}

function second(pair:Array<Dynamic>):String {
  return pair[1];
}

function swap(pair:Array<Dynamic>):Array<Dynamic> {
  return [pair[1], pair[0]];
}

function sum_pair(pair:Array<Float>):Float {
  return pair[0] + pair[1];
}
