// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/comparisonChain.ts#ComparisonChain. Do not edit.
package flighthq.golden;

function isBetween(value:Float, low:Float, high:Float):Bool {
  return (value > low) && (value < high);
}

function isOutside(value:Float, low:Float, high:Float):Bool {
  return (value < low) || (value > high);
}

function compareThree(a:Float, b:Float, c:Float):Float {
  if ((a > b) && (a > c)) {
    return a;
  }
  if (b > c) {
    return b;
  }
  return c;
}

function allEqual(a:Float, b:Float, c:Float):Bool {
  return (a == b) && (b == c);
}

function noneNegative(a:Float, b:Float, c:Float):Bool {
  return ((a >= 0) && (b >= 0)) && (c >= 0);
}
