// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/templateExpression.ts#TemplateExpression. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline flight::String greet(flight::String name) {
  return flight::String("Hello, ") + flight::to_string(name) + flight::String("!");
}

inline flight::String format_coordinate(double x, double y) {
  return flight::String("(") + flight::to_string(x) + flight::String(", ") + flight::to_string(y) + flight::String(")");
}

inline flight::String multi_line(flight::String title, flight::String body) {
  return flight::String("Title: ") + flight::to_string(title) + flight::String("\nBody: ") + flight::to_string(body) + flight::String("");
}

inline flight::String nested(double a, double b) {
  return flight::String("sum=") + flight::to_string((a + b)) + flight::String(", product=") + flight::to_string((a * b)) + flight::String("");
}

} // namespace flighthq_golden
