// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/optionalAccumulator.ts#OptionalAccumulator. Do not edit.
#pragma once
#include <optional>
#include <string>
#include <vector>

namespace flighthq_golden {

struct name_count {
  std::string name;
  double count;
};

struct Item {
  std::string name;
  double count;
};

double busiest_count(std::vector<Item> items) {
  std::optional<Item> best = std::nullopt;
  for (name_count item : items) {
    if ((!best.has_value() || (item.count > best.value().count))) {
      best = item;
    }
  }
  return (!best.has_value() ? 0.0 : best.value().count);
}

} // namespace flighthq_golden
