// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/multipleReturn.ts#MultipleReturn. Do not edit.
package flighthq.golden;

function absoluteValue(value:Float):Float {
  if (value < 0) {
    return - value;
  }
  return value;
}

function fizzbuzz(n:Float):String {
  if ((n % 15) == 0) {
    return "fizzbuzz";
  }
  if ((n % 3) == 0) {
    return "fizz";
  }
  if ((n % 5) == 0) {
    return "buzz";
  }
  return Std.string(n);
}

function boundedIncrement(value:Float, max:Float):Float {
  if (value >= max) {
    return max;
  }
  return value + 1;
}

function triangleType(a:Float, b:Float, c:Float):String {
  if ((a == b) && (b == c)) {
    return "equilateral";
  }
  if (((a == b) || (b == c)) || (a == c)) {
    return "isosceles";
  }
  return "scalene";
}
