// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/conditionalExpression.ts#ConditionalExpression. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

std::string sign_label(double value) {
  return ((value >= 0.0) ? "non-negative" : "negative");
}

double max_of_two(double a, double b) {
  return ((a > b) ? a : b);
}

double abs_value(double value) {
  return ((value < 0.0) ? -value : value);
}

std::string even_odd_label(double value) {
  return (((value % 2.0) == 0.0) ? "even" : "odd");
}

double clamp_positive(double value) {
  return ((value > 0.0) ? value : 0.0);
}

} // namespace flighthq_golden
