// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/switchString.ts#SwitchString. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function greet(language:String):String {
  switch (language) {
    case "en":
      return "hello";
    case "es":
      return "hola";
    case "fr":
      return "bonjour";
    default:
      return "hi";
  }
  throw new haxe.Exception("unreachable control flow");
}

function priority(level:String):Float {
  switch (level) {
    case "low":
      return 1;
    case "medium":
      return 2;
    case "high":
      return 3;
    case "critical":
      return 4;
    default:
      return 0;
  }
  throw new haxe.Exception("unreachable control flow");
}
