// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arraySearch.ts#ArraySearch. Do not edit.
#pragma once
#include <vector>

namespace flighthq_golden {

double find_index(std::vector<double> values, double target) {
  return values.index_of(target);
}

double find_last_index(std::vector<double> values, double target) {
  return values.last_index_of(target);
}

bool contains_value(std::vector<double> values, double target) {
  return (values.index_of(target) != -1.0);
}

} // namespace flighthq_golden
