// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedAccess.ts#NestedAccess. Do not edit.
package flighthq.golden;

typedef Point = { x:Float, y:Float };

typedef Rect = { origin:Point, size:Point };

function area(rect:Rect):Float {
  return rect.size.x * rect.size.y;
}

function translate(rect:Rect, dx:Float, dy:Float):Point {
  return { x: (rect.origin.x + dx), y: (rect.origin.y + dy) };
}

function diagonal(rect:Rect):Float {
  final w:Float = rect.size.x;
  final h:Float = rect.size.y;
  return Math.sqrt(((w * w) + (h * h)));
}
