// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mathRounding.ts#MathRounding. Do not edit.
#pragma once

namespace flighthq_golden {

double floor_value(double x) {
  return std::floor(x);
}

double ceil_value(double x) {
  return std::ceil(x);
}

double abs_value(double x) {
  return std::abs(x);
}

double round_half(double x) {
  return std::floor((x + 0.5));
}

double clamp_floor(double value, double min, double max) {
  return std::floor(std::max(min, std::min(max, value)));
}

double distance_from_origin(double x, double y) {
  return std::floor(std::sqrt(((x * x) + (y * y))));
}

} // namespace flighthq_golden
