// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/collectionText.ts#CollectionText. Do not edit.
#![forbid(unsafe_code)]

pub fn sum(values: Vec<f64>) -> f64 {
  let mut total: f64 = 0.0;
  for value in values {
    total += value;
  }
  return total;
}

pub fn comma_joined(values: Vec<String>) -> String {
  return values.join(", ");
}

pub fn custom_joined(values: Vec<String>, separator: String) -> String {
  return values.join(&separator);
}
