// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/doWhileLoop.ts#DoWhileLoop. Do not edit.
package flighthq.golden;

function collatz(start:Float):Float {
  var n:Float = start;
  var steps:Float = 0;
  while ((n != 1) && (n > 0)) {
    if ((n - (2 * Math.floor((n / 2)))) == 0) {
      n = (n / 2);
    }
    else {
      n = ((3 * n) + 1);
    }
    steps = (steps + 1);
  }
  return steps;
}

function digitSum(value:Float):Float {
  var n:Float = Math.abs(value);
  var total:Float = 0;
  while (n >= 1) {
    total = (total + (n - (10 * Math.floor((n / 10)))));
    n = Math.floor((n / 10));
  }
  return total;
}
