// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/optionalChainProperty.ts#OptionalChainProperty. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Point;

struct Point : public flight::ReferenceEnabled {
  double x;
  double y;
};

inline double safe_x(std::optional<flight::Ref<Point>> point) {
  return ([&]() -> double { auto nullish_coalesce_left = ([&]() -> std::optional<double> { auto optional_chain_receiver = point; if (!optional_chain_receiver.has_value()) return std::nullopt; return optional_chain_receiver.value()->x; }()); if (nullish_coalesce_left.has_value()) return nullish_coalesce_left.value(); return 0.0; }());
}

inline double safe_y(std::optional<flight::Ref<Point>> point) {
  return ([&]() -> double { auto nullish_coalesce_left = ([&]() -> std::optional<double> { auto optional_chain_receiver = point; if (!optional_chain_receiver.has_value()) return std::nullopt; return optional_chain_receiver.value()->y; }()); if (nullish_coalesce_left.has_value()) return nullish_coalesce_left.value(); return 0.0; }());
}

inline double safe_sum(std::optional<flight::Ref<Point>> point) {
  const double x = ([&]() -> double { auto nullish_coalesce_left = ([&]() -> std::optional<double> { auto optional_chain_receiver = point; if (!optional_chain_receiver.has_value()) return std::nullopt; return optional_chain_receiver.value()->x; }()); if (nullish_coalesce_left.has_value()) return nullish_coalesce_left.value(); return 0.0; }());
  const double y = ([&]() -> double { auto nullish_coalesce_left = ([&]() -> std::optional<double> { auto optional_chain_receiver = point; if (!optional_chain_receiver.has_value()) return std::nullopt; return optional_chain_receiver.value()->y; }()); if (nullish_coalesce_left.has_value()) return nullish_coalesce_left.value(); return 0.0; }());
  return (x + y);
}

} // namespace flighthq_golden
