// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/staticMethod.ts#StaticMethod. Do not edit.
package flighthq.golden;

class Counter {
  public var count:Float;

  public function new(initial:Float) {
    this.count = initial;
  }

  public function increment():Void {
    this.count = (this.count + 1);
  }

  public function value():Float {
    return this.count;
  }

  public static function zero():Counter {
    return new Counter(0);
  }

  public static function fromValue(value:Float):Counter {
    return new Counter(value);
  }
}
