// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/contextualUnionSubsetConversion.ts#ContextualUnionSubsetConversion. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone)]
pub enum AnonymousUnion {
  Alpha(Alpha),
  Beta(Beta),
  Gamma(Gamma),
}

#[derive(Clone)]
pub enum AnonymousUnion2 {
  Alpha(Alpha),
  Beta(Beta),
}

#[derive(Clone, Debug)]
pub struct Alpha {
  pub a: f64,
}

#[derive(Clone, Debug)]
pub struct Beta {
  pub b: f64,
}

#[derive(Clone, Debug)]
pub struct Gamma {
  pub c: f64,
}

#[derive(Clone, Debug)]
pub struct Holder {
  pub slot: AnonymousUnion,
}

fn take(_value: AnonymousUnion) -> f64 {
  return 1.0;
}

pub fn pass(value: AnonymousUnion2) -> f64 {
  return take(value);
}

pub fn read(value: AnonymousUnion2) -> AnonymousUnion {
  return value;
}

pub fn put(holder: &mut Holder, value: AnonymousUnion2) -> () {
  holder.slot = value;
}
