// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringParse.ts#StringParse. Do not edit.
#![forbid(unsafe_code)]

pub fn count_words(text: String) -> f64 {
  let trimmed: String = text.trim().to_owned();
  if (trimmed.len() as f64) == 0.0 {
    return 0.0;
  }
  let words: Vec<String> = trimmed.split(" ").map(|s| s.to_string()).collect::<Vec<String>>();
  return words.len() as f64;
}

pub fn has_protocol(url: String) -> bool {
  return url.find("://").map(|i| i as f64).unwrap_or(-1.0) != -1.0;
}

pub fn contains_at(email: String) -> bool {
  return email.find("@").map(|i| i as f64).unwrap_or(-1.0) != -1.0;
}

pub fn token_count(csv: String) -> f64 {
  let tokens: Vec<String> = csv.split(",").map(|s| s.to_string()).collect::<Vec<String>>();
  return tokens.len() as f64;
}

pub fn rejoin_tokens(csv: String, separator: String) -> String {
  let tokens: Vec<String> = csv.split(",").map(|s| s.to_string()).collect::<Vec<String>>();
  return tokens.join(&separator);
}
