// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/callableUnionParameterity.ts#CallableUnionParameterity. Do not edit.
#![forbid(unsafe_code)]

use std::rc::Rc;

type Handler = Rc<dyn Fn(f64) -> ()>;

type Reporter = Rc<dyn Fn(f64) -> ()>;

type NullableReporter = Rc<dyn Fn(Option<f64>) -> ()>;

#[derive(Clone)]
enum HandlerSlot {
  Handler(Handler),
  String(String),
}

#[derive(Clone)]
enum ReporterSlot {
  Reporter(Reporter),
  String(String),
}

pub fn store_optional(handler: Rc<dyn Fn(f64) -> ()>) -> HandlerSlot {
  return handler;
}

pub fn store_nullable(handler: Rc<dyn Fn(Option<f64>) -> ()>) -> HandlerSlot {
  return handler;
}

pub fn store_reporter(handler: Reporter) -> ReporterSlot {
  return handler;
}

pub fn store_nullable_reporter(handler: NullableReporter) -> ReporterSlot {
  return handler;
}
