// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedLoop.ts#NestedLoop. Do not edit.
#![forbid(unsafe_code)]

pub fn multiplication_table(size: f64) -> f64 {
  let mut sum: f64 = 0.0;
  {
    let mut i: f64 = 1.0;
    while i <= size {
      {
        {
          let mut j: f64 = 1.0;
          while j <= size {
            {
              sum = sum + (i * j);
            }
            j = j + 1.0;
          }
        }
      }
      i = i + 1.0;
    }
  }
  return sum;
}

pub fn flatten_sum(matrix: Vec<Vec<f64>>) -> f64 {
  let mut total: f64 = 0.0;
  for row in matrix {
    for cell in row {
      total = total + cell;
    }
  }
  return total;
}

pub fn triangle_number(n: f64) -> f64 {
  let mut total: f64 = 0.0;
  let mut i: f64 = 1.0;
  while i <= n {
    let mut j: f64 = 1.0;
    while j <= i {
      total = total + 1.0;
      j = j + 1.0;
    }
    i = i + 1.0;
  }
  return total;
}
