// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayChain.ts#ArrayChain. Do not edit.
#pragma once
#include <functional>
#include <vector>

namespace flighthq_golden {

double sum_positive(std::vector<double> values) {
  return values.filter([=](double v) { return (v > 0.0); }).reduce([=](double acc, double v) { return (acc + v); }, 0.0);
}

std::vector<double> double_evens(std::vector<double> values) {
  return values.filter([=](double v) { return ((v % 2.0) == 0.0); }).map([=](double v) { return (v * 2.0); });
}

bool has_large_positive(std::vector<double> values) {
  return values.filter([=](double v) { return (v > 0.0); }).some([=](double v) { return (v > 100.0); });
}

double count_matching(std::vector<double> values, double threshold) {
  return static_cast<double>(values.filter([=](double v) { return (v > threshold); }).size());
}

} // namespace flighthq_golden
