// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayChain.ts#ArrayChain. Do not edit.
#pragma once
#include <cmath>
#include <functional>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double sum_positive(flight::Array<double> values) {
  return values.filter([=](double v) { return (v > 0.0); }).reduce([=](double acc, double v) { return (acc + v); }, 0.0);
}

inline flight::Array<double> double_evens(flight::Array<double> values) {
  return values.filter([=](double v) { return (std::fmod(v, 2.0) == 0.0); }).map([=](double v) { return (v * 2.0); });
}

inline bool has_large_positive(flight::Array<double> values) {
  return values.filter([=](double v) { return (v > 0.0); }).some([=](double v) { return (v > 100.0); });
}

inline double count_matching(flight::Array<double> values, double threshold) {
  return static_cast<double>(values.filter([=](double v) { return (v > threshold); }).size());
}

} // namespace flighthq_golden
