// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/erasedValueUnionSelection.ts#ErasedValueUnionSelection. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Payload = { id:String };

function entry(payload:Dynamic):Dynamic {
  return (cast payload : Dynamic);
}

function objectEntry(payload:Dynamic):Dynamic {
  return (cast payload : Dynamic);
}

function contextual(payload:Dynamic):Dynamic {
  return payload;
}

function accept(_payload:Dynamic):Float {
  return 1;
}

function pass(payload:Dynamic):Float {
  return accept((cast payload : Dynamic));
}
