// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/objectSpread.ts#ObjectSpread. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Point = { x:Float, y:Float };

function translate(point:Point, dx:Float, dy:Float):Point {
  return (cast { x: (point.x + dx), y: (point.y + dy) } : Point);
}

function scale(point:Point, factor:Float):Point {
  return (cast { x: (point.x * factor), y: (point.y * factor) } : Point);
}

function distance(a:Point, b:Point):Float {
  final dx:Float = a.x - b.x;
  final dy:Float = a.y - b.y;
  return Math.sqrt(((dx * dx) + (dy * dy)));
}

function midpoint(a:Point, b:Point):Point {
  return (cast { x: ((a.x + b.x) / 2), y: ((a.y + b.y) / 2) } : Point);
}
