// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/cStyleFor.ts#CStyleFor. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double total(flight::Array<double> values) {
  double sum = 0.0;
  {
    double index = 0.0;
    while ((index < static_cast<double>(values.size()))) {
      {
        sum += values.get(index).value_or(0.0);
      }
      index += 1.0;
    }
  }
  return sum;
}

} // namespace flighthq_golden
