// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/constructedClass.ts#ConstructedClass. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

impl Point {
  pub fn new(x: f64, y: f64) -> Self {
    Self {
      x: x,
      y: y,
    }
  }

  pub fn length(&self) -> f64 {
    return (self.x + self.y);
  }

  pub fn describe(&self) -> String {
    return format!("point {}, {}", self.x, self.y);
  }

  pub fn bare(&self) -> String {
    return format!("{}", self.x);
  }
}

pub fn origin() -> Point {
  return Point::new(0.0, 0.0);
}
