// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/privateField.ts#PrivateField. Do not edit.
package flighthq.golden;

class Counter {
  public var #count:Float = 0;

  public function increment():Void {
    this.#count += 1;
  }

  public function getCount():Float {
    return this.#count;
  }

  public function #reset():Void {
    this.#count = 0;
  }

  public function clear():Void {
    this.#reset();
  }
}
