import type { CompilerModuleIdentity } from '../../compiler-types/src/index.js';
import { createCompilerInvariantFailure } from './compilerSourceEmission.js';

export function createCompilerGeneratedFileHeader(
  moduleIdentity: Readonly<CompilerModuleIdentity>,
  commentPrefix: string,
  upstreamCommit?: string,
): string {
  const identity = `${moduleIdentity.packageName}/${moduleIdentity.source}#${moduleIdentity.name}`;
  if (
    commentPrefix.length === 0 ||
    [commentPrefix, moduleIdentity.packageName, moduleIdentity.source, moduleIdentity.name].some(hasLineTerminator)
  ) {
    throw createCompilerInvariantFailure(
      'invalid-generated-file-provenance',
      identity,
      `Generated-file provenance requires a nonempty single-line comment prefix and module identity: ${identity}`,
    );
  }
  if (upstreamCommit !== undefined && !/^[0-9a-f]{40}$/u.test(upstreamCommit)) {
    throw createCompilerInvariantFailure(
      'invalid-generated-file-provenance',
      upstreamCommit,
      `Generated-file provenance requires a lowercase 40-character upstream commit: ${upstreamCommit}`,
    );
  }
  const revision = upstreamCommit === undefined ? '' : ` at ${upstreamCommit}`;
  return `${commentPrefix} Generated by @flighthq/tool-compiler from ${identity}${revision}. Do not edit.`;
}

function hasLineTerminator(value: string): boolean {
  return /[\n\r\u2028\u2029]/u.test(value);
}
