// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/clamp.ts#Clamp. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline const double epsilon = 0.000001;

inline double clamp(double value, double min, double max) {
  if ((value < min)) {
    return min;
  }
  if ((value > max)) {
    return max;
  }
  return value;
}

} // namespace flighthq_golden
