// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/enumSwitch.ts#EnumSwitch. Do not edit.
package flighthq.golden;

enum abstract Direction(String) from String to String {
  var Up = "up";
  var Down = "down";
  var Left = "left";
  var Right = "right";
}

function isVertical(dir:Direction):Bool {
  return (dir == Direction.Up) || (dir == Direction.Down);
}

function opposite(dir:Direction):Direction {
  switch (dir) {
    case Direction.Up:
      return Direction.Down;
    case Direction.Down:
      return Direction.Up;
    case Direction.Left:
      return Direction.Right;
    case Direction.Right:
      return Direction.Left;
  }
}

function directionLabel(dir:Direction):String {
  switch (dir) {
    case Direction.Up:
      return "north";
    case Direction.Down:
      return "south";
    case Direction.Left:
      return "west";
    case Direction.Right:
      return "east";
  }
}
