// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/multiReturn.ts#MultiReturn. Do not edit.
package flighthq.golden;

function sign(value:Float):Float {
  if (value > 0) {
    return 1;
  }
  if (value < 0) {
    return - 1;
  }
  return 0;
}

function safeDivide(a:Float, b:Float):Float {
  if (b == 0) {
    return 0;
  }
  return a / b;
}

function letterGrade(score:Float):String {
  if (score >= 90) {
    return "A";
  }
  if (score >= 80) {
    return "B";
  }
  if (score >= 70) {
    return "C";
  }
  if (score >= 60) {
    return "D";
  }
  return "F";
}

function fizzbuzz(n:Float):String {
  if ((n % 15) == 0) {
    return "fizzbuzz";
  }
  if ((n % 3) == 0) {
    return "fizz";
  }
  if ((n % 5) == 0) {
    return "buzz";
  }
  return Std.string(n);
}
