// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayMap.ts#ArrayMap. Do not edit.
#pragma once
#include <functional>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline flight::Array<double> doubles(flight::Array<double> values) {
  return values.map([=](double v) { return (v * 2.0); });
}

inline flight::Array<double> squares(flight::Array<double> values) {
  return values.map([=](double v) { return (v * v); });
}

inline flight::Array<double> negated(flight::Array<double> values) {
  return values.map([=](double v) { return -v; });
}

} // namespace flighthq_golden
