// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayMap.ts#ArrayMap. Do not edit.
#pragma once
#include <functional>
#include <vector>

namespace flighthq_golden {

std::vector<double> doubles(std::vector<double> values) {
  return values.map([=](double v) { return (v * 2.0); });
}

std::vector<double> squares(std::vector<double> values) {
  return values.map([=](double v) { return (v * v); });
}

std::vector<double> negated(std::vector<double> values) {
  return values.map([=](double v) { return -v; });
}

} // namespace flighthq_golden
