// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unguardedVariantMemberRefused.ts#UnguardedVariantMemberRefused. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct AnonymousObjectRecord {
  pub app: String,
}

#[derive(Clone, Debug)]
pub struct AnonymousObjectRecord2 {
  pub size: f64,
}

#[derive(Clone, Debug)]
pub struct AsepriteFrame {
  pub x: f64,
  pub y: f64,
}

#[derive(Clone, Debug)]
pub struct TexturePackerFrame {
  pub filename: String,
}

#[derive(Clone, Debug)]
pub struct AsepriteAtlas {
  pub frames: Vec<AsepriteFrame>,
  pub meta: AnonymousObjectRecord,
}

#[derive(Clone, Debug)]
pub struct TexturePackerAtlas {
  pub frames: Vec<TexturePackerFrame>,
  pub meta: AnonymousObjectRecord2,
}

#[derive(Clone, Debug)]
enum Atlas {
  AsepriteAtlas(AsepriteAtlas),
  TexturePackerAtlas(TexturePackerAtlas),
}

impl Atlas {
  fn as_aseprite_atlas(&self) -> &AsepriteAtlas {
    match self {
      Atlas::AsepriteAtlas(value) => value,
      _ => panic!("Atlas is not AsepriteAtlas"),
    }
  }
  fn as_texture_packer_atlas(&self) -> &TexturePackerAtlas {
    match self {
      Atlas::TexturePackerAtlas(value) => value,
      _ => panic!("Atlas is not TexturePackerAtlas"),
    }
  }
  fn frames(&self) -> Vec<AsepriteFrame> {
    match self {
      Atlas::AsepriteAtlas(value) => value.frames.clone(),
      Atlas::TexturePackerAtlas(value) => value.frames.clone(),
    }
  }
  fn meta(&self) -> AnonymousObjectRecord {
    match self {
      Atlas::AsepriteAtlas(value) => value.meta.clone(),
      Atlas::TexturePackerAtlas(value) => value.meta.clone(),
    }
  }
}

pub fn frame_count(atlas: Atlas) -> f64 {
  return atlas.frames().len() as f64;
}
