// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/voidReturn.ts#VoidReturn. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline void apply_discount(flight::Array<double> prices, double factor) {
  {
    double i = 0.0;
    while ((i < static_cast<double>(prices.size()))) {
      {
        prices.element(i) = (prices.element(i) * factor);
      }
      i = (i + 1.0);
    }
  }
}

inline void clear_array(flight::Array<double> values) {
  while ((static_cast<double>(values.size()) > 0.0)) {
    values.pop().value();
  }
}

} // namespace flighthq_golden
