// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/constAssignment.ts#ConstAssignment. Do not edit.
#![forbid(unsafe_code)]

pub fn compute_with_const(a: f64, b: f64) -> f64 {
  let sum: f64 = a + b;
  let product: f64 = a * b;
  let result: f64 = sum + product;
  return result;
}

pub fn multi_step(value: f64) -> f64 {
  let doubled: f64 = value * 2.0;
  let incremented: f64 = doubled + 1.0;
  let squared: f64 = incremented * incremented;
  return squared;
}

pub fn string_build(first: String, last: String) -> String {
  let full: String = format!("{} {}", first, last);
  let upper: String = full.to_uppercase();
  return upper;
}
