// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/callableUnionParameterity.ts#CallableUnionParameterity. Do not edit.
#pragma once
#include <functional>
#include <optional>
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

using Handler = std::function<void(double)>;

using Reporter = std::function<void(std::optional<double>)>;

using NullableReporter = std::function<void(std::optional<double>)>;

using HandlerSlot = std::variant<std::function<void(double)>, flight::String>;

using ReporterSlot = std::variant<std::function<void(std::optional<double>)>, flight::String>;

inline HandlerSlot store_optional(std::function<void(std::optional<double>)> handler) {
  return std::variant<std::function<void(double)>, flight::String>{std::in_place_type<std::function<void(double)>>, handler};
}

inline HandlerSlot store_nullable(std::function<void(std::optional<double>)> handler) {
  return std::variant<std::function<void(double)>, flight::String>{std::in_place_type<std::function<void(double)>>, [contextual_callable = handler](double contextual_callable_argument0) -> void { contextual_callable(contextual_callable_argument0); }};
}

inline ReporterSlot store_reporter(Reporter handler) {
  return std::variant<std::function<void(std::optional<double>)>, flight::String>{std::in_place_type<std::function<void(std::optional<double>)>>, handler};
}

inline ReporterSlot store_nullable_reporter(NullableReporter handler) {
  return std::variant<std::function<void(std::optional<double>)>, flight::String>{std::in_place_type<std::function<void(std::optional<double>)>>, handler};
}

} // namespace flighthq_golden
