// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/recordConstruction.ts#RecordConstruction. Do not edit.
#pragma once
#include <string>
#include <vector>

namespace flighthq_golden {

struct entry {
  std::string key;
  double value;
};

std::vector<entry> appended(std::vector<entry> entries, std::string key, double value) {
  const std::vector<entry> next = entries.slice();
  next.push_back({.key = key, .value = value});
  return next;
}

double tail_size(std::vector<entry> entries, double index) {
  return static_cast<double>(entries.slice(index).size());
}

} // namespace flighthq_golden
