// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayIndex.ts#ArrayIndex. Do not edit.
package flighthq.golden;

function at(values:Array<Float>, index:Float):Float {
  return values[Std.int(index)] ?? 0;
}

function head(values:Array<Float>):Float {
  return values[0] ?? 0;
}
