// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/multipleInterface.ts#MultipleInterface. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Named {
  flight::String name;
};

struct Valued {
  double value;
};

inline flight::String get_name(Named item) {
  return item.name;
}

inline double get_value(Valued item) {
  return item.value;
}

inline flight::String format_named(Named item) {
  return flight::String("item: ") + item.name;
}

inline bool is_positive(Valued item) {
  return (item.value > 0.0);
}

} // namespace flighthq_golden
