// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/multipleInterface.ts#MultipleInterface. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

struct named {
  std::string name;
};

struct valued {
  double value;
};

std::string get_name(named item) {
  return item.name;
}

double get_value(valued item) {
  return item.value;
}

std::string format_named(named item) {
  return "item: " + item.name;
}

bool is_positive(valued item) {
  return (item.value > 0.0);
}

} // namespace flighthq_golden
