// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/multipleInterface.ts#MultipleInterface. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

struct Named {
  std::string name;
};

struct Valued {
  double value;
};

std::string get_name(Named item) {
  return item.name;
}

double get_value(Valued item) {
  return item.value;
}

std::string format_named(Named item) {
  return "item: " + item.name;
}

bool is_positive(Valued item) {
  return (item.value > 0.0);
}

} // namespace flighthq_golden
