// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/functionComposition.ts#FunctionComposition. Do not edit.
#![forbid(unsafe_code)]

fn double(x: f64) -> f64 {
  return x * 2.0;
}

fn add_one(x: f64) -> f64 {
  return x + 1.0;
}

fn square(x: f64) -> f64 {
  return x * x;
}

pub fn double_and_add(value: f64) -> f64 {
  return add_one(double(value));
}

pub fn square_of_double(value: f64) -> f64 {
  return square(double(value));
}

pub fn chain_three(value: f64) -> f64 {
  return square(add_one(double(value)));
}

pub fn sum_of_squares(a: f64, b: f64) -> f64 {
  return square(a) + square(b);
}
