// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/collectionQuery.ts#CollectionQuery. Do not edit.
#![forbid(unsafe_code)]

pub fn has_value(values: Vec<f64>, value: f64) -> bool {
  return values.contains(&value);
}

pub fn any_positive(values: Vec<f64>) -> bool {
  return values.into_iter().any(|value| value > 0.0);
}

pub fn all_positive(values: Vec<f64>) -> bool {
  return values.into_iter().all(|value| value > 0.0);
}
