// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/catchFinallyAwait.ts#CatchFinallyAwait. Do not edit.
#pragma once
#include <coroutine>
#include <exception>
#include <stdexcept>
#include <vector>

namespace flighthq_golden {

FlightTask<double> attempt(FlightTask<double> task, std::vector<double> log) {
  double result = 0.0;
  std::exception_ptr finally_exception;
  try {
    try {
      result = co_await task;
    }
    catch (...) {
      result = 1.0;
    }
  }
  catch (...) {
    finally_exception = std::current_exception();
  }
  log.push_back(result);
  if (finally_exception) std::rethrow_exception(finally_exception);
  co_return result;
}

} // namespace flighthq_golden
