// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringCharAt.ts#StringCharAt. Do not edit.
package flighthq.golden;

function firstChar(text:String):String {
  return text.charAt(0);
}

function lastChar(text:String):String {
  return text.charAt((text.length - 1));
}

function isUpperFirst(text:String):Bool {
  final first:String = text.charAt(0);
  return first == first.toUpperCase();
}
