// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unionCarrierElementRefused.ts#UnionCarrierElementRefused. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone)]
pub enum AnonymousUnion {
  Fields(Fields),
  Other(Other),
}

#[derive(Clone)]
pub enum AnonymousUnion2 {
  Scalar(Scalar),
  F64(f64),
}

#[derive(Clone)]
enum Scalar {
  Bool(bool),
  F64(f64),
  String(String),
}

#[derive(Clone, Debug)]
pub struct Fields {
}

#[derive(Clone, Debug)]
pub struct Other {
}

pub fn read(fields: AnonymousUnion, key: String) -> Option<AnonymousUnion2> {
  return fields[key as usize];
}
