// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedCondition.ts#NestedCondition. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::String fizzbuzz(double n) {
  if (((n - (15.0 * std::floor((n / 15.0)))) == 0.0)) {
    return flight::String("fizzbuzz");
  }
  if (((n - (3.0 * std::floor((n / 3.0)))) == 0.0)) {
    return flight::String("fizz");
  }
  if (((n - (5.0 * std::floor((n / 5.0)))) == 0.0)) {
    return flight::String("buzz");
  }
  return flight::String("") + flight::to_string(n) + flight::String("");
}

inline flight::String letter_grade(double score) {
  if ((score >= 90.0)) {
    return flight::String("A");
  }
  if ((score >= 80.0)) {
    return flight::String("B");
  }
  if ((score >= 70.0)) {
    return flight::String("C");
  }
  if ((score >= 60.0)) {
    return flight::String("D");
  }
  return flight::String("F");
}

inline double quadrant(double x, double y) {
  if (((x > 0.0) && (y > 0.0))) {
    return 1.0;
  }
  if (((x < 0.0) && (y > 0.0))) {
    return 2.0;
  }
  if (((x < 0.0) && (y < 0.0))) {
    return 3.0;
  }
  if (((x > 0.0) && (y < 0.0))) {
    return 4.0;
  }
  return 0.0;
}

} // namespace flighthq_golden
