// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringParse.ts#StringParse. Do not edit.
package flighthq.golden;

function countWords(text:String):Float {
  final trimmed:String = StringTools.trim(text);
  if (trimmed.length == 0) {
    return 0;
  }
  final words:Array<String> = trimmed.split(" ");
  return words.length;
}

function hasProtocol(url:String):Bool {
  return url.indexOf("://") != - 1;
}

function containsAt(email:String):Bool {
  return email.indexOf("@") != - 1;
}

function tokenCount(csv:String):Float {
  final tokens:Array<String> = csv.split(",");
  return tokens.length;
}

function rejoinTokens(csv:String, separator:String):String {
  final tokens:Array<String> = csv.split(",");
  return tokens.join(separator);
}
