// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/operators.ts#Operators. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double adjust(double value, double mask) {
  double adjusted = value;
  adjusted += mask;
  adjusted *= 2.0;
  return -adjusted;
}

inline bool same(double left, double right) {
  return ((left == right) && (left != 0.0));
}

inline bool negate(bool value) {
  return !value;
}

} // namespace flighthq_golden
