// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/constrainedParameterConcreteOptional.ts#ConstrainedParameterConcreteOptional. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline bool is_absent(std::optional<flight::String> text) {
  return !text.has_value();
}

inline double measure(std::optional<flight::String> text) {
  if (!text.has_value()) {
    return 0.0;
  }
  return static_cast<double>(text.value().length());
}

inline double measure_narrowed(std::optional<flight::String> text) {
  const flight::String value = (text.has_value() ? text.value() : flight::String(""));
  return static_cast<double>(value.length());
}

} // namespace flighthq_golden
