// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/finallyAwait.ts#FinallyAwait. Do not edit.
#pragma once
#include <coroutine>
#include <exception>

namespace flighthq_golden {

FlightTask<double> attempt(FlightTask<double> task) {
  double result = 0.0;
  bool done = false;
  std::exception_ptr finally_exception;
  try {
    result = co_await task;
  }
  catch (...) {
    finally_exception = std::current_exception();
  }
  done = true;
  if (finally_exception) std::rethrow_exception(finally_exception);
  co_return (done ? result : result);
}

} // namespace flighthq_golden
