// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/finallyAwait.ts#FinallyAwait. Do not edit.
#pragma once
#include <coroutine>
#include <exception>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::Task<double> attempt(flight::Task<double> task) {
  double result = 0.0;
  bool done = false;
  std::exception_ptr finally_exception;
  try {
    result = co_await task;
  }
  catch (...) {
    finally_exception = std::current_exception();
  }
  done = true;
  if (finally_exception) std::rethrow_exception(finally_exception);
  co_return (done ? result : result);
}

} // namespace flighthq_golden
