// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/discriminatedUnion.ts#DiscriminatedUnion. Do not edit.
#pragma once
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Circle : public flight::ReferenceEnabled {
  flight::String kind;
  double radius;
};

struct Square : public flight::ReferenceEnabled {
  flight::String kind;
  double side;
};

using Shape = std::variant<flight::Ref<Circle>, flight::Ref<Square>>;

inline double area(Shape shape) {
  if (std::holds_alternative<flight::Ref<Circle>>(shape)) {
    return ((std::get<flight::Ref<Circle>>(shape)->radius * std::get<flight::Ref<Circle>>(shape)->radius) * 3.0);
  }
  return (std::get<flight::Ref<Square>>(shape)->side * std::get<flight::Ref<Square>>(shape)->side);
}

} // namespace flighthq_golden
