// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/discriminatedUnion.ts#DiscriminatedUnion. Do not edit.
#pragma once
#include <string>
#include <variant>

namespace flighthq_golden {

struct Circle {
  std::string kind;
  double radius;
};

struct Square {
  std::string kind;
  double side;
};

using Shape = std::variant<Circle, Square>;

double area(Shape shape) {
  if ((shape.kind == "circle")) {
    return ((shape.radius * shape.radius) * 3.0);
  }
  return (shape.side * shape.side);
}

} // namespace flighthq_golden
