// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/assignmentChain.ts#AssignmentChain. Do not edit.
#![forbid(unsafe_code)]

pub fn accumulate(start: f64, steps: f64) -> f64 {
  let mut value: f64 = start;
  {
    let mut i: f64 = 0.0;
    while i < steps {
      {
        value += i;
        value *= 2.0;
      }
      i += 1.0;
    }
  }
  return value;
}

pub fn build_string(base: String, count: f64) -> String {
  let mut result: String = base;
  {
    let mut i: f64 = 0.0;
    while i < count {
      {
        result = format!("{}{}", result, format!("-{}", i));
      }
      i += 1.0;
    }
  }
  return result;
}

pub fn bit_manipulate(value: f64, mask: f64) -> f64 {
  let mut result: f64 = value;
  result = (((result as i32) | (mask as i32)) as f64);
  result = (((result as i32) & (255.0 as i32)) as f64);
  result = (((result as i32) ^ (15.0 as i32)) as f64);
  result = (((result as i32) << (1.0 as i32)) as f64);
  return result;
}

pub fn multi_assign(a: f64, b: f64) -> f64 {
  let mut x: f64 = a;
  let mut y: f64 = b;
  x += y;
  y -= x;
  x *= 2.0;
  y *= -1.0;
  return x + y;
}
