// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringLength.ts#StringLength. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double get_length(flight::String s) {
  return static_cast<double>(s.length());
}

inline bool is_empty(flight::String s) {
  return (static_cast<double>(s.length()) == 0.0);
}

inline flight::String pad_to_length(flight::String s, double target) {
  flight::String result = s;
  while ((static_cast<double>(result.length()) < target)) {
    result = result + flight::String(" ");
  }
  return result;
}

inline bool longer_than(flight::String s, double threshold) {
  return (static_cast<double>(s.length()) > threshold);
}

} // namespace flighthq_golden
