// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/functionComposition.ts#FunctionComposition. Do not edit.
#pragma once

namespace flighthq_golden {

double double(double x) {
  return (x * 2.0);
}

double add_one(double x) {
  return (x + 1.0);
}

double square(double x) {
  return (x * x);
}

double double_and_add(double value) {
  return add_one(double(value));
}

double square_of_double(double value) {
  return square(double(value));
}

double chain_three(double value) {
  return square(add_one(double(value)));
}

double sum_of_squares(double a, double b) {
  return (square(a) + square(b));
}

} // namespace flighthq_golden
