// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/switchAwait.ts#SwitchAwait. Do not edit.
#![forbid(unsafe_code)]

use flight_runtime::FlightTask;

pub async fn pick(task: FlightTask<f64>, mode: f64) -> f64 {
  let mut total: f64 = 0.0;
  {
    let switch_subject = mode;
    if (switch_subject == 1.0) {
      total = task.await;
    }
    else {
      if (switch_subject == 2.0) {
        total = 20.0;
      }
      else {
        total = 30.0;
      }
    }
  }
  return total;
}
