// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayBinding.ts#ArrayBinding. Do not edit.
#pragma once
#include <optional>
#include <tuple>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

template <typename T>
using Rows = flight::Array<T>;

inline double select(std::tuple<double, double, double> values) {
  std::tuple<double, double, double> array_pattern_value = values;
  const double third = std::get<2>(array_pattern_value);
  return third;
}

inline double select_default(std::tuple<std::optional<double>> values) {
  std::tuple<std::optional<double>> array_pattern_value = values;
  const double first = std::get<0>(array_pattern_value).value_or(4.0);
  return first;
}

inline flight::Array<double> select_rest(std::tuple<double, flight::Array<double>> values) {
  std::tuple<double, flight::Array<double>> array_pattern_value = values;
  flight::Array<double> rest = std::get<1>(array_pattern_value);
  return rest;
}

inline std::tuple<double, std::optional<double>> create_values() {
  std::tuple<double, std::optional<double>> values = std::make_tuple(1.0, std::nullopt);
  return values;
}

inline double select_nested_default(std::tuple<std::optional<std::tuple<double>>> values) {
  std::tuple<std::optional<std::tuple<double>>> array_pattern_value = values;
  std::tuple<double> array_pattern_value_2 = std::get<0>(array_pattern_value).value_or(std::make_tuple(1.0));
  const double first = std::get<0>(array_pattern_value_2);
  return first;
}

inline std::tuple<flight::String, bool> select_fixed_rest(std::tuple<double, flight::String, bool> values) {
  std::tuple<double, flight::String, bool> array_pattern_value = values;
  std::tuple<flight::String, bool> rest = std::make_tuple(std::get<1>(array_pattern_value), std::get<2>(array_pattern_value));
  return rest;
}

inline flight::String select_nested_rest(std::tuple<double, flight::String, bool> values) {
  std::tuple<double, flight::String, bool> array_pattern_value = values;
  std::tuple<flight::String, bool> array_pattern_value_2 = std::make_tuple(std::get<1>(array_pattern_value), std::get<2>(array_pattern_value));
  const flight::String second = std::get<0>(array_pattern_value_2);
  return second;
}

inline std::tuple<std::optional<flight::String>> select_optional_rest(std::tuple<double, std::optional<flight::String>> values) {
  std::tuple<double, std::optional<flight::String>> array_pattern_value = values;
  std::tuple<std::optional<flight::String>> rest = std::make_tuple(std::get<1>(array_pattern_value));
  return rest;
}

inline std::tuple<flight::String, flight::Array<bool>> select_mixed_rest(std::tuple<double, flight::String, flight::Array<bool>> values) {
  std::tuple<double, flight::String, flight::Array<bool>> array_pattern_value = values;
  std::tuple<flight::String, flight::Array<bool>> rest = std::make_tuple(std::get<1>(array_pattern_value), std::get<2>(array_pattern_value));
  return rest;
}

inline flight::Array<bool> select_nested_mixed_rest(std::tuple<double, flight::String, flight::Array<bool>> values) {
  std::tuple<double, flight::String, flight::Array<bool>> array_pattern_value = values;
  std::tuple<flight::String, flight::Array<bool>> array_pattern_value_2 = std::make_tuple(std::get<1>(array_pattern_value), std::get<2>(array_pattern_value));
  flight::Array<bool> tail = std::get<1>(array_pattern_value_2);
  return tail;
}

inline double select_rows(Rows<std::tuple<double, double>> rows) {
  for (auto array_pattern_value : rows) {
    const double first = std::get<0>(array_pattern_value);
    const double second = std::get<1>(array_pattern_value);
    return first;
  }
  return 0.0;
}

} // namespace flighthq_golden
