// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeNarrowing.ts#TypeNarrowing. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function describeType(value:Dynamic):String {
  if (Std.isOfType(value, String)) {
    return "string of length " + Std.string(value.length);
  }
  return "number: " + Std.string(value);
}

function formatValue(value:Dynamic):String {
  if (Std.isOfType(value, String)) {
    return (cast value : String).toUpperCase();
  }
  if (Std.isOfType(value, Float)) {
    return Std.string(value);
  }
  return (flighthq._internal._Js.truthy(value) ? "yes" : "no");
}
