// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedLoop.ts#NestedLoop. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double multiplication_table(double size) {
  double sum = 0.0;
  {
    double i = 1.0;
    while ((i <= size)) {
      {
        {
          double j = 1.0;
          while ((j <= size)) {
            {
              sum = (sum + (i * j));
            }
            j = (j + 1.0);
          }
        }
      }
      i = (i + 1.0);
    }
  }
  return sum;
}

inline double flatten_sum(flight::Array<flight::Array<double>> matrix) {
  double total = 0.0;
  for (flight::Array<double> row : matrix) {
    for (auto cell : row) {
      total = (total + cell);
    }
  }
  return total;
}

inline double triangle_number(double n) {
  double total = 0.0;
  double i = 1.0;
  while ((i <= n)) {
    double j = 1.0;
    while ((j <= i)) {
      total = (total + 1.0);
      j = (j + 1.0);
    }
    i = (i + 1.0);
  }
  return total;
}

} // namespace flighthq_golden
