// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericCast.ts#NumericCast. Do not edit.
package flighthq.golden;

function roundDown(value:Float):Float {
  return Math.floor(value);
}

function roundUp(value:Float):Float {
  return Math.ceil(value);
}

function rounded(value:Float):Float {
  return Math.round(value);
}

function absolute(value:Float):Float {
  return Math.abs(value);
}

function integerPart(value:Float):Float {
  return (value >= 0) ? Math.floor(value) : Math.ceil(value);
}
