// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/optionalParameter.ts#OptionalParameter. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline flight::String greet_optional(std::optional<flight::String> name = std::nullopt) {
  if (name.has_value()) {
    return flight::String("Hello, ") + flight::to_string(name.value()) + flight::String("!");
  }
  return flight::String("Hello, stranger!");
}

inline double add_optional(double a, std::optional<double> b = std::nullopt) {
  if (b.has_value()) {
    return (a + b.value());
  }
  return a;
}

inline flight::String format_optional(double value, std::optional<flight::String> prefix = std::nullopt, std::optional<flight::String> suffix = std::nullopt) {
  flight::String result = flight::String("") + flight::to_string(value) + flight::String("");
  if (prefix.has_value()) {
    result = prefix.value() + result;
  }
  if (suffix.has_value()) {
    result = result + suffix.value();
  }
  return result;
}

} // namespace flighthq_golden
