// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/conditionalChain.ts#ConditionalChain. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::String classify(double value) {
  if ((value < 0.0)) {
    return flight::String("negative");
  }
  else {
    if ((value == 0.0)) {
      return flight::String("zero");
    }
    else {
      if ((value < 10.0)) {
        return flight::String("small");
      }
      else {
        if ((value < 100.0)) {
          return flight::String("medium");
        }
        else {
          return flight::String("large");
        }
      }
    }
  }
}

inline flight::String clamped_label(double value) {
  const double clamped = ((value < 0.0) ? 0.0 : ((value > 100.0) ? 100.0 : value));
  return ((clamped == 0.0) ? flight::String("min") : ((clamped == 100.0) ? flight::String("max") : flight::String("mid")));
}

inline double absolute_difference(double a, double b) {
  return ((a > b) ? (a - b) : (b - a));
}

} // namespace flighthq_golden
