// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/conditionalChain.ts#ConditionalChain. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

std::string classify(double value) {
  if ((value < 0.0)) {
    return "negative";
  }
  else {
    if ((value == 0.0)) {
      return "zero";
    }
    else {
      if ((value < 10.0)) {
        return "small";
      }
      else {
        if ((value < 100.0)) {
          return "medium";
        }
        else {
          return "large";
        }
      }
    }
  }
}

std::string clamped_label(double value) {
  const double clamped = ((value < 0.0) ? 0.0 : ((value > 100.0) ? 100.0 : value));
  return ((clamped == 0.0) ? "min" : ((clamped == 100.0) ? "max" : "mid"));
}

double absolute_difference(double a, double b) {
  return ((a > b) ? (a - b) : (b - a));
}

} // namespace flighthq_golden
