// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/negatedCondition.ts#NegatedCondition. Do not edit.
#pragma once

namespace flighthq_golden {

double unless(bool condition, double value) {
  if (!condition) {
    return value;
  }
  return 0.0;
}

bool neither(bool a, bool b) {
  return (!a && !b);
}

bool nand(bool a, bool b) {
  return !(a && b);
}

bool xor_manual(bool a, bool b) {
  return ((a || b) && !(a && b));
}

double clamp_positive(double value) {
  if (!(value > 0.0)) {
    return 0.0;
  }
  return value;
}

} // namespace flighthq_golden
