// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/literalUnion.ts#LiteralUnion. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

enum abstract Lane(String) from String to String {
  var Fast = "fast";
  var Safe = "safe";
}

typedef Route = { lane:Lane, cost:Float };

function isFast(route:Route):Bool {
  return flighthq._internal._Js.strictEqual(route.lane, "fast");
}

function laneName(route:Route):String {
  return route.lane;
}

function describe(lane:Lane):String {
  return (flighthq._internal._Js.strictEqual(lane, "fast") ? "quick" : "careful");
}
