// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/literalUnion.ts#LiteralUnion. Do not edit.
package flighthq.golden;

enum abstract Lane(String) from String to String {
  var Fast = "fast";
  var Safe = "safe";
}

typedef Route = { lane:Lane, cost:Float };

class LiteralUnion {
  public static function isFast(route:Route):Bool {
    return route.lane == "fast";
  }

  public static function laneName(route:Route):String {
    return route.lane;
  }

  public static function describe(lane:Lane):String {
    return (lane == "fast") ? "quick" : "careful";
  }
}
