// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/assertionOneAlternativeRecovery.ts#AssertionOneAlternativeRecovery. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Alpha = { a:Float };

typedef Beta = { b:Float };

typedef Gamma = { c:Float };

function one(value:Dynamic):Null<Alpha> {
  return (cast value : Null<Alpha>);
}

function nullable(value:Dynamic):Null<Alpha> {
  return (cast value : Null<Alpha>);
}

function fromNullable(value:Null<Dynamic>):Null<Alpha> {
  return (cast value : Null<Alpha>);
}
