// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/reassignment.ts#Reassignment. Do not edit.
package flighthq.golden;

function conditionalReassign(value:Float):String {
  var label:String = "zero";
  if (value > 0) {
    label = "positive";
  }
  else {
    if (value < 0) {
      label = "negative";
    }
  }
  return label;
}

function swapValues(a:Float, b:Float):Float {
  var x:Float = a;
  var y:Float = b;
  final temp:Float = x;
  x = y;
  y = temp;
  return x - y;
}

function accumulate(values:Array<Float>):Float {
  var sum:Float = 0;
  var count:Float = 0;
  for (v in values) {
    sum += v;
    count += 1;
  }
  return sum + count;
}

function narrowDown(max:Float):Float {
  var result:Float = max;
  while (result > 1) {
    result = Math.floor((result / 2));
  }
  return result;
}
