// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/identityAssertionConversion.ts#IdentityAssertionConversion. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Point;

struct Point : public flight::ReferenceEnabled {
  double x;
};

inline std::optional<flight::Array<flight::Ref<Point>>> readonly_view(std::optional<flight::Array<flight::Ref<Point>>> values) {
  return values;
}

inline std::optional<flight::Array<double>> readonly_numbers(std::optional<flight::Array<double>> values) {
  return values;
}

inline flight::Array<flight::Ref<Point>> readonly_plain(flight::Array<flight::Ref<Point>> values) {
  return values;
}

} // namespace flighthq_golden
