// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayMap.ts#ArrayMap. Do not edit.
#![forbid(unsafe_code)]

pub fn doubles(values: Vec<f64>) -> Vec<f64> {
  return values.into_iter().map(|v| v * 2.0).collect::<Vec<_>>();
}

pub fn squares(values: Vec<f64>) -> Vec<f64> {
  return values.into_iter().map(|v| v * v).collect::<Vec<_>>();
}

pub fn negated(values: Vec<f64>) -> Vec<f64> {
  return values.into_iter().map(|v| -v).collect::<Vec<_>>();
}
