// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mapOperations.ts#MapOperations. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline bool contains(flight::Map<flight::String, double> entries, flight::String key) {
  return entries.has(key);
}

inline double count(flight::Map<flight::String, double> entries) {
  return static_cast<double>(entries.size());
}

inline void insert(flight::Map<flight::String, double> entries, flight::String key, double value) {
  entries.set(key, value);
}

inline void remove(flight::Map<flight::String, double> entries, flight::String key) {
  entries.erase(key);
}

inline bool set_contains(flight::Set<flight::String> values, flight::String item) {
  return values.has(item);
}

inline double set_size(flight::Set<flight::String> values) {
  return static_cast<double>(values.size());
}

inline void set_add(flight::Set<flight::String> values, flight::String item) {
  values.add(item);
}

} // namespace flighthq_golden
