// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericBoundary.ts#NumericBoundary. Do not edit.
package flighthq.golden;

function safeDiv(a:Float, b:Float):Float {
  if (b == 0) {
    return 0;
  }
  return a / b;
}

function clampInt(value:Float, min:Float, max:Float):Float {
  if (value < min) {
    return min;
  }
  if (value > max) {
    return max;
  }
  return Math.floor(value);
}

function isEven(n:Float):Bool {
  return (Math.floor(n) == n) && ((n - (2 * Math.floor((n / 2)))) == 0);
}

function lerp(a:Float, b:Float, t:Float):Float {
  return a + ((b - a) * t);
}
