// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeNarrowing.ts#TypeNarrowing. Do not edit.
#pragma once
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::String describe_type(std::variant<double, flight::String> value) {
  if (value.index() == 1) {
    return flight::String("string of length ") + flight::to_string(static_cast<double>(std::get<1>(value).length())) + flight::String("");
  }
  return flight::String("number: ") + flight::to_string(std::get<0>(value)) + flight::String("");
}

inline flight::String format_value(std::variant<bool, double, flight::String> value) {
  if (value.index() == 2) {
    return std::get<2>(value).to_upper();
  }
  if (value.index() == 1) {
    return flight::String("") + flight::to_string(std::get<1>(value)) + flight::String("");
  }
  return (std::get<0>(value) ? flight::String("yes") : flight::String("no"));
}

} // namespace flighthq_golden
