// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeNarrowing.ts#TypeNarrowing. Do not edit.
#pragma once
#include <string>
#include <variant>

namespace flighthq_golden {

std::string describe_type(std::variant<std::string, double> value) {
  if ((typeidvalue == "string")) {
    return std::string("string of length ") + std::to_string(static_cast<double>(value.size())) + std::string("");
  }
  return std::string("number: ") + std::to_string(value) + std::string("");
}

std::string format_value(std::variant<std::string, double, bool> value) {
  if ((typeidvalue == "string")) {
    return value.to_upper();
  }
  if ((typeidvalue == "number")) {
    return std::string("") + std::to_string(value) + std::string("");
  }
  return (value ? "yes" : "no");
}

} // namespace flighthq_golden
