// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/doWhileAwait.ts#DoWhileAwait. Do not edit.
#pragma once
#include <coroutine>

namespace flighthq_golden {

FlightTask<double> drain(FlightTask<double> task, bool again) {
  double last = 0.0;
  do {
    last = co_await task;
    again = false;
  } while (again);
  co_return last;
}

} // namespace flighthq_golden
