// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/collectionFold.ts#CollectionFold. Do not edit.
#pragma once
#include <functional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double total(flight::Array<double> values) {
  return values.reduce([=](double accumulated, double value) { return (accumulated + value); }, 0.0);
}

} // namespace flighthq_golden
