// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unsignedShift.ts#UnsignedShift. Do not edit.
package flighthq.golden;

function unsignedShiftRight(value:Float, count:Float):Float {
  return Std.int(value) >>> Std.int(count);
}

function unsignedShiftAssign(value:Float, count:Float):Float {
  var result:Float = value;
  result = Std.int(result) >>> Std.int(count);
  return result;
}

function signedVsUnsigned(value:Float):Float {
  final signed:Float = Std.int(value) >> Std.int(1);
  final unsigned:Float = Std.int(value) >>> Std.int(1);
  return signed + unsigned;
}
