// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unionMemberAliasAssertion.ts#UnionMemberAliasAssertion. Do not edit.
#pragma once
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Runtime;

struct Runtime : public flight::ReferenceEnabled {
  flight::String kind;
};

using RuntimeAlias = flight::Ref<Runtime>;

using NestedAlias = RuntimeAlias;

using Slot = std::variant<flight::Ref<Runtime>, flight::String>;

inline NestedAlias narrow_nested(std::variant<flight::Ref<Runtime>, flight::String> value) {
  return std::get<flight::Ref<Runtime>>(value);
}

inline RuntimeAlias narrow_from_aliased_union(Slot value) {
  return std::get<flight::Ref<Runtime>>(value);
}

} // namespace flighthq_golden
