// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nullishPresenceTest.ts#NullishPresenceTest. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function comparesEqualsString(value:String):Bool {
  return js.Syntax.strictEq(value, js.Syntax.code("undefined"));
}

function comparesIndexed(values:haxe.DynamicAccess<String>, key:String):Bool {
  return js.Syntax.strictNeq(HaxeReflect.field(values, key), js.Syntax.code("undefined"));
}

function comparesNumber(flag:Float):Bool {
  return js.Syntax.strictNeq(flag, js.Syntax.code("undefined"));
}

function comparesNullable(value:Null<String>):Bool {
  return value != null;
}

function comparesString(value:String):Bool {
  return js.Syntax.strictNeq(value, js.Syntax.code("undefined"));
}

function comparesStringLoose(value:String):Bool {
  return value != null;
}
