// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/classAccessor.ts#ClassAccessor. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct Counter {
    count: f64,
}

impl Counter {
  pub const ZERO: f64 = 0.0;
  pub fn new(count: f64) -> Self {
    Self {
      count: count,
    }
  }

  pub fn value(&self) -> f64 {
    return self.count;
  }

  pub fn set_value(&mut self, next: f64) -> () {
    self.count = next;
  }

  pub fn make() -> Counter {
    return Counter::new(0.0);
  }
}

pub fn read_back(counter: Counter) -> f64 {
  return counter.value();
}
