// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/helper.ts#Helper. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double helper(double value) {
  return (value + 1.0);
}

} // namespace flighthq_golden
