// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/moduleValueFacade.ts#ModuleValueFacade. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

} // namespace flighthq_golden
