// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/moduleValueFacade.ts#ModuleValueFacade. Do not edit.
#pragma once

namespace flighthq_golden {

} // namespace flighthq_golden
