// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unionValuePartialProjectionRefused.ts#UnionValuePartialProjectionRefused. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Alpha = { a:Float, extra:Float };

typedef Beta = { b:Float };

function take(_value:Dynamic):Float {
  return 1;
}

function pass(value:Dynamic):Float {
  return take(value);
}
