// Generated by @flighthq/tool-compiler. Do not edit.
package flighthq.golden;

class DefaultParameter {
  public static function scale(value:Float, factor:Float = 2):Float {
    return (value * factor);
  }
}
