// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/defaultParameter.ts#DefaultParameter. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function scale(value:Float, ?factor:Float):Float {
  final factorDefault:Float = js.Syntax.strictEq(factor, js.Syntax.code("undefined")) ? 2 : (cast factor : Float);
  return value * factorDefault;
}
