// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/catchAwait.ts#CatchAwait. Do not edit.
package flighthq.golden;

class CatchAwait {
  public static function attempt(task:flighthq._internal._Promise<Float>, backup:flighthq._internal._Promise<Float>):flighthq._internal._Promise<Float> {
    return new flighthq._internal._Promise(function(resolveTask, rejectTask) {
      try {
        var result:Float = 0;
        var taskJoin = function() {
          try {
            resolveTask(result);
            return;
          } catch (taskError_2:Dynamic) {
            rejectTask(taskError_2);
          }
        };
        var taskRejected = function(taskRejection:Dynamic) {
          try {
            flighthq._internal._Promise.resolve(backup).then(
              function(awaitValue) {
                result = awaitValue;
                try {
                  taskJoin();
                  return;
                } catch (taskError_4:Dynamic) {
                  rejectTask(taskError_4);
                }
              },
              function(awaitError) {
                rejectTask(awaitError);
              }
            );
            return;
          } catch (taskError_3:Dynamic) {
            rejectTask(taskError_3);
          }
        };
        try {
          flighthq._internal._Promise.resolve(task).then(
            function(awaitValue_2) {
              result = awaitValue_2;
              try {
                taskJoin();
                return;
              } catch (taskError_6:Dynamic) {
                taskRejected(taskError_6);
                return;
              }
            },
            function(awaitError_2) {
              taskRejected(awaitError_2);
              return;
            }
          );
          return;
        } catch (taskError_5:Dynamic) {
          taskRejected(taskError_5);
          return;
        }
        return;
      } catch (taskError:Dynamic) {
        rejectTask(taskError);
      }
    });
  }
}
