// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/multipleReturn.ts#MultipleReturn. Do not edit.
#![forbid(unsafe_code)]

pub fn absolute_value(value: f64) -> f64 {
  if value < 0.0 {
    return -value;
  }
  return value;
}

pub fn fizzbuzz(n: f64) -> String {
  if (n % 15.0) == 0.0 {
    return "fizzbuzz".to_owned();
  }
  if (n % 3.0) == 0.0 {
    return "fizz".to_owned();
  }
  if (n % 5.0) == 0.0 {
    return "buzz".to_owned();
  }
  return format!("{}", n);
}

pub fn bounded_increment(value: f64, max: f64) -> f64 {
  if value >= max {
    return max;
  }
  return value + 1.0;
}

pub fn triangle_type(a: f64, b: f64, c: f64) -> String {
  if (a == b) && (b == c) {
    return "equilateral".to_owned();
  }
  if ((a == b) || (b == c)) || (a == c) {
    return "isosceles".to_owned();
  }
  return "scalene".to_owned();
}
