// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeofNarrowing.ts#TypeofNarrowing. Do not edit.
#pragma once
#include <variant>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline flight::String describe(std::variant<flight::String, double> value) {
  if ((typeidvalue == flight::String("string"))) {
    return value.to_upper();
  }
  return flight::String("number ") + flight::to_string(value) + flight::String("");
}

inline double length(std::variant<flight::String, double> value) {
  if ((typeidvalue == flight::String("number"))) {
    return 1.0;
  }
  return static_cast<double>(value.length());
}

inline flight::String classify(std::variant<flight::String, double, bool> value) {
  if ((typeidvalue == flight::String("string"))) {
    return flight::String("text");
  }
  if ((typeidvalue == flight::String("number"))) {
    return flight::String("count");
  }
  return flight::String("flag");
}

} // namespace flighthq_golden
