// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeofNarrowing.ts#TypeofNarrowing. Do not edit.
#pragma once
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::String describe(std::variant<flight::String, double> value) {
  if (std::holds_alternative<flight::String>(value)) {
    return std::get<flight::String>(value).to_upper();
  }
  return flight::String("number ") + flight::to_string(std::get<double>(value)) + flight::String("");
}

inline double length(std::variant<flight::String, double> value) {
  if (std::holds_alternative<double>(value)) {
    return 1.0;
  }
  return static_cast<double>(std::get<flight::String>(value).length());
}

inline flight::String classify(std::variant<flight::String, double, bool> value) {
  if (std::holds_alternative<flight::String>(value)) {
    return flight::String("text");
  }
  if (std::holds_alternative<double>(value)) {
    return flight::String("count");
  }
  return flight::String("flag");
}

} // namespace flighthq_golden
