// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/closedKeySelection.ts#ClosedKeySelection. Do not edit.
#pragma once
#include <functional>
#include <optional>
#include <stdexcept>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Signals;

struct Signals : public flight::ReferenceEnabled {
  std::function<void()> on_complete;
  std::function<void()> on_loop;
  std::function<void()> on_pause;
  std::function<void()> on_play;
  std::function<void()> on_stop;
};

inline void invoke(std::function<void()> signal) {
  signal();
}

using SignalName = flight::String;

inline void emits_signal(std::optional<flight::Ref<Signals>> signals, SignalName name) {
  if (signals.has_value()) {
    invoke(([&]() -> std::function<void()> { const auto& selection_receiver = signals.value(); const auto selection_key = name; if (selection_key == flight::String("onComplete")) return selection_receiver->on_complete; if (selection_key == flight::String("onLoop")) return selection_receiver->on_loop; if (selection_key == flight::String("onPause")) return selection_receiver->on_pause; if (selection_key == flight::String("onPlay")) return selection_receiver->on_play; if (selection_key == flight::String("onStop")) return selection_receiver->on_stop; throw std::logic_error("Flight finite-key selection reached no member"); }()));
  }
}

} // namespace flighthq_golden
