// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/variableForInHoisting.ts#VariableForInHoisting. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct Values {
  pub value: f64,
}

pub fn select_first_key(values: Values) -> String {
  let key;
  for variable_hoisting_iteration_value in ["value".to_owned()] {
    key = variable_hoisting_iteration_value;
    return key;
  }
  return "".to_owned();
}
