// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/closedKeySelection.ts#ClosedKeySelection. Do not edit.
#![forbid(unsafe_code)]

use std::rc::Rc;

#[derive(Clone, Debug)]
pub struct Signals {
  pub on_complete: Rc<dyn Fn() -> ()>,
  pub on_loop: Rc<dyn Fn() -> ()>,
  pub on_pause: Rc<dyn Fn() -> ()>,
  pub on_play: Rc<dyn Fn() -> ()>,
  pub on_stop: Rc<dyn Fn() -> ()>,
}

fn invoke(signal: Rc<dyn Fn() -> ()>) -> () {
  signal();
}

pub type SignalName = String;

pub fn emits_signal(signals: Option<Signals>, name: SignalName) -> () {
  if signals.is_some() {
    invoke(signals.clone().unwrap()[name as usize]);
  }
}
