// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/switchExpression.ts#SwitchExpression. Do not edit.
#pragma once
#include <stdexcept>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::String day_name(double day) {
  {
    auto switch_value = day;
    if (switch_value == 0.0) {
      return flight::String("Sunday");
    }
    else if (switch_value == 1.0) {
      return flight::String("Monday");
    }
    else if (switch_value == 2.0) {
      return flight::String("Tuesday");
    }
    else if (switch_value == 3.0) {
      return flight::String("Wednesday");
    }
    else if (switch_value == 4.0) {
      return flight::String("Thursday");
    }
    else if (switch_value == 5.0) {
      return flight::String("Friday");
    }
    else if (switch_value == 6.0) {
      return flight::String("Saturday");
    }
    else {
      return flight::String("Unknown");
    }
  }
  throw std::logic_error("Flight function completed without a value");
}

inline flight::String classify_char(double code) {
  if (((code >= 48.0) && (code <= 57.0))) {
    return flight::String("digit");
  }
  if (((code >= 65.0) && (code <= 90.0))) {
    return flight::String("upper");
  }
  if (((code >= 97.0) && (code <= 122.0))) {
    return flight::String("lower");
  }
  return flight::String("other");
}

} // namespace flighthq_golden
