// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringComparison.ts#StringComparison. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline bool is_equal(flight::String a, flight::String b) {
  return (a == b);
}

inline bool is_not_equal(flight::String a, flight::String b) {
  return (a != b);
}

inline bool is_empty(flight::String text) {
  return (static_cast<double>(text.length()) == 0.0);
}

inline bool longer_than(flight::String text, double threshold) {
  return (static_cast<double>(text.length()) > threshold);
}

inline flight::String match_or_default(flight::String text, flight::String expected, flight::String fallback) {
  if ((text == expected)) {
    return text;
  }
  return fallback;
}

} // namespace flighthq_golden
