// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringComparison.ts#StringComparison. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

bool is_equal(std::string a, std::string b) {
  return (a == b);
}

bool is_not_equal(std::string a, std::string b) {
  return (a != b);
}

bool is_empty(std::string text) {
  return (static_cast<double>(text.size()) == 0.0);
}

bool longer_than(std::string text, double threshold) {
  return (static_cast<double>(text.size()) > threshold);
}

std::string match_or_default(std::string text, std::string expected, std::string fallback) {
  if ((text == expected)) {
    return text;
  }
  return fallback;
}

} // namespace flighthq_golden
