// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringAccumulate.ts#StringAccumulate. Do not edit.
package flighthq.golden;

function join(parts:Array<String>, separator:String):String {
  if (parts.length == 0) {
    return "";
  }
  var result:String = parts[0];
  {
    var i:Float = 1;
    while (i < parts.length) {
      {
        result = ((result + separator) + parts[Std.int(i)]);
      }
      i += 1;
    }
  }
  return result;
}

function repeat(text:String, count:Float):String {
  var result:String = "";
  {
    var i:Float = 0;
    while (i < count) {
      {
        result = (result + text);
      }
      i += 1;
    }
  }
  return result;
}

function wrap(text:String, before:String, after:String):String {
  return (before + text) + after;
}

function padLeft(text:String, width:Float, fill:String):String {
  var result:String = text;
  while (result.length < width) {
    result = (fill + result);
  }
  return result;
}
