// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mutatedParameter.ts#MutatedParameter. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Cell {
  double value;
};

inline void bump(Cell cell, double next) {
  cell.value = next;
}

inline void bump_twice(Cell cell) {
  bump(cell, 1.0);
  bump(cell, 2.0);
}

inline void fill(flight::Array<double> out, double value) {
  out.push(value);
}

} // namespace flighthq_golden
