// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayForOfProduct.ts#ArrayForOfProduct. Do not edit.
#![forbid(unsafe_code)]

pub fn product(values: Vec<f64>) -> f64 {
  let mut result: f64 = 1.0;
  for value in values {
    result *= value;
  }
  return result;
}

pub fn max(values: Vec<f64>) -> f64 {
  let mut best: f64 = values[0].clone();
  for value in values {
    if value > best {
      best = value;
    }
  }
  return best;
}

pub fn count_positive(values: Vec<f64>) -> f64 {
  let mut count: f64 = 0.0;
  for value in values {
    if value > 0.0 {
      count += 1.0;
    }
  }
  return count;
}

pub fn sum_absolute(values: Vec<f64>) -> f64 {
  let mut total: f64 = 0.0;
  for value in values {
    total += f64::abs(value);
  }
  return total;
}
