// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringCoercion.ts#StringCoercion. Do not edit.
#![forbid(unsafe_code)]

pub fn number_to_string(value: f64) -> String {
  return format!("{}", value);
}

pub fn boolean_to_string(value: bool) -> String {
  return format!("{}", value);
}

pub fn concat_number_string(n: f64, s: String) -> String {
  return format!("{}{}", format!("{}", n), s);
}

pub fn format_decimal(value: f64, label: String) -> String {
  return format!("{}: {}", label, format!("{}", value));
}
