// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/literalUnion.ts#LiteralUnion. Do not edit.
#![forbid(unsafe_code)]

pub type Lane = String;

#[derive(Clone, Debug)]
pub struct Route {
  pub lane: Lane,
  pub cost: f64,
}

pub fn is_fast(route: Route) -> bool {
  return route.lane == "fast".to_owned();
}

pub fn lane_name(route: Route) -> String {
  return route.lane;
}

pub fn describe(lane: Lane) -> String {
  return if (lane == "fast".to_owned()) { "quick".to_owned() } else { "careful".to_owned() };
}
