// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arithmeticPrecedence.ts#ArithmeticPrecedence. Do not edit.
package flighthq.golden;

function addMul(a:Float, b:Float, c:Float):Float {
  return a + (b * c);
}

function mulAdd(a:Float, b:Float, c:Float):Float {
  return (a * b) + c;
}

function groupedAdd(a:Float, b:Float, c:Float):Float {
  return (a + b) * c;
}

function mixedOps(a:Float, b:Float, c:Float, d:Float):Float {
  return (a * b) + (c / d);
}

function nestedGroups(a:Float, b:Float, c:Float):Float {
  return (a + b) * (b + c);
}
