// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayLiteral.ts#ArrayLiteral. Do not edit.
#pragma once
#include <vector>

namespace flighthq_golden {

std::vector<double> single_element() {
  return std::vector{42.0};
}

std::vector<double> three_elements() {
  return std::vector{1.0, 2.0, 3.0};
}

std::vector<double> empty_array() {
  return std::vector{};
}

std::vector<double> computed(double a, double b) {
  return std::vector{a, b, (a + b), (a * b)};
}

std::vector<std::vector<double>> nested(double x) {
  return std::vector{std::vector{x}, std::vector{(x + 1.0), (x + 2.0)}};
}

} // namespace flighthq_golden
