// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeNamespace.ts#TypeNamespace. Do not edit.
#![forbid(unsafe_code)]

pub fn get_default_name() -> String {
  return "default".to_owned();
}

pub fn get_default_value() -> f64 {
  return 0.0;
}
