// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/objectBinding.ts#ObjectBinding. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Shape = { other:Bool, value:Float };

function project(parameterPatternValue:Shape, source:Shape):Float {
  var value:Float = js.Syntax.code("undefined");
  final objectPatternValue:Shape = parameterPatternValue;
  (value = objectPatternValue.value);
  var assigned:Float = 0;
  {
    final destructuringAssignmentValue:Shape = source;
    (assigned = destructuringAssignmentValue.value);
  }
  return value + assigned;
}
