// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericConversion.ts#NumericConversion. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double clamp_value(double value, double min, double max) {
  if ((value < min)) {
    return min;
  }
  if ((value > max)) {
    return max;
  }
  return value;
}

inline double lerp(double start, double end, double t) {
  return (start + ((end - start) * t));
}

inline double round_to_places(double value, double places) {
  const double factor = flight::power(10.0, places);
  return (flight::round((value * factor)) / factor);
}

inline double average(flight::Array<double> values) {
  const double count = static_cast<double>(values.size());
  if ((count == 0.0)) {
    return 0.0;
  }
  double sum = 0.0;
  for (auto value : values) {
    sum = (sum + value);
  }
  return (sum / count);
}

} // namespace flighthq_golden
