// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/structuralAssertionOwnerUnproven.ts#StructuralAssertionOwnerUnproven. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Node = { id:String };

typedef DerivedNode = { id:String, extra:Float };

function widen(node:Node):DerivedNode {
  return (cast node : DerivedNode);
}
