// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/closureReturn.ts#ClosureReturn. Do not edit.
#pragma once
#include <functional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline std::function<double(double)> make_adder(double base) {
  return [=](double x) { return (base + x); };
}

inline flight::Array<double> apply_to_each(flight::Array<double> values, std::function<double(double)> transform) {
  return values.map(transform);
}

inline std::function<double(double)> compose(std::function<double(double)> f, std::function<double(double)> g) {
  return [=](double x) { return f(g(x)); };
}

} // namespace flighthq_golden
