// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedClosure.ts#NestedClosure. Do not edit.
#pragma once
#include <functional>
#include <memory>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline std::function<double()> create_counter(double initial) {
  const auto count_capture = std::make_shared<double>(initial);
  return [=]() {
  (*count_capture) = ((*count_capture) + 1.0);
  return (*count_capture);
};
}

inline double apply_twice(double value, std::function<double(double)> transform) {
  return transform(transform(value));
}

inline flight::Array<flight::String> filter_and_map(flight::Array<double> items, double threshold) {
  return items.filter([=](double item) { return (item > threshold); }).map([=](double item) { return flight::to_string(item); });
}

} // namespace flighthq_golden
