// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/tupleSpread.ts#TupleSpread. Do not edit.
#pragma once
#include <optional>
#include <tuple>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

using Pair = std::tuple<double, flight::String>;

inline Pair create_pair(double value, flight::String text) {
  Pair pair = std::make_tuple(value, text);
  return pair;
}

inline std::tuple<std::optional<bool>> create_optional() {
  std::tuple<std::optional<bool>> value = std::make_tuple(std::nullopt);
  return value;
}

inline std::tuple<double, double, flight::String, double, flight::String, std::optional<bool>> create_tuple_spread(Pair pair) {
  std::tuple<double, double, flight::String, double, flight::String, std::optional<bool>> value = ([&]() { auto tuple_spread_element = 0.0; auto tuple_spread_value = pair; auto tuple_spread_value_2 = create_pair(2.0, flight::String("flight")); auto tuple_spread_value_3 = create_optional(); return std::make_tuple(tuple_spread_element, std::get<0>(tuple_spread_value), std::get<1>(tuple_spread_value), std::get<0>(tuple_spread_value_2), std::get<1>(tuple_spread_value_2), std::get<0>(tuple_spread_value_3)); })();
  create_pair(std::get<0>(pair), std::get<1>(pair));
  return value;
}

} // namespace flighthq_golden
