// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/tupleSpread.ts#TupleSpread. Do not edit.
#pragma once
#include <optional>
#include <string>
#include <tuple>

namespace flighthq_golden {

using Pair = std::tuple<double, std::string>;

Pair create_pair(double value, std::string text) {
  const Pair pair = std::make_tuple(value, text);
  return pair;
}

std::tuple<std::optional<bool>> create_optional() {
  const std::tuple<std::optional<bool>> value = std::make_tuple(std::nullopt);
  return value;
}

std::tuple<double, double, std::string, double, std::string, std::optional<bool>> create_tuple_spread(Pair pair) {
  const std::tuple<double, double, std::string, double, std::string, std::optional<bool>> value = ([&]() { auto tuple_spread_element = 0.0; auto tuple_spread_value = pair; auto tuple_spread_value_2 = create_pair(2.0, "flight"); auto tuple_spread_value_3 = create_optional(); return std::make_tuple(tuple_spread_element, std::get<0>(tuple_spread_value), std::get<1>(tuple_spread_value), std::get<0>(tuple_spread_value_2), std::get<1>(tuple_spread_value_2), std::get<0>(tuple_spread_value_3)); })();
  create_pair(std::get<0>(pair), std::get<1>(pair));
  return value;
}

} // namespace flighthq_golden
