// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/discriminatedUnion.ts#DiscriminatedUnion. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct Circle {
  pub kind: String,
  pub radius: f64,
}

#[derive(Clone, Debug)]
pub struct Square {
  pub kind: String,
  pub side: f64,
}

#[derive(Clone, Debug)]
pub enum Shape {
  Circle(Circle),
  Square(Square),
}

impl Shape {
  pub fn as_circle(&self) -> &Circle {
    match self {
      Shape::Circle(value) => value,
      _ => panic!("Shape is not Circle"),
    }
  }
  pub fn as_square(&self) -> &Square {
    match self {
      Shape::Square(value) => value,
      _ => panic!("Shape is not Square"),
    }
  }
  pub fn kind(&self) -> String {
    match self {
      Shape::Circle(value) => value.kind.clone(),
      Shape::Square(value) => value.kind.clone(),
    }
  }
}

pub fn area(shape: Shape) -> f64 {
  if (shape.kind() == "circle".to_owned()) {
    return ((shape.as_circle().radius * shape.as_circle().radius) * 3.0);
  }
  return (shape.as_square().side * shape.as_square().side);
}
