// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mathMembers.ts#MathMembers. Do not edit.
#![forbid(unsafe_code)]

pub fn widest(first: f64, second: f64) -> f64 {
  return f64::max(first, f64::abs(second));
}
