// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeofPresenceGuard.ts#TypeofPresenceGuard. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Texture;

struct Texture : public flight::ReferenceEnabled {
  double size;
  flight::String name;
};

inline std::optional<flight::Ref<Texture>> read() {
  return std::nullopt;
}

inline double size_when_present() {
  auto texture = read();
  if (texture.has_value()) {
    return texture.value()->size;
  }
  return 0.0;
}

inline double size_when_absent() {
  auto texture = read();
  if (!(texture.has_value())) {
    return 0.0;
  }
  return texture.value()->size;
}

} // namespace flighthq_golden
