// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/guardClause.ts#GuardClause. Do not edit.
#![forbid(unsafe_code)]

pub fn safe_sqrt(value: f64) -> f64 {
  if value < 0.0 {
    return -1.0;
  }
  return f64::sqrt(value);
}

pub fn classify(value: f64) -> String {
  if value != value {
    return "nan".to_owned();
  }
  if value == 0.0 {
    return "zero".to_owned();
  }
  if value < 0.0 {
    return "negative".to_owned();
  }
  if value < 1.0 {
    return "fraction".to_owned();
  }
  return "positive".to_owned();
}

pub fn first_positive(values: Vec<f64>) -> f64 {
  for value in values {
    if value > 0.0 {
      return value;
    }
  }
  return -1.0;
}

pub fn bounded_sum(values: Vec<f64>, limit: f64) -> f64 {
  let mut total: f64 = 0.0;
  for value in values {
    if (total + value) > limit {
      return total;
    }
    total = total + value;
  }
  return total;
}
