// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/whileAccumulator.ts#WhileAccumulator. Do not edit.
#![forbid(unsafe_code)]

pub fn sum_up_to(limit: f64) -> f64 {
  let mut sum: f64 = 0.0;
  let mut i: f64 = 1.0;
  while i <= limit {
    sum += i;
    i += 1.0;
  }
  return sum;
}

pub fn digit_sum(value: f64) -> f64 {
  let mut n: f64 = f64::abs(value);
  let mut sum: f64 = 0.0;
  while n > 0.0 {
    sum += n % 10.0;
    n = f64::floor((n / 10.0));
  }
  return sum;
}

pub fn count_digits(value: f64) -> f64 {
  if value == 0.0 {
    return 1.0;
  }
  let mut n: f64 = f64::abs(value);
  let mut count: f64 = 0.0;
  while n > 0.0 {
    n = f64::floor((n / 10.0));
    count += 1.0;
  }
  return count;
}

pub fn collatz_steps(start: f64) -> f64 {
  let mut n: f64 = start;
  let mut steps: f64 = 0.0;
  while n != 1.0 {
    if (n % 2.0) == 0.0 {
      n = n / 2.0;
    }
    else {
      n = (3.0 * n) + 1.0;
    }
    steps += 1.0;
  }
  return steps;
}
