// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayChain.ts#ArrayChain. Do not edit.
#![forbid(unsafe_code)]

pub fn sum_positive(values: Vec<f64>) -> f64 {
  return values.into_iter().filter(|&v| v > 0.0).collect::<Vec<_>>().into_iter().fold(0.0, |acc, v| acc + v);
}

pub fn double_evens(values: Vec<f64>) -> Vec<f64> {
  return values.into_iter().filter(|&v| (v % 2.0) == 0.0).collect::<Vec<_>>().into_iter().map(|v| v * 2.0).collect::<Vec<_>>();
}

pub fn has_large_positive(values: Vec<f64>) -> bool {
  return values.into_iter().filter(|&v| v > 0.0).collect::<Vec<_>>().into_iter().any(|v| v > 100.0);
}

pub fn count_matching(values: Vec<f64>, threshold: f64) -> f64 {
  return values.into_iter().filter(|&v| v > threshold).collect::<Vec<_>>().len() as f64;
}
