// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/bitwiseOperation.ts#BitwiseOperation. Do not edit.
#![forbid(unsafe_code)]

pub fn bitwise_and(a: f64, b: f64) -> f64 {
  return ((a as i32) & (b as i32)) as f64;
}

pub fn bitwise_or(a: f64, b: f64) -> f64 {
  return ((a as i32) | (b as i32)) as f64;
}

pub fn bitwise_xor(a: f64, b: f64) -> f64 {
  return ((a as i32) ^ (b as i32)) as f64;
}

pub fn left_shift(value: f64, bits: f64) -> f64 {
  return ((value as i32) << (bits as i32)) as f64;
}

pub fn right_shift(value: f64, bits: f64) -> f64 {
  return ((value as i32) >> (bits as i32)) as f64;
}

pub fn bitwise_not(value: f64) -> f64 {
  return !(value as i32) as f64;
}
