// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/firstReplacement.ts#FirstReplacement. Do not edit.
package flighthq.golden;

function swapped(text:String):String {
  return flighthq._internal._StringTools.replaceFirst(text, "a", "b");
}
