// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/assertionClassOneValueNarrowing.ts#AssertionClassOneValueNarrowing. Do not edit.
#pragma once
#include <memory>
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct BaseShape;
struct DerivedShape;

struct BaseShape : public flight::ReferenceEnabled {
  flight::String id = flight::String("");
  virtual ~BaseShape() = default;
};

struct DerivedShape : public BaseShape {
  double extra = 0.0;
};

inline std::optional<flight::Ref<DerivedShape>> narrow(std::optional<flight::Ref<BaseShape>> value) {
  return std::static_pointer_cast<DerivedShape>(value.value());
}

} // namespace flighthq_golden
