// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/closureCapture.ts#ClosureCapture. Do not edit.
#![forbid(unsafe_code)]

use std::rc::Rc;

pub fn counter() -> Rc<dyn Fn() -> f64> {
  let mut count: f64 = 0.0;
  return Rc::new(|| {
  count += 1.0;
  return count;
});
}

pub fn accumulate(values: Vec<f64>) -> f64 {
  let mut total: f64 = 0.0;
  let add: Rc<dyn Fn(f64) -> ()> = Rc::new(|n| {
  total += n;
});
  for v in values {
    add(v);
  }
  return total;
}

pub fn make_multiplier(factor: f64) -> Rc<dyn Fn(f64) -> f64> {
  return Rc::new(|x| x * factor);
}
