// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringCoercion.ts#StringCoercion. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

std::string number_to_string(double value) {
  return std::string("") + std::to_string(value) + std::string("");
}

std::string boolean_to_string(bool value) {
  return std::string("") + std::to_string(value) + std::string("");
}

std::string concat_number_string(double n, std::string s) {
  return std::string("") + std::to_string(n) + std::string("") + s;
}

std::string format_decimal(double value, std::string label) {
  return label + ": " + std::string("") + std::to_string(value) + std::string("");
}

} // namespace flighthq_golden
