// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringCoercion.ts#StringCoercion. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline flight::String number_to_string(double value) {
  return flight::String("") + flight::to_string(value) + flight::String("");
}

inline flight::String boolean_to_string(bool value) {
  return flight::String("") + flight::to_string(value) + flight::String("");
}

inline flight::String concat_number_string(double n, flight::String s) {
  return flight::String("") + flight::to_string(n) + flight::String("") + s;
}

inline flight::String format_decimal(double value, flight::String label) {
  return label + flight::String(": ") + flight::String("") + flight::to_string(value) + flight::String("");
}

} // namespace flighthq_golden
