// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringNormalize.ts#StringNormalize. Do not edit.
#![forbid(unsafe_code)]

pub fn trim_and_lower(text: String) -> String {
  return text.trim().to_owned().to_lowercase();
}

pub fn is_palindrome(text: String) -> bool {
  let lower: String = text.to_lowercase();
  let len: f64 = lower.len() as f64;
  let mut i: f64 = 0.0;
  while i < (len / 2.0) {
    if lower.chars().nth(i as usize).map(|c| c.to_string()).unwrap_or_default() != lower.chars().nth(((len - 1.0) - i) as usize).map(|c| c.to_string()).unwrap_or_default() {
      return false;
    }
    i = i + 1.0;
  }
  return true;
}

pub fn has_prefix(text: String, prefix: String) -> bool {
  return text.starts_with(&prefix) && ((text.len() as f64) > (prefix.len() as f64));
}

pub fn replace_first(text: String, from: String, to: String) -> String {
  return text.replacen(&from, &to, 1);
}
