// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mapOperations.ts#MapOperations. Do not edit.
#![forbid(unsafe_code)]

pub fn contains(entries: std::collections::HashMap<String, f64>, key: String) -> bool {
  return entries.contains_key(&key);
}

pub fn count(entries: std::collections::HashMap<String, f64>) -> f64 {
  return entries.len() as f64;
}

pub fn insert(entries: &mut std::collections::HashMap<String, f64>, key: String, value: f64) -> () {
  entries.insert(key, value);
}

pub fn remove(entries: &mut std::collections::HashMap<String, f64>, key: String) -> bool {
  return entries.remove(key);
}

pub fn set_contains(values: std::collections::HashSet<String>, item: String) -> bool {
  return values.contains(&item);
}

pub fn set_size(values: std::collections::HashSet<String>) -> f64 {
  return values.len() as f64;
}

pub fn set_add(values: &mut std::collections::HashSet<String>, item: String) -> () {
  values.insert(item);
}
