// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedTernary.ts#NestedTernary. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline flight::String classify(double value) {
  return ((value > 0.0) ? flight::String("positive") : ((value < 0.0) ? flight::String("negative") : flight::String("zero")));
}

inline flight::String letter_grade(double score) {
  return ((score >= 90.0) ? flight::String("A") : ((score >= 80.0) ? flight::String("B") : ((score >= 70.0) ? flight::String("C") : flight::String("F"))));
}

inline double clamp_range(double value, double low, double high) {
  return ((value < low) ? low : ((value > high) ? high : value));
}

inline double min_of_three(double a, double b, double c) {
  return ((a < b) ? ((a < c) ? a : c) : ((b < c) ? b : c));
}

} // namespace flighthq_golden
