// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedTernary.ts#NestedTernary. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

std::string classify(double value) {
  return ((value > 0.0) ? "positive" : ((value < 0.0) ? "negative" : "zero"));
}

std::string letter_grade(double score) {
  return ((score >= 90.0) ? "A" : ((score >= 80.0) ? "B" : ((score >= 70.0) ? "C" : "F")));
}

double clamp_range(double value, double low, double high) {
  return ((value < low) ? low : ((value > high) ? high : value));
}

double min_of_three(double a, double b, double c) {
  return ((a < b) ? ((a < c) ? a : c) : ((b < c) ? b : c));
}

} // namespace flighthq_golden
