// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/restParameter.ts#RestParameter. Do not edit.
package flighthq.golden;

function sum(...values:Float):Float {
  var total:Float = 0;
  for (value in values) {
    total += value;
  }
  return total;
}

function counted(...items:Float):Float {
  return items.length;
}
