// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/restParameter.ts#RestParameter. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function sum(...values:Float):Float {
  final valuesArray:Array<Float> = values.toArray();
  var total:Float = 0;
  for (value in valuesArray) {
    (total += value);
  }
  return total;
}

function counted(...items:Float):Float {
  final itemsArray:Array<Float> = items.toArray();
  return itemsArray.length;
}
