// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/parameterReuse.ts#ParameterReuse. Do not edit.
#![forbid(unsafe_code)]

pub fn spread(value: f64) -> f64 {
  return ((value * value) + value) + value;
}

pub fn mirror(text: String) -> String {
  let reversed: String = text.split("").map(|s| s.to_string()).collect::<Vec<String>>().reverse().join("");
  return format!("{}{}", text, reversed);
}

pub fn clamp_and_scale(value: f64, lo: f64, hi: f64) -> f64 {
  let clamped: f64 = if (value < lo) { lo } else { if (value > hi) { hi } else { value } };
  return (clamped - lo) / (hi - lo);
}

pub fn repeat_join(text: String, count: f64, separator: String) -> String {
  let mut result: String = text.clone();
  {
    let mut i: f64 = 1.0;
    while i < count {
      {
        result = format!("{}{}{}", result, separator, text);
      }
      i += 1.0;
    }
  }
  return result;
}
