// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unguardedVariantMemberRefused.ts#UnguardedVariantMemberRefused. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef AsepriteFrame = { x:Float, y:Float };

typedef TexturePackerFrame = { filename:String };

typedef AsepriteAtlas = { frames:Array<AsepriteFrame>, meta:{ app:String } };

typedef TexturePackerAtlas = { frames:Array<TexturePackerFrame>, meta:{ size:Float } };

typedef Atlas = Dynamic;

function frameCount(atlas:Atlas):Float {
  return atlas.frames.length;
}
