// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericSemantics.ts#NumericSemantics. Do not edit.
#pragma once
#include <cmath>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double half(double value) {
  return (value / 2.0);
}

inline double remainder(double value, double divisor) {
  return std::fmod(value, divisor);
}

inline double accumulate(double steps) {
  double total = 0.0;
  {
    double index = 0.0;
    while ((index < steps)) {
      {
        total += 0.1;
      }
      index += 1.0;
    }
  }
  return total;
}

inline double scaled(double value) {
  return ((value * 3.0) - 1.0);
}

} // namespace flighthq_golden
