// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/erasedValueUnionSelection.ts#ErasedValueUnionSelection. Do not edit.
#pragma once
#include <flight/any.hpp>
#include <optional>
#include <stdexcept>
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Payload;

struct Payload : public flight::ReferenceEnabled {
  flight::String id;
};

inline std::optional<std::variant<double, flight::String>> entry(flight::Any payload) {
  return ([&]() -> std::optional<std::variant<double, flight::String>> { const auto& erased_value = payload; if (erased_value.kind() == flight::AnyKind::number) return std::optional<std::variant<double, flight::String>>{std::in_place, std::in_place_type<double>, erased_value.as_number()}; if (erased_value.kind() == flight::AnyKind::string) return std::optional<std::variant<double, flight::String>>{std::in_place, std::in_place_type<flight::String>, erased_value.as_string()}; if (erased_value.is_nullish()) return std::nullopt; throw std::logic_error("erased value holds no alternative this union represents"); }());
}

inline std::variant<flight::Ref<Payload>, double> object_entry(flight::Any payload) {
  return ([&]() -> std::variant<flight::Ref<Payload>, double> { const auto& erased_value_2 = payload; if (static_cast<bool>(erased_value_2.object_if<Payload>())) return std::variant<flight::Ref<Payload>, double>{std::in_place_type<flight::Ref<Payload>>, erased_value_2.object_if<Payload>()}; if (erased_value_2.kind() == flight::AnyKind::number) return std::variant<flight::Ref<Payload>, double>{std::in_place_type<double>, erased_value_2.as_number()}; throw std::logic_error("erased value holds no alternative this union represents"); }());
}

inline std::variant<double, flight::String> contextual(flight::Any payload) {
  return ([&]() -> std::variant<double, flight::String> { const auto& erased_value_3 = payload; if (erased_value_3.kind() == flight::AnyKind::number) return std::variant<double, flight::String>{std::in_place_type<double>, erased_value_3.as_number()}; if (erased_value_3.kind() == flight::AnyKind::string) return std::variant<double, flight::String>{std::in_place_type<flight::String>, erased_value_3.as_string()}; throw std::logic_error("erased value holds no alternative this union represents"); }());
}

inline double accept(std::variant<double, flight::String> payload) {
  return 1.0;
}

inline double pass(flight::Any payload) {
  return accept(([&]() -> std::variant<double, flight::String> { const auto& erased_value_4 = payload; if (erased_value_4.kind() == flight::AnyKind::number) return std::variant<double, flight::String>{std::in_place_type<double>, erased_value_4.as_number()}; if (erased_value_4.kind() == flight::AnyKind::string) return std::variant<double, flight::String>{std::in_place_type<flight::String>, erased_value_4.as_string()}; throw std::logic_error("erased value holds no alternative this union represents"); }()));
}

} // namespace flighthq_golden
