// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/moduleFacade.ts#ModuleFacade. Do not edit.
#pragma once

namespace flighthq_golden {

double local(double value) {
  return value;
}

} // namespace flighthq_golden
