// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedClosure.ts#NestedClosure. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function createCounter(initial:Float):()->Float {
  var count:Float = initial;
  return cast(function():Float {
  (count = (count + 1));
  return count;
});
}

function applyTwice(value:Float, transform:(Float)->Float):Float {
  return transform(transform(value));
}

function filterAndMap(items:Array<Float>, threshold:Float):Array<String> {
  return items.filter(cast(function(item:Float) return (item > threshold))).map(cast(function(item:Float) return flighthq._internal._Number.toString(item)));
}
