// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/finallyReturnAwait.ts#FinallyReturnAwait. Do not edit.
#pragma once
#include <coroutine>
#include <exception>
#include <optional>
#include <stdexcept>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::Task<double> attempt(flight::Task<double> task, flight::Array<double> log) {
  std::optional<double> finally_return;
  std::exception_ptr finally_exception;
  try {
    finally_return = co_await task;
  }
  catch (...) {
    finally_exception = std::current_exception();
  }
  log.push(1.0);
  if (finally_exception) std::rethrow_exception(finally_exception);
  if (finally_return.has_value()) co_return finally_return.value();
  co_await std::suspend_never{};
  throw std::logic_error("Flight async function completed without a value");
}

} // namespace flighthq_golden
