// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/finallyReturnAwait.ts#FinallyReturnAwait. Do not edit.
#pragma once
#include <coroutine>
#include <exception>
#include <optional>
#include <vector>

namespace flighthq_golden {

FlightTask<double> attempt(FlightTask<double> task, std::vector<double> log) {
  std::optional<double> finally_return;
  std::exception_ptr finally_exception;
  try {
    finally_return = co_await task;
  }
  catch (...) {
    finally_exception = std::current_exception();
  }
  log.push_back(1.0);
  if (finally_exception) std::rethrow_exception(finally_exception);
  if (finally_return.has_value()) co_return finally_return.value();
}

} // namespace flighthq_golden
