// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericLoop.ts#NumericLoop. Do not edit.
#pragma once
#include <cmath>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double factorial(double n) {
  double result = 1.0;
  {
    double i = 2.0;
    while ((i <= n)) {
      {
        result *= i;
      }
      i += 1.0;
    }
  }
  return result;
}

inline double fibonacci(double n) {
  double a = 0.0;
  double b = 1.0;
  {
    double i = 0.0;
    while ((i < n)) {
      {
        const double next = (a + b);
        a = b;
        b = next;
      }
      i += 1.0;
    }
  }
  return a;
}

inline double gcd(double a, double b) {
  double x = a;
  double y = b;
  while ((y != 0.0)) {
    const double temp = y;
    y = std::fmod(x, temp);
    x = temp;
  }
  return x;
}

inline double power(double base, double exp) {
  double result = 1.0;
  {
    double i = 0.0;
    while ((i < exp)) {
      {
        result *= base;
      }
      i += 1.0;
    }
  }
  return result;
}

} // namespace flighthq_golden
