// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/blockScope.ts#BlockScope. Do not edit.
#![forbid(unsafe_code)]

pub fn scoped_accumulate(values: Vec<f64>) -> f64 {
  let mut result: f64 = 0.0;
  for value in values {
    let doubled: f64 = value * 2.0;
    result = result + doubled;
  }
  return result;
}

pub fn nested_scope(x: f64) -> f64 {
  let mut result: f64 = x;
  if x > 0.0 {
    let temp: f64 = result * 2.0;
    result = temp + 1.0;
  }
  else {
    let temp_2: f64 = result * 3.0;
    result = temp_2 - 1.0;
  }
  return result;
}

pub fn multiple_bindings(a: f64, b: f64) -> f64 {
  let sum: f64 = a + b;
  let product: f64 = a * b;
  let diff: f64 = a - b;
  return (sum + product) + diff;
}
