// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nullability.ts#Nullability. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double widen(std::optional<double> value, double fallback) {
  if (!value.has_value()) {
    return fallback;
  }
  return value.value();
}

inline flight::String label(std::optional<flight::String> name) {
  return (!name.has_value() ? flight::String("none") : name.value());
}

} // namespace flighthq_golden
