// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayQueue.ts#ArrayQueue. Do not edit.
package flighthq.golden;

function dequeue(items:Array<Float>):Float {
  return items.shift();
}

function enqueue(items:Array<Float>, value:Float):Void {
  items.push(value);
}

function prepend(items:Array<String>, value:String):Void {
  items.unshift(value);
}

function rotateFirst(items:Array<Float>):Void {
  final first:Float = items.shift();
  items.push(first);
}
