// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/awaitConditionAwait.ts#AwaitConditionAwait. Do not edit.
#pragma once
#include <coroutine>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline flight::Task<double> decide(flight::Task<bool> task) {
  double total = 0.0;
  {
    auto await_condition = co_await task;
    if (await_condition) {
      total = 1.0;
    }
    else {
      total = 2.0;
    }
  }
  co_return total;
}

} // namespace flighthq_golden
