// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/doWhileLoop.ts#DoWhileLoop. Do not edit.
#pragma once
#include <cmath>
#include <cstdint>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double collatz(double n) {
  double steps = 0.0;
  double current = n;
  while ((current != 1.0)) {
    if (((current - (2.0 * std::floor((current / 2.0)))) == 0.0)) {
      current = (current / 2.0);
    }
    else {
      current = ((3.0 * current) + 1.0);
    }
    steps = (steps + 1.0);
  }
  return steps;
}

inline double digit_sum(double n) {
  double sum = 0.0;
  double remaining = std::abs(n);
  while ((remaining > 0.0)) {
    sum = (sum + (remaining - (10.0 * std::floor((remaining / 10.0)))));
    remaining = std::floor((remaining / 10.0));
  }
  return sum;
}

inline double gcd(double a, double b) {
  double x = std::abs(a);
  double y = std::abs(b);
  while ((y != 0.0)) {
    const double temp = y;
    y = (x - (y * std::floor((x / y))));
    x = temp;
  }
  return x;
}

} // namespace flighthq_golden
