// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/negatedCondition.ts#NegatedCondition. Do not edit.
#![forbid(unsafe_code)]

pub fn unless(condition: bool, value: f64) -> f64 {
  if !condition {
    return value;
  }
  return 0.0;
}

pub fn neither(a: bool, b: bool) -> bool {
  return !a && !b;
}

pub fn nand(a: bool, b: bool) -> bool {
  return !(a && b);
}

pub fn xor_manual(a: bool, b: bool) -> bool {
  return (a || b) && !(a && b);
}

pub fn clamp_positive(value: f64) -> f64 {
  if !(value > 0.0) {
    return 0.0;
  }
  return value;
}
