import ts from 'typescript';

// The published surface of `@flighthq/tool-compiler`, rendered as a committed report.
//
// The facade is cultivated by hand, so a name can enter or leave it as a side effect of an unrelated
// edit — a re-export added to a package index reaches the public API without anyone deciding it
// should. A committed report turns that into a reviewable diff instead of a silent change, which is
// what the repository's pre-release API posture asks for: every exported name is a candidate for the
// final form, so the set of them is worth seeing whole.
//
// The report records names and kinds, not signatures. A signature diff would churn on every internal
// type rename and train readers to approve the file without reading it; the set of exported names
// changes rarely and means something every time.

export type PublicApiKind = 'function' | 'type' | 'value';

export interface PublicApiExport {
  readonly kind: PublicApiKind;
  readonly name: string;
}

export function classifyPublicApiSymbol(symbol: ts.Symbol, checker: ts.TypeChecker): PublicApiKind {
  const resolved = symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
  if (resolved.flags & ts.SymbolFlags.Function) return 'function';
  return resolved.flags & ts.SymbolFlags.Value ? 'value' : 'type';
}

export function formatPublicApiReport(exports: readonly PublicApiExport[]): string {
  const sorted = [...exports].sort((left, right) => left.name.localeCompare(right.name));
  const counts = new Map<PublicApiKind, number>([
    ['function', 0],
    ['type', 0],
    ['value', 0],
  ]);
  for (const entry of sorted) counts.set(entry.kind, (counts.get(entry.kind) ?? 0) + 1);
  return [
    '# @flighthq/tool-compiler public API',
    '',
    'Generated by `npm run api`; verified by `npm run api:check`. Every change to this file is a change',
    'to the published surface, so review it as one.',
    '',
    `${String(sorted.length)} exports: ${String(counts.get('function') ?? 0)} functions, ${String(counts.get('value') ?? 0)} values, ${String(counts.get('type') ?? 0)} types.`,
    '',
    '| export | kind |',
    '| --- | --- |',
    ...sorted.map((entry) => `| \`${entry.name}\` | ${entry.kind} |`),
    '',
  ].join('\n');
}
