// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/voidReturn.ts#VoidReturn. Do not edit.
#![forbid(unsafe_code)]

pub fn apply_discount(prices: &mut Vec<f64>, factor: f64) -> () {
  {
    let mut i: f64 = 0.0;
    while i < (prices.len() as f64) {
      {
        prices[i as usize] = prices[i as usize] * factor;
      }
      i = i + 1.0;
    }
  }
}

pub fn clear_array(values: &mut Vec<f64>) -> () {
  while (values.len() as f64) > 0.0 {
    values.pop();
  }
}
