// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringConcat.ts#StringConcat. Do not edit.
package flighthq.golden;

function greetUser(name:String):String {
  return ("Hello, " + name) + "!";
}

function formatPair(key:String, value:Float):String {
  return (key + "=") + Std.string(value);
}

function repeat(text:String, count:Float):String {
  var result:String = "";
  {
    var i:Float = 0;
    while (i < count) {
      {
        result += text;
      }
      i += 1;
    }
  }
  return result;
}
