// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/functionComposition.ts#FunctionComposition. Do not edit.
package flighthq.golden;

function double(x:Float):Float {
  return x * 2;
}

function addOne(x:Float):Float {
  return x + 1;
}

function square(x:Float):Float {
  return x * x;
}

function doubleAndAdd(value:Float):Float {
  return addOne(double(value));
}

function squareOfDouble(value:Float):Float {
  return square(double(value));
}

function chainThree(value:Float):Float {
  return square(addOne(double(value)));
}

function sumOfSquares(a:Float, b:Float):Float {
  return square(a) + square(b);
}
