// Generated by @flighthq/tool-compiler. Do not edit.
package flighthq.golden;

class NameCollision {
  public static function fooBar(value:Float):Float {
    return value;
  }

  public static function foo_bar(value:Float):Float {
    return (value + 1);
  }
}
