// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unsignedShift.ts#UnsignedShift. Do not edit.
#pragma once
#include <cstdint>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double unsigned_shift_right(double value, double count) {
  return static_cast<double>(static_cast<uint32_t>(static_cast<int32_t>(value)) >> static_cast<uint32_t>(count));
}

inline double unsigned_shift_assign(double value, double count) {
  double result = value;
  result = count;
  return result;
}

inline double signed_vs_unsigned(double value) {
  const double signed_ = static_cast<double>(static_cast<int32_t>(value) >> static_cast<int32_t>(1.0));
  const double unsigned_ = static_cast<double>(static_cast<uint32_t>(static_cast<int32_t>(value)) >> static_cast<uint32_t>(1.0));
  return (signed_ + unsigned_);
}

} // namespace flighthq_golden
