// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/moduleFacade.ts#ModuleFacade. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef ModuleFacadeRound = flighthq.golden.Helper.Circle;
typedef ModuleFacadeShape = flighthq.golden.Helper.Shape;

function local(value:Float):Float {
  return value;
}
