// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/moduleFacade.ts#ModuleFacade. Do not edit.
package flighthq.golden;

typedef Round = flighthq.golden.Helper.Circle;

class ModuleFacade {
  public static function local(value:Float):Float {
    return value;
  }
}
