// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/loopJumpAwait.ts#LoopJumpAwait. Do not edit.
#pragma once
#include <coroutine>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::Task<double> drain(flight::Task<double> task, bool stop, bool skip) {
  double last = 0.0;
  while (true) {
    last = co_await task;
    if (skip) {
      continue;
    }
    if (stop) {
      break;
    }
  }
  co_return last;
}

} // namespace flighthq_golden
