// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeNamespace.ts#TypeNamespace. Do not edit.
package flighthq.golden;

function getDefaultName():String {
  return "default";
}

function getDefaultValue():Float {
  return 0;
}
