// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericTruncation.ts#NumericTruncation. Do not edit.
#pragma once

namespace flighthq_golden {

double round_down(double value) {
  return std::floor(value);
}

double round_up(double value) {
  return std::ceil(value);
}

double round_nearest(double value) {
  return std::round(value);
}

double fractional_part(double value) {
  return (value - std::floor(value));
}

double round_to_int(double value) {
  return std::floor((value + 0.5));
}

} // namespace flighthq_golden
