// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericTruncation.ts#NumericTruncation. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double round_down(double value) {
  return std::floor(value);
}

inline double round_up(double value) {
  return std::ceil(value);
}

inline double round_nearest(double value) {
  return flight::round(value);
}

inline double fractional_part(double value) {
  return (value - std::floor(value));
}

inline double round_to_int(double value) {
  return std::floor((value + 0.5));
}

} // namespace flighthq_golden
