// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/bitwiseNot.ts#BitwiseNot. Do not edit.
package flighthq.golden;

function complement(value:Float):Float {
  return ~ Std.int(value);
}

function extractLowByte(value:Float):Float {
  return Std.int(~ Std.int(value)) & Std.int(255);
}

function toggleSign(value:Float):Float {
  return ~ Std.int(value) + 1;
}

function maskAndComplement(value:Float, mask:Float):Float {
  return ~ Std.int((Std.int(value) & Std.int(mask)));
}
