// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/closureCapture.ts#ClosureCapture. Do not edit.
#pragma once
#include <functional>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline std::function<double()> counter() {
  double count = 0.0;
  return [=]() {
  count += 1.0;
  return count;
};
}

inline double accumulate(flight::Array<double> values) {
  double total = 0.0;
  std::function<void(double)> add = [=](double n) {
  total += n;
};
  for (double v : values) {
    add(v);
  }
  return total;
}

inline std::function<double(double)> make_multiplier(double factor) {
  return [=](double x) { return (x * factor); };
}

} // namespace flighthq_golden
