// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/nestedArray.ts#NestedArray. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double sum_row(flight::Array<flight::Array<double>> grid, double row) {
  double total = 0.0;
  for (auto value : grid.element(row)) {
    total += value;
  }
  return total;
}

inline flight::Array<double> flatten(flight::Array<flight::Array<double>> grid) {
  flight::Array<double> result = flight::Array<double>{};
  for (auto row : grid) {
    for (auto value : row) {
      result.push(value);
    }
  }
  return result;
}

inline flight::Array<flight::Array<double>> transpose(flight::Array<flight::Array<double>> grid) {
  const double rows = static_cast<double>(grid.size());
  const double cols = static_cast<double>(grid.element(0.0).size());
  flight::Array<flight::Array<double>> result = flight::Array<flight::Array<double>>{};
  {
    double c = 0.0;
    while ((c < cols)) {
      {
        flight::Array<double> row = flight::Array<double>{};
        {
          double r = 0.0;
          while ((r < rows)) {
            {
              row.push(grid.element(r).element(c));
            }
            r += 1.0;
          }
        }
        result.push(row);
      }
      c += 1.0;
    }
  }
  return result;
}

} // namespace flighthq_golden
