// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/errorConstruction.ts#ErrorConstruction. Do not edit.
#pragma once
#include <functional>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline void throw_message(flight::String message) {
  throw flight::Error(message);
}

inline flight::String try_catch(std::function<void()> action) {
  try {
    action();
    return flight::String("ok");
  }
  catch (...) {
    return flight::String("caught");
  }
}

} // namespace flighthq_golden
