// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/reassignment.ts#Reassignment. Do not edit.
#![forbid(unsafe_code)]

pub fn conditional_reassign(value: f64) -> String {
  let mut label: String = "zero".to_owned();
  if value > 0.0 {
    label = "positive".to_owned();
  }
  else {
    if value < 0.0 {
      label = "negative".to_owned();
    }
  }
  return label;
}

pub fn swap_values(a: f64, b: f64) -> f64 {
  let mut x: f64 = a;
  let mut y: f64 = b;
  let temp: f64 = x;
  x = y;
  y = temp;
  return x - y;
}

pub fn accumulate(values: Vec<f64>) -> f64 {
  let mut sum: f64 = 0.0;
  let mut count: f64 = 0.0;
  for v in values {
    sum += v;
    count += 1.0;
  }
  return sum + count;
}

pub fn narrow_down(max: f64) -> f64 {
  let mut result: f64 = max;
  while result > 1.0 {
    result = f64::floor((result / 2.0));
  }
  return result;
}
