// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/contextualUnionViewConversion.ts#ContextualUnionViewConversion. Do not edit.
#pragma once
#include <flight/structural_ref.hpp>
#include <stdexcept>
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Color;
struct Texture;

struct Color : public flight::ReferenceEnabled {
  double r;
  double g;
};

struct Texture : public flight::ReferenceEnabled {
  flight::String id;
};

inline std::variant<flight::Ref<Texture>, flight::Ref<Color>> pick(std::variant<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Texture>>>>, flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Color>>>>> value) {
  return ([&]() -> std::variant<flight::Ref<Texture>, flight::Ref<Color>> { const auto& converted_union = value; if (const auto* alternative = std::get_if<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Texture>>>>>(&converted_union)) return std::variant<flight::Ref<Texture>, flight::Ref<Color>>{std::in_place_type<flight::Ref<Texture>>, flight::structural_ref_cast<flight::Ref<Texture>>(*alternative)}; if (const auto* alternative = std::get_if<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Color>>>>>(&converted_union)) return std::variant<flight::Ref<Texture>, flight::Ref<Color>>{std::in_place_type<flight::Ref<Color>>, flight::structural_ref_cast<flight::Ref<Color>>(*alternative)}; throw std::logic_error("source union alternative is not a readonly view of one the destination names"); }());
}

} // namespace flighthq_golden
