// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringBuild.ts#StringBuild. Do not edit.
#![forbid(unsafe_code)]

pub fn reverse(text: String) -> String {
  let mut result: String = "".to_owned();
  {
    let mut i: f64 = (text.len() as f64) - 1.0;
    while i >= 0.0 {
      {
        result = format!("{}{}", result, text.chars().nth(i as usize).map(|c| c.to_string()).unwrap_or_default());
      }
      i -= 1.0;
    }
  }
  return result;
}

pub fn count_char(text: String, ch: String) -> f64 {
  let mut count: f64 = 0.0;
  {
    let mut i: f64 = 0.0;
    while i < (text.len() as f64) {
      {
        if text.chars().nth(i as usize).map(|c| c.to_string()).unwrap_or_default() == ch {
          count = count + 1.0;
        }
      }
      i += 1.0;
    }
  }
  return count;
}

pub fn truncate(text: String, max_length: f64) -> String {
  if (text.len() as f64) <= max_length {
    return text;
  }
  return format!("{}...", text[0.0 as usize..max_length as usize].to_string());
}
