// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arithmeticPrecedence.ts#ArithmeticPrecedence. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double add_mul(double a, double b, double c) {
  return (a + (b * c));
}

inline double mul_add(double a, double b, double c) {
  return ((a * b) + c);
}

inline double grouped_add(double a, double b, double c) {
  return ((a + b) * c);
}

inline double mixed_ops(double a, double b, double c, double d) {
  return ((a * b) + (c / d));
}

inline double nested_groups(double a, double b, double c) {
  return ((a + b) * (b + c));
}

} // namespace flighthq_golden
