// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/helper.ts#Helper. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function helper(value:Float):Float {
  return value + 1;
}
