// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/moduleValueFacade.ts#ModuleValueFacade. Do not edit.
package flighthq.golden;

function helper(value:Float):Float {
  return flighthq.golden.Helper.helper(value);
}
