// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unionAssignment.ts#UnionAssignment. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
enum StrOrF64 {
  Str(String),
  F64(f64),
}

impl StrOrF64 {
  fn as_str(&self) -> &String {
    match self {
      StrOrF64::Str(value) => value,
      _ => panic!("StrOrF64 is not Str"),
    }
  }
  fn as_f64(&self) -> &f64 {
    match self {
      StrOrF64::F64(value) => value,
      _ => panic!("StrOrF64 is not F64"),
    }
  }
}

impl std::fmt::Display for StrOrF64 {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    match self {
      StrOrF64::Str(value) => write!(f, "{}", value),
      StrOrF64::F64(value) => write!(f, "{}", value),
    }
  }
}

pub fn assign_string(text: String) -> StrOrF64 {
  let mut value: StrOrF64 = text;
  return value;
}

pub fn assign_number(n: f64) -> StrOrF64 {
  let mut value: StrOrF64 = n;
  return value;
}

pub fn reassign(flag: bool) -> StrOrF64 {
  let mut value: StrOrF64 = "start".to_owned();
  if flag {
    value = 42.0;
  }
  return value;
}

pub fn assign_null(text: Option<String>) -> String {
  if text.is_none() {
    return "none".to_owned();
  }
  return text.clone().unwrap();
}

pub fn assign_undefined(text: Option<String>) -> String {
  if text.is_none() {
    return "none".to_owned();
  }
  return text.clone().unwrap();
}

pub fn return_member(flag: bool) -> StrOrF64 {
  if flag {
    return "yes".to_owned();
  }
  return 0.0;
}
