// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/ternaryExpression.ts#TernaryExpression. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double clamp_value(double value, double low, double high) {
  return ((value < low) ? low : ((value > high) ? high : value));
}

inline double sign(double value) {
  return ((value > 0.0) ? 1.0 : ((value < 0.0) ? -1.0 : 0.0));
}

inline flight::String label(double count) {
  return ((count == 0.0) ? flight::String("none") : ((count == 1.0) ? flight::String("one") : flight::String("many")));
}

} // namespace flighthq_golden
