// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/multipleReturn.ts#MultipleReturn. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

double absolute_value(double value) {
  if ((value < 0.0)) {
    return -value;
  }
  return value;
}

std::string fizzbuzz(double n) {
  if (((n % 15.0) == 0.0)) {
    return "fizzbuzz";
  }
  if (((n % 3.0) == 0.0)) {
    return "fizz";
  }
  if (((n % 5.0) == 0.0)) {
    return "buzz";
  }
  return std::string("") + std::to_string(n) + std::string("");
}

double bounded_increment(double value, double max) {
  if ((value >= max)) {
    return max;
  }
  return (value + 1.0);
}

std::string triangle_type(double a, double b, double c) {
  if (((a == b) && (b == c))) {
    return "equilateral";
  }
  if ((((a == b) || (b == c)) || (a == c))) {
    return "isosceles";
  }
  return "scalene";
}

} // namespace flighthq_golden
