// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/negativeArithmetic.ts#NegativeArithmetic. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double negate(double value) {
  return -value;
}

inline double double_negate(double value) {
  return --value;
}

inline double subtract_from_zero(double value) {
  return (0.0 - value);
}

inline double negative_product(double a, double b) {
  return -(a * b);
}

inline double absolute_difference(double a, double b) {
  const double diff = (a - b);
  return ((diff < 0.0) ? -diff : diff);
}

} // namespace flighthq_golden
