// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/compoundAssignment.ts#CompoundAssignment. Do not edit.
#pragma once
#include <cmath>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double accumulate(double initial, double steps) {
  double value = initial;
  {
    double i = 0.0;
    while ((i < steps)) {
      {
        value += i;
      }
      i += 1.0;
    }
  }
  return value;
}

inline double scale(double base, double factor) {
  double result = base;
  result *= factor;
  return result;
}

inline double halve(double value) {
  double result = value;
  result /= 2.0;
  return result;
}

inline double remainder(double value, double divisor) {
  double result = value;
  ([&]() { auto&& assignment_target = result; assignment_target = std::fmod(assignment_target, divisor); return assignment_target; }());
  return result;
}

} // namespace flighthq_golden
