// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/collectionArgumentMatchingDomain.ts#CollectionArgumentMatchingDomain. Do not edit.
#pragma once
#include <optional>
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Alpha;
struct Beta;

struct Alpha : public flight::ReferenceEnabled {
  double value;
};

struct Beta : public flight::ReferenceEnabled {
  double other;
};

inline std::optional<std::variant<flight::Ref<Alpha>, flight::Ref<Beta>>> pick() {
  return std::nullopt;
}

inline flight::Set<std::variant<flight::Ref<Alpha>, flight::Ref<Beta>>> target = flight::Set<std::variant<flight::Ref<Alpha>, flight::Ref<Beta>>>();

inline flight::Map<flight::String, std::variant<flight::Ref<Alpha>, flight::Ref<Beta>>> lookup = flight::Map<flight::String, std::variant<flight::Ref<Alpha>, flight::Ref<Beta>>>();

inline void add() {
  std::optional<std::variant<flight::Ref<Alpha>, flight::Ref<Beta>>> found = pick();
  if (!found.has_value()) {
    return;
  }
  target.add(found.value());
}

inline void put(flight::String key) {
  std::optional<std::variant<flight::Ref<Alpha>, flight::Ref<Beta>>> value = pick();
  if (!value.has_value()) {
    return;
  }
  lookup.set(key, value.value());
}

} // namespace flighthq_golden
