// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/contextualUnionViewAbsence.ts#ContextualUnionViewAbsence. Do not edit.
#pragma once
#include <flight/structural_ref.hpp>
#include <optional>
#include <stdexcept>
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Color;
struct Texture;

struct Color : public flight::ReferenceEnabled {
  double r;
  double g;
};

struct Texture : public flight::ReferenceEnabled {
  flight::String id;
};

inline std::variant<flight::Ref<Texture>, flight::Ref<Color>, flight::Null, flight::Undefined> keep_absence(std::variant<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Texture>>>>, flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Color>>>>, flight::Null, flight::Undefined> value) {
  return ([&]() -> std::variant<flight::Ref<Texture>, flight::Ref<Color>, flight::Null, flight::Undefined> { const auto& converted_union = value; if (std::holds_alternative<flight::Null>(converted_union)) return std::variant<flight::Ref<Texture>, flight::Ref<Color>, flight::Null, flight::Undefined>{std::in_place_type<flight::Null>, flight::null}; if (std::holds_alternative<flight::Undefined>(converted_union)) return std::variant<flight::Ref<Texture>, flight::Ref<Color>, flight::Null, flight::Undefined>{std::in_place_type<flight::Undefined>, flight::undefined}; if (const auto* alternative = std::get_if<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Texture>>>>>(&converted_union)) return std::variant<flight::Ref<Texture>, flight::Ref<Color>, flight::Null, flight::Undefined>{std::in_place_type<flight::Ref<Texture>>, flight::structural_ref_cast<flight::Ref<Texture>>(*alternative)}; if (const auto* alternative = std::get_if<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Color>>>>>(&converted_union)) return std::variant<flight::Ref<Texture>, flight::Ref<Color>, flight::Null, flight::Undefined>{std::in_place_type<flight::Ref<Color>>, flight::structural_ref_cast<flight::Ref<Color>>(*alternative)}; throw std::logic_error("source union alternative is not a readonly view of one the destination names"); }());
}

inline std::variant<flight::Ref<Texture>, flight::Ref<Color>, flight::Null, flight::Undefined> from_present(std::variant<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Texture>>>>, flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Color>>>>> value) {
  return ([&]() -> std::variant<flight::Ref<Texture>, flight::Ref<Color>, flight::Null, flight::Undefined> { const auto& converted_union_2 = value; if (const auto* alternative = std::get_if<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Texture>>>>>(&converted_union_2)) return std::variant<flight::Ref<Texture>, flight::Ref<Color>, flight::Null, flight::Undefined>{std::in_place_type<flight::Ref<Texture>>, flight::structural_ref_cast<flight::Ref<Texture>>(*alternative)}; if (const auto* alternative = std::get_if<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Color>>>>>(&converted_union_2)) return std::variant<flight::Ref<Texture>, flight::Ref<Color>, flight::Null, flight::Undefined>{std::in_place_type<flight::Ref<Color>>, flight::structural_ref_cast<flight::Ref<Color>>(*alternative)}; throw std::logic_error("source union alternative is not a readonly view of one the destination names"); }());
}

inline std::optional<std::variant<flight::Ref<Texture>, flight::Ref<Color>>> from_optional(std::optional<std::variant<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Texture>>>>, flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Color>>>>>> value) {
  return ([&]() -> std::optional<std::variant<flight::Ref<Texture>, flight::Ref<Color>>> { const auto& converted_union_3 = value; if (!converted_union_3.has_value()) return std::nullopt; if (const auto* alternative = std::get_if<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Texture>>>>>(&converted_union_3.value())) return std::optional<std::variant<flight::Ref<Texture>, flight::Ref<Color>>>{std::in_place, std::in_place_type<flight::Ref<Texture>>, flight::structural_ref_cast<flight::Ref<Texture>>(*alternative)}; if (const auto* alternative = std::get_if<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<Color>>>>>(&converted_union_3.value())) return std::optional<std::variant<flight::Ref<Texture>, flight::Ref<Color>>>{std::in_place, std::in_place_type<flight::Ref<Color>>, flight::structural_ref_cast<flight::Ref<Color>>(*alternative)}; throw std::logic_error("source union alternative is not a readonly view of one the destination names"); }());
}

} // namespace flighthq_golden
