// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/awaitConditionAwait.ts#AwaitConditionAwait. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function decide(task:flighthq._internal._Promise<Bool>):flighthq._internal._Promise<Float> {
  return new flighthq._internal._Promise(function(resolveTask, rejectTask) {
    try {
      var total:Float = 0;
      flighthq._internal._Promise.resolve(task).then(
        function(awaitValue_2) {
          var awaitValue = awaitValue_2;
          try {
            if (flighthq._internal._Js.truthy(awaitValue)) {
              (total = 1);
            }
            else {
              (total = 2);
            }
            resolveTask(cast(total));
            return;
          } catch (taskError_2:Dynamic) {
            rejectTask(taskError_2);
          }
        },
        function(awaitError) {
          rejectTask(awaitError);
        }
      );
      return;
    } catch (taskError:Dynamic) {
      rejectTask(taskError);
    }
  });
}
