// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/catchAwait.ts#CatchAwait. Do not edit.
#pragma once
#include <coroutine>

namespace flighthq_golden {

FlightTask<double> attempt(FlightTask<double> task, FlightTask<double> backup) {
  double result = 0.0;
  try {
    result = co_await task;
  }
  catch (...) {
    result = co_await backup;
  }
  co_return result;
}

} // namespace flighthq_golden
