// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/tupleAccess.ts#TupleAccess. Do not edit.
#pragma once
#include <tuple>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline double first(std::tuple<double, flight::String> pair) {
  return std::get<0>(pair);
}

inline flight::String second(std::tuple<double, flight::String> pair) {
  return std::get<1>(pair);
}

inline std::tuple<flight::String, double> swap(std::tuple<double, flight::String> pair) {
  return std::make_tuple(std::get<1>(pair), std::get<0>(pair));
}

inline double sum_pair(std::tuple<double, double> pair) {
  return (std::get<0>(pair) + std::get<1>(pair));
}

} // namespace flighthq_golden
