// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericEnum.ts#NumericEnum. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

enum class level {
  Low = 1.0,
  High = 2.0,
};

struct Named {
  std::string name;
};

struct Tagged {
  std::string name;
  double tag;
};

std::string describe(Tagged value) {
  return value.name;
}

level highest() {
  return level::High;
}

} // namespace flighthq_golden
