// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/discriminatedUnion.ts#DiscriminatedUnion. Do not edit.
package flighthq.golden;

typedef Circle = { kind:String, radius:Float };

typedef Square = { kind:String, side:Float };

typedef Shape = Dynamic;

class DiscriminatedUnion {
  public static function area(shape:Shape):Float {
    if ((shape.kind == "circle")) {
      return ((shape.radius * shape.radius) * 3);
    }
    return (shape.side * shape.side);
  }
}
