// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/discriminatedUnion.ts#DiscriminatedUnion. Do not edit.
package flighthq.golden;

typedef Circle = { kind:String, radius:Float };

typedef Square = { kind:String, side:Float };

typedef Shape = { kind:String, ?radius:Float, ?side:Float };

class DiscriminatedUnion {
  public static function area(shape:Shape):Float {
    if (shape.kind == "circle") {
      return ((cast shape : Circle).radius * (cast shape : Circle).radius) * 3;
    }
    return (cast shape : Square).side * (cast shape : Square).side;
  }
}
