// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/discriminatedUnion.ts#DiscriminatedUnion. Do not edit.
package flighthq.golden;

typedef Circle = { kind:String, radius:Float };

typedef Square = { kind:String, side:Float };

typedef Shape = { kind:String, ?radius:Float, ?side:Float };

function area(shape:Shape):Float {
  if (flighthq._internal._Js.strictEqual(shape.kind, "circle")) {
    return (cast(shape).radius * cast(shape).radius) * 3;
  }
  return cast(shape).side * cast(shape).side;
}
