// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringSearch.ts#StringSearch. Do not edit.
package flighthq.golden;

function has(text:String, search:String):Bool {
  return StringTools.contains(text, search);
}

function prefix(text:String):Bool {
  return StringTools.startsWith(text, "hello");
}

function suffix(text:String):Bool {
  return StringTools.endsWith(text, "world");
}
