// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/optionalChainDefault.ts#OptionalChainDefault. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct Entry {
  pub key: String,
}

pub fn first_key(entries: Vec<Entry>) -> String {
  return entries[0].key.clone();
}
