// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/operators.ts#Operators. Do not edit.
#![forbid(unsafe_code)]

pub fn adjust(value: f64, mask: f64) -> f64 {
  let mut adjusted: f64 = value;
  adjusted += mask;
  adjusted *= 2.0;
  return -adjusted;
}

pub fn same(left: f64, right: f64) -> bool {
  return (left == right) && (left != 0.0);
}

pub fn negate(value: bool) -> bool {
  return !value;
}
