// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/variableHoisting.ts#VariableHoisting. Do not edit.
#pragma once
#include <string>
#include <tuple>
#include <vector>

namespace flighthq_golden {

double select_nested() {
  double value;
  {
    value = 1.0;
  }
  return value;
}

double select_loop(double limit) {
  double index;
  double total = 0.0;
  index = 0.0;
  {
    while ((index < limit)) {
      total += index;
      index += 1.0;
    }
  }
  return (total + index);
}

std::string select_pattern(std::tuple<double, std::string> values) {
  double first;
  std::string second;
  const std::tuple<double, std::string> array_pattern_value = values;
  first = array_pattern_value[static_cast<size_t>(0.0)];
  second = array_pattern_value[static_cast<size_t>(1.0)];
  if ((first < 0.0)) {
    return "";
  }
  return second;
}

void increment_values(std::vector<double> values) {
  double value;
  for (double variable_hoisting_iteration_value : values) {
    value = variable_hoisting_iteration_value;
    value += 1.0;
  }
}

} // namespace flighthq_golden
