// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/intersectionMergedShape.ts#IntersectionMergedShape. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef A = { ?a:Float, shared:String };

typedef B = { b:String, shared:String };

typedef BAlias = B;

function read(value:Dynamic):Null<Float> {
  return value.a;
}
