// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/partialNamedShape.ts#PartialNamedShape. Do not edit.
#![forbid(unsafe_code)]

use crate::provider::{Info, InfoAlias, NestedAlias};

#[derive(Clone, Debug)]
pub struct AnonymousObjectRecord {
  pub value: Option<f64>,
}

pub fn read_direct(values: AnonymousObjectRecord) -> Option<f64> {
  return values.value;
}

pub fn read_aliased(values: AnonymousObjectRecord) -> Option<f64> {
  return values.value;
}

pub fn read_nested(values: AnonymousObjectRecord) -> Option<f64> {
  return values.value;
}

pub fn write(values: &mut AnonymousObjectRecord) -> () {
  values.value = 1.0;
}
