// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/numericTruncation.ts#NumericTruncation. Do not edit.
package flighthq.golden;

function roundDown(value:Float):Float {
  return Math.floor(value);
}

function roundUp(value:Float):Float {
  return Math.ceil(value);
}

function roundNearest(value:Float):Float {
  return Math.round(value);
}

function fractionalPart(value:Float):Float {
  return value - Math.floor(value);
}

function roundToInt(value:Float):Float {
  return Math.floor((value + 0.5));
}
