// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/contextualUnionRemapShapes.ts#ContextualUnionRemapShapes. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Circle = { radius:Float };

typedef Aabb = { min:Float, max:Float };

typedef Obb = { center:Float, rotation:Float };

typedef Capsule = { start:Float, end:Float, radius:Float };

typedef Shape = Dynamic;
