// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/switchAwait.ts#SwitchAwait. Do not edit.
#pragma once
#include <coroutine>

namespace flighthq_golden {

FlightTask<double> pick(FlightTask<double> task, double mode) {
  double total = 0.0;
  {
    const auto switch_subject = mode;
    if ((switch_subject == 1.0)) {
      total = co_await task;
    }
    else {
      if ((switch_subject == 2.0)) {
        total = 20.0;
      }
      else {
        total = 30.0;
      }
    }
  }
  co_return total;
}

} // namespace flighthq_golden
