// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/privateField.ts#PrivateField. Do not edit.
#pragma once

namespace flighthq_golden {

struct counter {
  double count;
  void increment() {
    this->count += 1.0;
  }
  double get_count() {
    return this->count;
  }
  void reset() {
    this->count = 0.0;
  }
  void clear() {
    this->reset();
  }
};

} // namespace flighthq_golden
