// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/operators.ts#Operators. Do not edit.
package flighthq.golden;

class Operators {
  public static function adjust(value:Float, mask:Float):Float {
    var adjusted:Float = value;
    adjusted += mask;
    adjusted *= 2;
    return - adjusted;
  }

  public static function same(left:Float, right:Float):Bool {
    return (left == right) && (left != 0);
  }

  public static function negate(value:Bool):Bool {
    return ! value;
  }
}
