// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/recursion.ts#Recursion. Do not edit.
#pragma once
#include <cmath>
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline double factorial(double n) {
  if ((n <= 1.0)) {
    return 1.0;
  }
  return (n * factorial((n - 1.0)));
}

inline double fibonacci(double n) {
  if ((n <= 0.0)) {
    return 0.0;
  }
  if ((n == 1.0)) {
    return 1.0;
  }
  return (fibonacci((n - 1.0)) + fibonacci((n - 2.0)));
}

inline double gcd(double a, double b) {
  if ((b == 0.0)) {
    return a;
  }
  return gcd(b, std::fmod(a, b));
}

} // namespace flighthq_golden
