import type {
  CompilerCppAmbientMemberBinding,
  CppCompilerRuntimeProfile,
  IrResolvedMember,
} from '../../compiler-types/src/index.js';

export function getCompilerCppAmbientMemberBinding(
  member: Readonly<IrResolvedMember>,
  runtimeProfile: CppCompilerRuntimeProfile = 'standard-library',
): CompilerCppAmbientMemberBinding | undefined {
  const bindings = runtimeProfile === 'flight-cpp' ? cppFlightRuntimeAmbientMemberBindings : cppAmbientMemberBindings;
  return bindings[`${member.receiver}.${member.name}`];
}

const cppFlightRuntimeAmbientMemberBindings: Readonly<Record<string, CompilerCppAmbientMemberBinding>> = {
  'array.concat': { kind: 'method', targetName: 'concat' },
  'array.every': { kind: 'method', targetName: 'every' },
  'array.fill': { kind: 'method', targetName: 'fill' },
  'array.filter': { kind: 'method', targetName: 'filter' },
  'array.find': { kind: 'method', targetName: 'find' },
  'array.findIndex': { kind: 'method', targetName: 'find_index' },
  'array.forEach': { kind: 'method', targetName: 'for_each' },
  'array.includes': { kind: 'method', targetName: 'includes' },
  'array.indexOf': { kind: 'method', targetName: 'index_of' },
  'array.join': { kind: 'method', targetName: 'join' },
  'array.lastIndexOf': { kind: 'method', targetName: 'last_index_of' },
  'array.length': { kind: 'sizeMethod', targetName: 'size' },
  'array.map': { kind: 'method', targetName: 'map' },
  'array.pop': { kind: 'method', targetName: 'pop' },
  'array.push': { kind: 'method', targetName: 'push' },
  'array.reduce': { kind: 'method', targetName: 'reduce' },
  'array.reverse': { kind: 'method', targetName: 'reverse' },
  'array.shift': { kind: 'method', targetName: 'shift' },
  'array.slice': { kind: 'method', targetName: 'slice' },
  'array.some': { kind: 'method', targetName: 'some' },
  'array.sort': { kind: 'method', targetName: 'sort' },
  'array.splice': { kind: 'method', targetName: 'splice' },
  'array.unshift': { kind: 'method', targetName: 'unshift' },
  'arrayBuffer.byteLength': { kind: 'sizeMethod', targetName: 'byte_length' },
  'dataView.buffer': { kind: 'property', targetName: 'buffer' },
  'dataView.byteLength': { kind: 'property', targetName: 'byte_length' },
  'dataView.byteOffset': { kind: 'property', targetName: 'byte_offset' },
  'dataView.getFloat32': { kind: 'method', targetName: 'get_float32' },
  'dataView.getFloat64': { kind: 'method', targetName: 'get_float64' },
  'dataView.getInt8': { kind: 'method', targetName: 'get_int8' },
  'dataView.getInt16': { kind: 'method', targetName: 'get_int16' },
  'dataView.getInt32': { kind: 'method', targetName: 'get_int32' },
  'dataView.getUint8': { kind: 'method', targetName: 'get_uint8' },
  'dataView.getUint16': { kind: 'method', targetName: 'get_uint16' },
  'dataView.getUint32': { kind: 'method', targetName: 'get_uint32' },
  'dataView.setFloat32': { kind: 'method', targetName: 'set_float32' },
  'dataView.setFloat64': { kind: 'method', targetName: 'set_float64' },
  'dataView.setInt8': { kind: 'method', targetName: 'set_int8' },
  'dataView.setInt16': { kind: 'method', targetName: 'set_int16' },
  'dataView.setInt32': { kind: 'method', targetName: 'set_int32' },
  'dataView.setUint8': { kind: 'method', targetName: 'set_uint8' },
  'dataView.setUint16': { kind: 'method', targetName: 'set_uint16' },
  'dataView.setUint32': { kind: 'method', targetName: 'set_uint32' },
  'date.getDate': { kind: 'method', targetName: 'get_date' },
  'date.getDay': { kind: 'method', targetName: 'get_day' },
  'date.getFullYear': { kind: 'method', targetName: 'get_full_year' },
  'date.getHours': { kind: 'method', targetName: 'get_hours' },
  'date.getMilliseconds': { kind: 'method', targetName: 'get_milliseconds' },
  'date.getMinutes': { kind: 'method', targetName: 'get_minutes' },
  'date.getMonth': { kind: 'method', targetName: 'get_month' },
  'date.getSeconds': { kind: 'method', targetName: 'get_seconds' },
  'date.getTime': { kind: 'method', targetName: 'get_time' },
  'date.toISOString': { kind: 'method', targetName: 'to_isostring' },
  'date.toString': { kind: 'method', targetName: 'to_string' },
  'map.clear': { kind: 'method', targetName: 'clear' },
  'map.delete': { kind: 'method', targetName: 'erase' },
  'map.forEach': { kind: 'method', targetName: 'for_each' },
  'map.get': { kind: 'method', targetName: 'get' },
  'map.has': { kind: 'method', targetName: 'has' },
  'map.set': { kind: 'method', targetName: 'set' },
  'map.size': { kind: 'sizeMethod', targetName: 'size' },
  'number.toString': { kind: 'method', targetName: 'to_string' },
  'regexp.exec': { kind: 'method', targetName: 'exec' },
  'regexp.test': { kind: 'method', targetName: 'test' },
  'set.add': { kind: 'method', targetName: 'add' },
  'set.clear': { kind: 'method', targetName: 'clear' },
  'set.delete': { kind: 'method', targetName: 'erase' },
  'set.has': { kind: 'method', targetName: 'has' },
  'set.forEach': { kind: 'method', targetName: 'for_each' },
  'set.size': { kind: 'sizeMethod', targetName: 'size' },
  'string.charAt': { kind: 'method', targetName: 'char_at' },
  'string.charCodeAt': { kind: 'method', targetName: 'char_code_at' },
  'string.concat': { kind: 'method', targetName: 'concat' },
  'string.endsWith': { kind: 'method', targetName: 'ends_with' },
  'string.includes': { kind: 'method', targetName: 'includes' },
  'string.indexOf': { kind: 'method', targetName: 'index_of' },
  'string.lastIndexOf': { kind: 'method', targetName: 'last_index_of' },
  'string.length': { kind: 'sizeMethod', targetName: 'length' },
  'string.match': { kind: 'method', targetName: 'match' },
  'string.padStart': { kind: 'method', targetName: 'pad_start' },
  'string.repeat': { kind: 'method', targetName: 'repeat' },
  'string.replace': { kind: 'method', targetName: 'replace' },
  'string.slice': { kind: 'method', targetName: 'slice' },
  'string.split': { kind: 'method', targetName: 'split' },
  'string.startsWith': { kind: 'method', targetName: 'starts_with' },
  'string.substring': { kind: 'method', targetName: 'substring' },
  'string.toLowerCase': { kind: 'method', targetName: 'to_lower' },
  'string.toUpperCase': { kind: 'method', targetName: 'to_upper' },
  'string.trim': { kind: 'method', targetName: 'trim' },
  'task.catch': { kind: 'method', targetName: 'catch_error' },
  'task.finally': { kind: 'method', targetName: 'finally' },
  'task.then': { kind: 'method', targetName: 'then' },
  'textDecoder.decode': { kind: 'method', targetName: 'decode' },
  'typedArray.buffer': { kind: 'property', targetName: 'buffer' },
  'typedArray.byteLength': { kind: 'property', targetName: 'byte_length' },
  'typedArray.byteOffset': { kind: 'property', targetName: 'byte_offset' },
  'typedArray.fill': { kind: 'method', targetName: 'fill' },
  'typedArray.length': { kind: 'sizeMethod', targetName: 'size' },
  'typedArray.set': { kind: 'method', targetName: 'set' },
  'typedArray.slice': { kind: 'method', targetName: 'slice' },
  'typedArray.subarray': { kind: 'method', targetName: 'subarray' },
  'url.protocol': { kind: 'property', targetName: 'protocol' },
};

const cppAmbientMemberBindings: Readonly<Record<string, CompilerCppAmbientMemberBinding>> = {
  'array.concat': { kind: 'method', targetName: 'insert' },
  'array.filter': { algorithm: 'std::copy_if', kind: 'algorithm', targetName: 'copy_if' },
  'array.includes': { kind: 'method', targetName: 'contains' },
  'array.indexOf': { algorithm: 'std::find', kind: 'algorithm', targetName: 'find' },
  'array.join': { kind: 'method', targetName: 'join' },
  'array.length': { kind: 'sizeMethod', targetName: 'size' },
  'array.map': { algorithm: 'std::transform', kind: 'algorithm', targetName: 'transform' },
  'array.pop': { kind: 'method', targetName: 'pop_back' },
  'array.push': { kind: 'method', targetName: 'push_back' },
  'array.reverse': { kind: 'method', targetName: 'reverse' },
  'array.some': { algorithm: 'std::any_of', kind: 'algorithm', targetName: 'any_of' },
  'array.every': { algorithm: 'std::all_of', kind: 'algorithm', targetName: 'all_of' },
  'array.find': { algorithm: 'std::find_if', kind: 'algorithm', targetName: 'find_if' },
  'array.reduce': { algorithm: 'std::accumulate', kind: 'algorithm', targetName: 'accumulate' },
  'map.delete': { kind: 'method', targetName: 'erase' },
  'map.get': { kind: 'method', targetName: 'at' },
  'map.has': { kind: 'method', targetName: 'count' },
  'map.set': { kind: 'method', targetName: 'insert_or_assign' },
  'map.size': { kind: 'sizeMethod', targetName: 'size' },
  'number.toString': { kind: 'method', targetName: 'to_string' },
  'set.add': { kind: 'method', targetName: 'insert' },
  'set.delete': { kind: 'method', targetName: 'erase' },
  'set.has': { kind: 'method', targetName: 'count' },
  'set.size': { kind: 'sizeMethod', targetName: 'size' },
  'string.endsWith': { kind: 'method', targetName: 'ends_with' },
  'string.includes': { kind: 'method', targetName: 'contains' },
  'string.indexOf': { kind: 'method', targetName: 'find' },
  'string.length': { kind: 'sizeMethod', targetName: 'size' },
  'string.replace': { kind: 'method', targetName: 'replace' },
  'string.split': { kind: 'method', targetName: 'split' },
  'string.startsWith': { kind: 'method', targetName: 'starts_with' },
  'string.toLowerCase': { kind: 'method', targetName: 'to_lower' },
  'string.toUpperCase': { kind: 'method', targetName: 'to_upper' },
  'string.trim': { kind: 'method', targetName: 'trim' },
  'typedArray.length': { kind: 'sizeMethod', targetName: 'size' },
};
