// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/constrainedParameterInterfaceGuardRefused.ts#ConstrainedParameterInterfaceGuardRefused. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef RichTextContent = { ?plain:String };

function plainLength<T:Null<RichTextContent>>(content:T):Float {
  if (js.Syntax.strictEq(content, js.Syntax.code("undefined"))) {
    return 0;
  }
  return (flighthq._internal._Js.truthy(HaxeReflect.field(content, "plain")) ? HaxeReflect.field(content, "plain").length : 0);
}
