// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/multipleInterface.ts#MultipleInterface. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct Named {
  pub name: String,
}

#[derive(Clone, Debug)]
pub struct Valued {
  pub value: f64,
}

pub fn get_name(item: Named) -> String {
  return item.name;
}

pub fn get_value(item: Valued) -> f64 {
  return item.value;
}

pub fn format_named(item: Named) -> String {
  return format!("item: {}", item.name);
}

pub fn is_positive(item: Valued) -> bool {
  return item.value > 0.0;
}
