// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/optionalCoalesce.ts#OptionalCoalesce. Do not edit.
#pragma once
#include <optional>
#include <flight/runtime.hpp>

namespace flighthq_golden {

struct Holder {
  double value;
};

inline double read(std::optional<Holder> holder) {
  return ([&]() -> std::optional<double> { auto optional_chain_receiver = holder; if (!optional_chain_receiver.has_value()) return std::nullopt; return optional_chain_receiver.value().value; }()).value_or(0.0);
}

} // namespace flighthq_golden
