// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/optionalCoalesce.ts#OptionalCoalesce. Do not edit.
#pragma once
#include <optional>

namespace flighthq_golden {

struct holder {
  double value;
};

double read(std::optional<holder> holder) {
  return holder.value.value_or(0.0);
}

} // namespace flighthq_golden
