// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/forOfLoop.ts#ForOfLoop. Do not edit.
#![forbid(unsafe_code)]

pub fn sum(values: Vec<f64>) -> f64 {
  let mut total: f64 = 0.0;
  for value in values {
    total = total + value;
  }
  return total;
}

pub fn collect(items: Vec<String>) -> String {
  let mut result: String = "".to_owned();
  for item in items {
    result = format!("{}{}", result, item);
  }
  return result;
}
