// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeNamespace.ts#TypeNamespace. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

std::string get_default_name() {
  return "default";
}

double get_default_value() {
  return 0.0;
}

} // namespace flighthq_golden
