// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeNamespace.ts#TypeNamespace. Do not edit.
#pragma once
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

inline flight::String get_default_name() {
  return flight::String("default");
}

inline double get_default_value() {
  return 0.0;
}

} // namespace flighthq_golden
