// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringCharCode.ts#StringCharCode. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

double char_code_first(std::string text) {
  return text.char_code_at(0.0);
}

bool is_digit_code(std::string text, double index) {
  const double code = text.char_code_at(index);
  return ((code >= 48.0) && (code <= 57.0));
}

double sum_char_codes(std::string text) {
  double total = 0.0;
  {
    double i = 0.0;
    while ((i < static_cast<double>(text.size()))) {
      {
        total = (total + text.char_code_at(i));
      }
      i = (i + 1.0);
    }
  }
  return total;
}

} // namespace flighthq_golden
