// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/readonlyProperty.ts#ReadonlyProperty. Do not edit.
#pragma once
#include <string>

namespace flighthq_golden {

struct config {
  double width;
  double height;
  std::string label;
};

double get_area(config config) {
  return (config.width * config.height);
}

std::string get_label(config config) {
  return config.label;
}

double get_perimeter(config config) {
  return (2.0 * (config.width + config.height));
}

} // namespace flighthq_golden
