// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/firstReplacement.ts#FirstReplacement. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

inline flight::String swapped(flight::String text) {
  return text.replace(flight::String("a"), flight::String("b"));
}

} // namespace flighthq_golden
