// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/spreadCall.ts#SpreadCall. Do not edit.
package flighthq.golden;

function widest(values:Array<Float>):Float {
  return Reflect.callMethod(Math, cast(Math.max), values);
}
