// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typedArraySemantics.ts#TypedArraySemantics. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function signedRangeConstruction():flighthq._internal._Int8Array {
  final zero:Float = 0;
  final values:flighthq._internal._Int8Array = (cast new flighthq._internal._Int8Array([(cast 130 : Float), - 129, (zero / zero), (1 / zero)]) : flighthq._internal._Int8Array);
  return (cast values : flighthq._internal._Int8Array);
}

function unsignedModuloWrites():flighthq._internal._UInt8Array {
  final values:flighthq._internal._UInt8Array = (cast new flighthq._internal._UInt8Array(Std.int(5)) : flighthq._internal._UInt8Array);
  (values[0] = Std.int(300));
  (values[1] = Std.int(- 1));
  (values[2] = Std.int(1));
  (values[2] += 257);
  (values[3] = Std.int(255));
  (values[3] += 2);
  (values[4] = Std.int(250));
  (values[4] %= 64);
  return (cast values : flighthq._internal._UInt8Array);
}

function clampedTies():flighthq._internal._UInt8ClampedArray {
  final values:flighthq._internal._UInt8ClampedArray = (cast new flighthq._internal._UInt8ClampedArray(Std.int(6)) : flighthq._internal._UInt8ClampedArray);
  (values[0] = Std.int(0.5));
  (values[1] = Std.int(1.5));
  (values[2] = Std.int(2.5));
  (values[3] = Std.int(3.5));
  (values[4] = Std.int(254.5));
  (values[5] = Std.int(255.5));
  return (cast values : flighthq._internal._UInt8ClampedArray);
}

function float32Overflow():flighthq._internal._Float32Array {
  final values:flighthq._internal._Float32Array = (cast new flighthq._internal._Float32Array(Std.int(2)) : flighthq._internal._Float32Array);
  (values[0] = 3.5e+38);
  (values[1] = - 3.5e+38);
  return (cast values : flighthq._internal._Float32Array);
}

function subarrayAliasesStorage():flighthq._internal._UInt8Array {
  final source:flighthq._internal._UInt8Array = (cast new flighthq._internal._UInt8Array([(cast 1 : Float), 2, 3, 4]) : flighthq._internal._UInt8Array);
  final view:flighthq._internal._UInt8Array = (cast source.subarray(1, 3) : flighthq._internal._UInt8Array);
  (view[0] = Std.int(9));
  (source[2] = Std.int(8));
  return (cast source : flighthq._internal._UInt8Array);
}

function sliceCopiesStorage():flighthq._internal._UInt8Array {
  final source:flighthq._internal._UInt8Array = (cast new flighthq._internal._UInt8Array([(cast 1 : Float), 2, 3, 4]) : flighthq._internal._UInt8Array);
  final copy:flighthq._internal._UInt8Array = (cast source.slice(1, 3) : flighthq._internal._UInt8Array);
  (copy[0] = Std.int(9));
  (source[2] = Std.int(8));
  return (cast copy : flighthq._internal._UInt8Array);
}

function viewsHaveDistinctIdentity():Bool {
  final source:flighthq._internal._UInt8Array = (cast new flighthq._internal._UInt8Array([(cast 1 : Float), 2]) : flighthq._internal._UInt8Array);
  return ((source.subarray(0) != source) && (source.slice(0) != source)) && (source.subarray(0) != source.subarray(0));
}

function bufferBackedViewsShareStorage():flighthq._internal._UInt8Array {
  final buffer:flighthq._internal._ArrayBuffer = (cast new flighthq._internal._ArrayBuffer(Std.int(4)) : flighthq._internal._ArrayBuffer);
  final whole:flighthq._internal._UInt8Array = (cast new flighthq._internal._UInt8Array(buffer) : flighthq._internal._UInt8Array);
  final middle:flighthq._internal._UInt8Array = (cast new flighthq._internal._UInt8Array(buffer, 1, 2) : flighthq._internal._UInt8Array);
  (middle[0] = Std.int(9));
  (middle[1] = Std.int(8));
  return (cast whole : flighthq._internal._UInt8Array);
}

function dataViewAliasesTypedArray():flighthq._internal._UInt8Array {
  final bytes:flighthq._internal._UInt8Array = (cast new flighthq._internal._UInt8Array(Std.int(8)) : flighthq._internal._UInt8Array);
  final view:flighthq._internal._DataView = (cast new flighthq._internal._DataView(bytes.buffer, 1, 6) : flighthq._internal._DataView);
  view.setUint32(0, 16909060);
  view.setUint16(4, 1286, true);
  final matches:Bool = ((((view.getUint32(0) == 16909060) && (view.getUint16(4, true) == 1286)) && (view.byteLength == 6)) && (view.byteOffset == 1)) && (view.buffer == bytes.buffer);
  (bytes[7] = Std.int((matches ? 1 : 0)));
  return (cast bytes : flighthq._internal._UInt8Array);
}
