// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/generics.ts#Generics. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Pair<Left, Right> = { left:Left, right:Right };

function identity<Value>(value:Value):Value {
  return value;
}
