// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/generics.ts#Generics. Do not edit.
package flighthq.golden;

typedef Pair<Left, Right> = { left:Left, right:Right };

class Generics {
  public static function identity<Value>(value:Value):Value {
    return value;
  }
}
