// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/objectBinding.ts#ObjectBinding. Do not edit.
#pragma once
#include <flight/runtime.hpp>

namespace flighthq_golden {

struct other_value {
  bool other;
  double value;
};

using Shape = other_value;

inline double project(Shape parameter_pattern_value, Shape source) {
  double value;
  Shape object_pattern_value = parameter_pattern_value;
  value = object_pattern_value.value;
  double assigned = 0.0;
  {
    Shape destructuring_assignment_value = source;
    assigned = destructuring_assignment_value.value;
  }
  return (value + assigned);
}

} // namespace flighthq_golden
