// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/objectBinding.ts#ObjectBinding. Do not edit.
#pragma once

namespace flighthq_golden {

struct other_value {
  bool other;
  double value;
};

using shape = other_value;

double project(shape parameter_pattern_value, shape source) {
  double value;
  const shape object_pattern_value = parameter_pattern_value;
  value = object_pattern_value.value;
  double assigned = 0.0;
  {
    const shape destructuring_assignment_value = source;
    assigned = destructuring_assignment_value.value;
  }
  return (value + assigned);
}

} // namespace flighthq_golden
