// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/arrayLiteral.ts#ArrayLiteral. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

function singleElement():Array<Float> {
  return ([(cast 42 : Float)] : Array<Float>);
}

function threeElements():Array<Float> {
  return ([(cast 1 : Float), 2, 3] : Array<Float>);
}

function emptyArray():Array<Float> {
  return (cast [] : Array<Float>);
}

function computed(a:Float, b:Float):Array<Float> {
  return ([(cast a : Float), b, (a + b), (a * b)] : Array<Float>);
}

function nested(x:Float):Array<Array<Float>> {
  return ([([(cast x : Float)] : Array<Float>), ([(cast (x + 1) : Float), (x + 2)] : Array<Float>)] : Array<Array<Float>>);
}
