// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/cascadeGuard.ts#CascadeGuard. Do not edit.
#![forbid(unsafe_code)]

pub fn is_leap_year(year: f64) -> bool {
  if (year - (400.0 * f64::floor((year / 400.0)))) == 0.0 {
    return true;
  }
  if (year - (100.0 * f64::floor((year / 100.0)))) == 0.0 {
    return false;
  }
  if (year - (4.0 * f64::floor((year / 4.0)))) == 0.0 {
    return true;
  }
  return false;
}

pub fn is_valid_triangle(a: f64, b: f64, c: f64) -> bool {
  if a <= 0.0 {
    return false;
  }
  if b <= 0.0 {
    return false;
  }
  if c <= 0.0 {
    return false;
  }
  if (a + b) <= c {
    return false;
  }
  if (a + c) <= b {
    return false;
  }
  if (b + c) <= a {
    return false;
  }
  return true;
}

pub fn classify_bmi(weight: f64, height: f64) -> String {
  if height <= 0.0 {
    return "invalid".to_owned();
  }
  if weight <= 0.0 {
    return "invalid".to_owned();
  }
  let bmi: f64 = weight / (height * height);
  if bmi < 18.5 {
    return "underweight".to_owned();
  }
  if bmi < 25.0 {
    return "normal".to_owned();
  }
  if bmi < 30.0 {
    return "overweight".to_owned();
  }
  return "obese".to_owned();
}

pub fn safe_reciprocal(value: f64) -> f64 {
  if value == 0.0 {
    return 0.0;
  }
  return 1.0 / value;
}
