// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/assertionInheritedAlternativeRecovery.ts#AssertionInheritedAlternativeRecovery. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

private class BaseShape {
  public var id:String = "";

  public function new() {}
}

private class DerivedShape extends BaseShape {
  public var extra:Float;

  public function new() {
    super();
    this.extra = 0;
  }
}

typedef Other = { tag:Float };

function narrow(value:Dynamic):Null<DerivedShape> {
  return (cast value : Null<DerivedShape>);
}
