// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/genericElement.ts#GenericElement. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
pub struct Box<Value: Clone> {
  pub contents: Value,
}

pub fn unwrap<Value: Clone>(box_: Box<Value>) -> Value {
  return box_.contents;
}

pub fn first_of<Value: Clone>(values: Vec<Value>, fallback: Value) -> Value {
  let first: Option<Value> = values.get(0).cloned();
  return first.unwrap_or_else(|| fallback);
}

pub fn second_name(pair: (String, String)) -> String {
  let second: String = pair.1;
  return second;
}
