// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/abstractField.ts#AbstractField. Do not edit.
package flighthq.golden;

abstract class Component {
  public var name:String;

  public var version:Float;

  public function new() {}

  public function describe():String {
    return this.name;
  }

  public function getVersion():Float {
    return this.version;
  }
}

class Button extends Component {

  public function new() {
    super();
    this.name = "button";
    this.version = 1;
  }
}

class DeclareExample {
  public var label:String;

  public var value:Float = 0;

  public function new() {}

  public function getLabel():String {
    return this.label;
  }
}
