// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/closedKeyWriteDispatch.ts#ClosedKeyWriteDispatch. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Pairs = { ?alpha:Float, ?beta:Float };

function set(pairs:Pairs, key:Dynamic, value:Float):Void {
  (function() { final assignmentReceiver:Dynamic = pairs; final assignmentKey:Dynamic = key; final assignmentValue:Dynamic = value; flighthq._internal._Js.setProperty(assignmentReceiver, assignmentKey, assignmentValue); return assignmentValue; })();
}
