// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/mathMembers.ts#MathMembers. Do not edit.
package flighthq.golden;

class MathMembers {
  public static function widest(first:Float, second:Float):Float {
    return Math.max(first, Math.abs(second));
  }
}
