// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/unionMemberAliasAssertion.ts#UnionMemberAliasAssertion. Do not edit.
package flighthq.golden;

import Reflect as HaxeReflect;

typedef Runtime = { kind:String };

typedef RuntimeAlias = Runtime;

typedef NestedAlias = RuntimeAlias;

typedef Slot = Dynamic;

function narrowNested(value:Dynamic):NestedAlias {
  return (cast value : NestedAlias);
}

function narrowFromAliasedUnion(value:Slot):RuntimeAlias {
  return (cast value : RuntimeAlias);
}
