// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/guardClause.ts#GuardClause. Do not edit.
#pragma once
#include <string>
#include <vector>

namespace flighthq_golden {

double safe_sqrt(double value) {
  if ((value < 0.0)) {
    return -1.0;
  }
  return std::sqrt(value);
}

std::string classify(double value) {
  if ((value != value)) {
    return "nan";
  }
  if ((value == 0.0)) {
    return "zero";
  }
  if ((value < 0.0)) {
    return "negative";
  }
  if ((value < 1.0)) {
    return "fraction";
  }
  return "positive";
}

double first_positive(std::vector<double> values) {
  for (double value : values) {
    if ((value > 0.0)) {
      return value;
    }
  }
  return -1.0;
}

double bounded_sum(std::vector<double> values, double limit) {
  double total = 0.0;
  for (double value : values) {
    if (((total + value) > limit)) {
      return total;
    }
    total = (total + value);
  }
  return total;
}

} // namespace flighthq_golden
