// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/typeofNarrowing.ts#TypeofNarrowing. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Debug)]
enum StrOrF64 {
  Str(String),
  F64(f64),
}

impl StrOrF64 {
  fn as_str(&self) -> &String {
    match self {
      StrOrF64::Str(value) => value,
      _ => panic!("StrOrF64 is not Str"),
    }
  }
  fn as_f64(&self) -> &f64 {
    match self {
      StrOrF64::F64(value) => value,
      _ => panic!("StrOrF64 is not F64"),
    }
  }
}

impl std::fmt::Display for StrOrF64 {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    match self {
      StrOrF64::Str(value) => write!(f, "{}", value),
      StrOrF64::F64(value) => write!(f, "{}", value),
    }
  }
}

#[derive(Clone, Debug)]
enum StrOrF64OrBool {
  Str(String),
  F64(f64),
  Bool(bool),
}

impl StrOrF64OrBool {
  fn as_str(&self) -> &String {
    match self {
      StrOrF64OrBool::Str(value) => value,
      _ => panic!("StrOrF64OrBool is not Str"),
    }
  }
  fn as_f64(&self) -> &f64 {
    match self {
      StrOrF64OrBool::F64(value) => value,
      _ => panic!("StrOrF64OrBool is not F64"),
    }
  }
  fn as_bool(&self) -> &bool {
    match self {
      StrOrF64OrBool::Bool(value) => value,
      _ => panic!("StrOrF64OrBool is not Bool"),
    }
  }
}

impl std::fmt::Display for StrOrF64OrBool {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    match self {
      StrOrF64OrBool::Str(value) => write!(f, "{}", value),
      StrOrF64OrBool::F64(value) => write!(f, "{}", value),
      StrOrF64OrBool::Bool(value) => write!(f, "{}", value),
    }
  }
}

pub fn describe(value: StrOrF64) -> String {
  if matches!(value, StrOrF64::Str(_)) {
    return value.as_str().to_uppercase();
  }
  return format!("number {}", *value.as_f64());
}

pub fn length(value: StrOrF64) -> f64 {
  if matches!(value, StrOrF64::F64(_)) {
    return 1.0;
  }
  return value.as_str().len() as f64;
}

pub fn classify(value: StrOrF64OrBool) -> String {
  if matches!(value, StrOrF64OrBool::Str(_)) {
    return "text".to_owned();
  }
  if matches!(value, StrOrF64OrBool::F64(_)) {
    return "count".to_owned();
  }
  return "flag".to_owned();
}
