// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/negativeArithmetic.ts#NegativeArithmetic. Do not edit.
package flighthq.golden;

function negate(value:Float):Float {
  return - value;
}

function doubleNegate(value:Float):Float {
  return - - value;
}

function subtractFromZero(value:Float):Float {
  return 0 - value;
}

function negativeProduct(a:Float, b:Float):Float {
  return - (a * b);
}

function absoluteDifference(a:Float, b:Float):Float {
  final diff:Float = a - b;
  return (diff < 0) ? - diff : diff;
}
