// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/guardClause.ts#GuardClause. Do not edit.
package flighthq.golden;

function safeSqrt(value:Float):Float {
  if (value < 0) {
    return - 1;
  }
  return Math.sqrt(value);
}

function classify(value:Float):String {
  if (value != value) {
    return "nan";
  }
  if (value == 0) {
    return "zero";
  }
  if (value < 0) {
    return "negative";
  }
  if (value < 1) {
    return "fraction";
  }
  return "positive";
}

function firstPositive(values:Array<Float>):Float {
  for (value in values) {
    if (value > 0) {
      return value;
    }
  }
  return - 1;
}

function boundedSum(values:Array<Float>, limit:Float):Float {
  var total:Float = 0;
  for (value in values) {
    if ((total + value) > limit) {
      return total;
    }
    total = (total + value);
  }
  return total;
}
