// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/genericFunction.ts#GenericFunction. Do not edit.
#![forbid(unsafe_code)]

pub fn identity<T>(value: T) -> T {
  return value;
}

pub fn first_element<T>(items: Vec<T>) -> T {
  return items[0].clone();
}

pub fn pair<A, B>(a: A, b: B) -> (A, B) {
  return (a, b);
}
