// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/stringEnum.ts#StringEnum. Do not edit.
#pragma once
#include <utility>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 2, "Flight C++ runtime ABI mismatch");

namespace flighthq_golden {

struct Lane {
  flight::String value;
  Lane(flight::String source) : value(std::move(source)) {}
  operator const flight::String&() const noexcept { return value; }
  friend bool operator==(const Lane&, const Lane&) noexcept = default;
  static const Lane Fast;
  static const Lane Safe;
};
inline const Lane Lane::Fast{flight::String("fast")};
inline const Lane Lane::Safe{flight::String("safe")};

} // namespace flighthq_golden
