// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/conditionalAwait.ts#ConditionalAwait. Do not edit.
#![forbid(unsafe_code)]

use flight_runtime::FlightTask;

pub async fn choose(task: FlightTask<f64>, flag: bool) -> f64 {
  let mut total: f64 = 0.0;
  if flag {
    total = task.await;
  }
  else {
    total = 1.0;
  }
  return total;
}
