// Generated by @flighthq/tool-compiler from @flighthq/golden/packages/golden/src/closureCompoundAssignment.ts#ClosureCompoundAssignment. Do not edit.
#![forbid(unsafe_code)]

use std::cell::Cell;
use std::rc::Rc;

pub fn captured_power(base: f64) -> Rc<dyn Fn() -> f64> {
  let value: Rc<Cell<f64>> = Rc::new(Cell::new(base));
  return {
  let value = Rc::clone(&value);
  Rc::new(move || {
  value.set(value.get() ** 2.0);
  return value.get();
})
};
}

pub fn captured_or(initial: f64) -> Rc<dyn Fn(f64) -> f64> {
  let value: Rc<Cell<f64>> = Rc::new(Cell::new(initial));
  return {
  let value = Rc::clone(&value);
  Rc::new(move |fallback| {
  value.set(value.get() || fallback);
  return value.get();
})
};
}

pub fn captured_and(initial: f64) -> Rc<dyn Fn(f64) -> f64> {
  let value: Rc<Cell<f64>> = Rc::new(Cell::new(initial));
  return {
  let value = Rc::clone(&value);
  Rc::new(move |replacement| {
  value.set(value.get() && replacement);
  return value.get();
})
};
}

pub fn captured_nullish(initial: Option<String>) -> Rc<dyn Fn(String) -> String> {
  let value: Rc<Cell<Option<String>>> = Rc::new(Cell::new(initial));
  return {
  let value = Rc::clone(&value);
  Rc::new(move |fallback| {
  value.set(value.get() ?? fallback);
  return value.get();
})
};
}

pub fn captured_unsigned_shift(initial: f64) -> Rc<dyn Fn(f64) -> f64> {
  let value: Rc<Cell<f64>> = Rc::new(Cell::new(initial));
  return {
  let value = Rc::clone(&value);
  Rc::new(move |bits| {
  value.set(value.get() >>> bits);
  return value.get();
})
};
}

pub fn captured_bitwise_or(initial: f64) -> Rc<dyn Fn(f64) -> f64> {
  let value: Rc<Cell<f64>> = Rc::new(Cell::new(initial));
  return {
  let value = Rc::clone(&value);
  Rc::new(move |mask| {
  value.set(value.get() | mask);
  return value.get();
})
};
}

pub fn captured_bitwise_and(initial: f64) -> Rc<dyn Fn(f64) -> f64> {
  let value: Rc<Cell<f64>> = Rc::new(Cell::new(initial));
  return {
  let value = Rc::clone(&value);
  Rc::new(move |mask| {
  value.set(value.get() & mask);
  return value.get();
})
};
}
